/**
 * THE L012 INTEGRATION TEST — REAL sources fused through the ONE canonical
 * engine, per the acceptance's own example composition:
 *
 * ```text
 * L002 deterministic tracking (TRACKING)      ─┐
 * L011 broadcast-perception seam over a REAL  ─┤→ LiveFusionEngine
 *      generated MP4 (BROADCAST_PERCEPTION)   ─┤   → TemporalBufferEngine (L004)
 * L007 SkillCorner open-data replay (TRACKING,─┘   → LiveSwmUpdater (L003)
 *      FORMAT-FIXTURE jsonl — the recorded schema)      → WorldModelEngine (the ONE SWM)
 * ```
 *
 * THE ACCEPTANCE PINS:
 *
 * - COEXISTENCE: all three sources feed the SAME session through the same
 *   L004→L003 composition; every batch passes VERBATIM (disjoint entity
 *   spaces — no cross-source co-observation); all three sources' entities
 *   live in the ONE engine; per-source provenance rides the W005 bridge
 *   (componentId + provenance per source — VERBATIM);
 * - CONFLICTS + ARBITRATION (real, not fixtures): TWO L002 sources with the
 *   same roster ids but different seeds observe the SAME entities at the
 *   same times with materially different positions → ConflictRecords minted
 *   (the batch ledger shape), same-time ties arbitrated by the canonical
 *   replay order, losers withheld (counted, never bridged), the engine
 *   follows the canonical survivor;
 * - SOURCE LOSS + FALLBACK: when one stream stops, the L004 STALLED latch
 *   fires → the fusion report records source-lost + fallbackActive while
 *   the surviving source keeps the world alive;
 * - §9 MULTI-SOURCE ACCOUNTING: per-source summaries carry the L004
 *   counters verbatim; the fusion counters add the multi-source facts;
 * - D8 REPLAY EQUALITY: a batch `runWorldFusion` pass over the SAME bridged
 *   store reproduces the live final state (the arbitrated stream IS the
 *   stored stream) — for BOTH compositions.
 *
 * FIXTURE HONESTY: the SkillCorner frames are FORMAT-FIXTURES (the recorded
 * published schema with synthetic values — no sample data committed); the
 * MP4 is generated by the real ffmpeg at test time (skipped honestly when
 * the binary is unavailable — the repo convention); the L002 sources are
 * the real deterministic synthetic sources.
 */
import { afterAll, describe, expect, test } from "bun:test";
import { mkdirSync, rmSync } from "node:fs";
import { join } from "node:path";
import { FfmpegTool, generateTestMp4 } from "@sporta/media-platform";
import type { CalibrationResult } from "@sporta/perception-adapters";
import type { LiveObservation } from "@sporta/live-source";
import { createDeterministicLiveSource, drainSource } from "@sporta/live-source";
import {
  createSkillCornerOpenDataReplay,
  SKILLCORNER_DEFAULT_SOURCE_ID,
} from "@sporta/live-open-data";
import { createBroadcastPerceptionClipSource } from "@sporta/live-perception";
import { createTemporalBufferEngine } from "@sporta/live-temporal";
import { createLiveSwmUpdater } from "@sporta/live-swm";
import { runWorldFusion } from "@sporta/fusion";
import { WorldModelEngine } from "@sporta/world-model";
import { InMemoryObservationStore } from "@sporta/observation";
import type { ObservationStore } from "@sporta/observation";
import {
  PITCH_AXES,
  PITCH_LENGTH_AXIS_METERS,
  PITCH_ORIGIN,
  PITCH_WIDTH_AXIS_METERS,
} from "@sporta/contracts";
import type { FootballState } from "@sporta/world-model";
import { createLiveFusionEngine, type FusionReport, type LiveFusionEngine } from "../src/index";

const SESSION_ID = "s-l012-integration";

/** The minimal valid football state (the fusion test convention, mirrored). */
function makeFootballState(): FootballState {
  return {
    pitch: {
      lengthAxisMeters: PITCH_LENGTH_AXIS_METERS,
      widthAxisMeters: PITCH_WIDTH_AXIS_METERS,
      origin: PITCH_ORIGIN,
      axes: PITCH_AXES,
    },
    clock: { period: "first-half", clockMs: 0, stoppage: false },
    score: { home: 0, away: 0, status: { status: "unknown" } },
    possession: { status: "unknown" },
    eventTaxonomyVersion: "1",
  };
}

// ---------------------------------------------------------------------------
// The SkillCorner FORMAT-FIXTURE jsonl (the recorded published schema,
// synthetic values — mirrored from the L007 battery, no sample data)
// ---------------------------------------------------------------------------

function frameLine(input: {
  frame: number;
  timestamp: string | null;
  period: 1 | 2 | null;
  players: Array<{ x: number; y: number; id: number; detected: boolean | null }>;
  ball: { x: number | null; y: number | null; z: number | null; detected: boolean | null };
}): string {
  return JSON.stringify({
    frame: input.frame,
    timestamp: input.timestamp,
    period: input.period,
    ball_data: { x: input.ball.x, y: input.ball.y, z: input.ball.z, is_detected: input.ball.detected },
    possession: { player_id: null, group: null },
    image_corners_projection: {
      x_top_left: null,
      y_top_left: null,
      x_bottom_left: null,
      y_bottom_left: null,
      x_bottom_right: null,
      y_bottom_right: null,
      x_top_right: null,
      y_top_right: null,
    },
    player_data: input.players.map((player) => ({
      x: player.x,
      y: player.y,
      player_id: player.id,
      is_detected: player.detected,
    })),
  });
}

const SKILLCORNER_FIXTURE_JSONL = [
  frameLine({ frame: 2, timestamp: "00:00:00.20", period: 1, players: [
    { x: -40.5, y: -10.25, id: 101, detected: true },
    { x: -20.0, y: 5.5, id: 102, detected: true },
  ], ball: { x: 0.5, y: 0.25, z: 0.11, detected: true } }),
  frameLine({ frame: 3, timestamp: "00:00:00.30", period: 1, players: [
    { x: -40.2, y: -10.1, id: 101, detected: true },
    { x: -20.1, y: 5.4, id: 102, detected: true },
  ], ball: { x: 0.7, y: 0.3, z: 0.0, detected: false } }),
  frameLine({ frame: 4, timestamp: "00:00:00.40", period: 1, players: [
    { x: -39.9, y: -9.9, id: 101, detected: true },
    { x: -19.5, y: 5.2, id: 102, detected: true },
  ], ball: { x: 0.9, y: 0.4, z: 0.0, detected: true } }),
].join("\n");

// ---------------------------------------------------------------------------
// The broadcast-perception clip (real ffmpeg — skipped honestly when absent)
// ---------------------------------------------------------------------------

const tool = new FfmpegTool();
const hasFfmpeg = await tool.available();
const WORK_DIR = join(import.meta.dir, ".tmp-integration");
const CLIP_PATH = join(WORK_DIR, "pitch-scene.mp4");
let clipBytes: Uint8Array | null = null;
if (hasFfmpeg) {
  mkdirSync(WORK_DIR, { recursive: true });
  await generateTestMp4(CLIP_PATH, {
    scene: "pitch",
    durationSeconds: 2,
    width: 320,
    height: 240,
    frameRate: 24,
    withAudio: false,
  });
  clipBytes = new Uint8Array(await Bun.file(CLIP_PATH).arrayBuffer());
}
afterAll(() => {
  if (hasFfmpeg) rmSync(WORK_DIR, { recursive: true, force: true });
});

/** The known scene geometry (the L011 integration test's injected calibration). */
const FULL_FRAME_CALIBRATION: CalibrationResult = {
  mapping: {
    kind: "field-mapping",
    pitchCorners: [
      { x: 0, y: 0 },
      { x: 1, y: 0 },
      { x: 1, y: 1 },
      { x: 0, y: 1 },
    ],
  },
  homography: [105, 0, 0, 0, 68, 0, 0, 0, 1],
  cornerSet: {
    corners: [
      { x: 0, y: 0 },
      { x: 1, y: 0 },
      { x: 1, y: 1 },
      { x: 0, y: 1 },
    ],
    cornerOrder: "tl, tr, br, bl",
    confidence: 1,
  },
  confidence: 1,
  correspondenceCount: 4,
};

// ---------------------------------------------------------------------------
// The composition driver (the continuity battery's pattern, multi-source)
// ---------------------------------------------------------------------------

interface Composition {
  engine: WorldModelEngine;
  store: ObservationStore;
  fusion: LiveFusionEngine;
  reports: FusionReport[];
}

/** Drives N arrival streams through the ONE fusion composition, then finalizes. */
function driveComposition(
  arrivals: readonly LiveObservation[],
  options?: { policy?: Parameters<typeof createLiveFusionEngine>[0]["policy"]; endClockMs?: number },
): Composition {
  const engine = WorldModelEngine.create(SESSION_ID, {
    football: makeFootballState(),
    now: () => 0,
  });
  const store = new InMemoryObservationStore();
  const updater = createLiveSwmUpdater({ sessionId: SESSION_ID, engine, store });
  const temporal = createTemporalBufferEngine({ sessionId: SESSION_ID });
  const fusion = createLiveFusionEngine({
    sessionId: SESSION_ID,
    temporal,
    updater,
    ...(options?.policy !== undefined ? { policy: options.policy } : {}),
  });
  const reports: FusionReport[] = [];
  const sorted = [...arrivals].sort((a, b) => a.ingestTimeMs - b.ingestTimeMs);
  const lastIngestMs = sorted.length > 0 ? sorted[sorted.length - 1]!.ingestTimeMs : 0;
  const endClockMs = options?.endClockMs ?? lastIngestMs + 400;
  let next = 0;
  let clock = 0;
  while (clock <= endClockMs) {
    while (next < sorted.length && sorted[next]!.ingestTimeMs <= clock) {
      reports.push(fusion.admit(sorted[next]!));
      next += 1;
    }
    reports.push(fusion.tick(clock));
    clock += 100;
  }
  while (next < sorted.length) {
    reports.push(fusion.admit(sorted[next]!));
    next += 1;
  }
  reports.push(fusion.finalize());
  return { engine, store, fusion, reports };
}

/** Collects a pull-source's whole stream (planned ingest → next batch). */
function collectPulls(source: {
  plannedIngestTimeMs(): number | null;
  next(): LiveObservation | null;
}): LiveObservation[] {
  const batches: LiveObservation[] = [];
  for (;;) {
    if (source.plannedIngestTimeMs() === null) break;
    const batch = source.next();
    if (batch === null) break;
    batches.push(batch);
  }
  return batches;
}

/** Asserts the D8 replay equality over the bridged store (semantic state). */
function expectReplayEquality(composition: Composition): void {
  const replayEngine = WorldModelEngine.create(SESSION_ID, {
    football: makeFootballState(),
    now: () => 0,
  });
  runWorldFusion({ store: composition.store, engine: replayEngine, sessionId: SESSION_ID });
  const liveIds = [...composition.engine.entityIds].sort();
  const replayIds = [...replayEngine.entityIds].sort();
  expect(replayIds).toEqual(liveIds);
  for (const entityId of liveIds) {
    const liveEntity = composition.engine.entityAt(entityId)!;
    const replayEntity = replayEngine.entityAt(entityId)!;
    expect(replayEntity.kind).toBe(liveEntity.kind);
    expect(replayEntity.lastEventTimeMs).toBe(liveEntity.lastEventTimeMs);
    expect(JSON.stringify(replayEntity.state)).toBe(JSON.stringify(liveEntity.state));
  }
}

// ---------------------------------------------------------------------------

describe("L012 integration — three REAL sources fused into the ONE canonical engine", () => {
  test.skipIf(!hasFfmpeg)("L002 tracking + L011 broadcast-perception + L007 SkillCorner replay: coexistence, verbatim provenance, §9 accounting, replay equality", async () => {
    expect(clipBytes).not.toBeNull();
    // The three REAL sources (per the acceptance's example composition).
    const tracking = drainSource(
      createDeterministicLiveSource({
        sessionId: SESSION_ID,
        sourceId: "synthetic-tracking-1",
        seed: 20260921,
        scenario: "normal",
        tickCount: 30,
        playersPerTeam: 4,
      }),
    );
    const perception = await createBroadcastPerceptionClipSource({
      sessionId: SESSION_ID,
      clipBytes: clipBytes!,
      filename: "pitch-scene.mp4",
      calibration: FULL_FRAME_CALIBRATION,
      sourceId: "broadcast-perception-1",
    });
    const perceptionArrivals = collectPulls(perception);
    const skillcorner = collectPulls(
      createSkillCornerOpenDataReplay({ sessionId: SESSION_ID, jsonl: SKILLCORNER_FIXTURE_JSONL }),
    );
    expect(tracking.length).toBeGreaterThan(0);
    expect(perceptionArrivals.length).toBeGreaterThan(0);
    expect(skillcorner.length).toBeGreaterThan(0);

    const composition = driveComposition([...tracking, ...perceptionArrivals, ...skillcorner]);

    // COEXISTENCE: no cross-source co-observation (disjoint entity spaces) →
    // every batch passed VERBATIM, no conflicts, no arbitration, no withholding.
    expect(composition.fusion.stats().conflicts).toBe(0);
    expect(composition.fusion.stats().conflictRowsWithheld).toBe(0);
    expect(composition.fusion.stats().batchesApplied).toBe(
      tracking.length + perceptionArrivals.length + skillcorner.length,
    );
    // All three sources' entities live in the ONE canonical engine.
    expect(composition.engine.entityIds.length).toBeGreaterThanOrEqual(4 * 2 + 1); // L002 roster
    expect(composition.engine.entityIds.length).toBeGreaterThan(8); // + perception tracks + SkillCorner players/ball
    // PER-SOURCE PROVENANCE VERBATIM in the SWM evidence chain: the bridge
    // store carries every source's componentId, each row with its own
    // provenance kind (all DERIVED — the sources' own declarations).
    const bridged = composition.store.all();
    const componentIds = new Set(bridged.map((obs) => obs.componentId));
    expect(componentIds.has("synthetic-tracking-1")).toBe(true);
    expect(componentIds.has("broadcast-perception-1")).toBe(true);
    expect(componentIds.has(SKILLCORNER_DEFAULT_SOURCE_ID)).toBe(true);
    expect(bridged.every((obs) => obs.provenance === "DERIVED")).toBe(true);
    // The §9 multi-source accounting: per-source summaries with the L004
    // counters verbatim + the fusion counters.
    const finalReport = composition.reports[composition.reports.length - 1]!;
    expect(finalReport.sourceSummary.length).toBe(3);
    for (const summary of finalReport.sourceSummary) {
      expect(summary.batchesApplied).toBeGreaterThan(0);
      expect(summary.temporal.appliedBatches).toBe(summary.batchesApplied); // L004 counters, verbatim
      expect(summary.state).toBe("active"); // no losses in the nominal composition
    }
    // The dual-clock §9 latency fields are carried per source (the L004 surface).
    for (const summary of finalReport.sourceSummary) {
      expect(summary.temporal.meanSourceToIngestMs).not.toBeNull();
    }
    // D8: the multi-source composition replays to the identical final state.
    expectReplayEquality(composition);
  });

  test.skipIf(!hasFfmpeg)("a source that stops mid-session is recorded LOST while the survivors carry the world (honest source-loss accounting)", async () => {
    expect(clipBytes).not.toBeNull();
    const trackingFull = drainSource(
      createDeterministicLiveSource({
        sessionId: SESSION_ID,
        sourceId: "tracking-survivor",
        seed: 20260921,
        scenario: "normal",
        tickCount: 60,
        playersPerTeam: 4,
      }),
    );
    const perception = await createBroadcastPerceptionClipSource({
      sessionId: SESSION_ID,
      clipBytes: clipBytes!,
      filename: "pitch-scene.mp4",
      calibration: FULL_FRAME_CALIBRATION,
      sourceId: "broadcast-perception-1",
    });
    const perceptionArrivals = collectPulls(perception);
    // The perception stream ENDS early (a finite clip): the L002 stream
    // continues long past it; the render clock runs past the L004 stall
    // budget (3000ms) for the perception source — but NOT yet for the
    // survivor (its own last progress sits 2900ms back at the last tick).
    const composition = driveComposition([...trackingFull, ...perceptionArrivals], {
      endClockMs: trackingFull[trackingFull.length - 1]!.ingestTimeMs + 2900,
    });
    const finalReport = composition.reports[composition.reports.length - 1]!;
    const perceptionSummary = finalReport.sourceSummary.find(
      (s) => s.sourceId === "broadcast-perception-1",
    );
    // The finite clip's stream stopped: the L004 STALLED latch fired → the
    // fusion layer recorded the LOSS (events + state + fallback flag).
    expect(perceptionSummary!.state).toBe("lost");
    expect(composition.fusion.stats().sourcesLost).toBeGreaterThanOrEqual(1);
    expect(finalReport.fallbackActive).toBe(true);
    expect(
      composition.reports.some((report) =>
        report.sourceEvents.some(
          (event) => event.kind === "source-lost" && event.sourceId === "broadcast-perception-1",
        ),
      ),
    ).toBe(true);
    // The SURVIVING source carried the world (its rows kept applying).
    expect(finalReport.sourceSummary.find((s) => s.sourceId === "tracking-survivor")!.state).toBe("active");
    expect(finalReport.sourceSummary.find((s) => s.sourceId === "tracking-survivor")!.batchesApplied).toBeGreaterThan(0);
    // D8 still holds for the lossy composition.
    expectReplayEquality(composition);
  });
});

describe("L012 integration — two REAL L002 tracking sources with the SAME roster ids (genuine cross-source conflicts)", () => {
  test("conflicts are explicit, ties arbitrated by the canonical order, losers withheld, replay equality holds", () => {
    const seedA = 20260921;
    const seedB = 987654321;
    const sourceA = drainSource(
      createDeterministicLiveSource({
        sessionId: SESSION_ID,
        sourceId: "tracking-a",
        seed: seedA,
        scenario: "normal",
        tickCount: 40,
        playersPerTeam: 3,
      }),
    );
    const sourceB = drainSource(
      createDeterministicLiveSource({
        sessionId: SESSION_ID,
        sourceId: "tracking-b",
        seed: seedB,
        scenario: "normal",
        tickCount: 40,
        playersPerTeam: 3,
      }),
    );
    // Same roster ids, same tick times, materially different trajectories
    // (different seeds) — genuine same-time cross-source disagreement.
    expect(sourceA[0]!.entityObservations[0]!.entityRef).toBe(sourceB[0]!.entityObservations[0]!.entityRef);
    // sourceB's arrivals admit BEFORE sourceA's at tied ingest times (the
    // driver's stable sort keeps insertion order): B's rows drain first,
    // then A's later-arriving rows are the canonical-MIN of each tie → they
    // are WITHHELD (the withholding path — the same-path-drains-first order
    // would apply A first and let the canonical-max B overtake on top).
    const composition = driveComposition([...sourceB, ...sourceA], {
      policy: { sourcePrecedence: ["tracking-a", "tracking-b"] },
    });
    const stats = composition.fusion.stats();
    // CONFLICTS EXPLICIT: the ledger is non-empty, every record lists
    // every conflicting value with its confidence.
    expect(stats.conflicts).toBeGreaterThan(0);
    const conflictReports = composition.reports.filter((report) => report.conflicts.length > 0);
    for (const report of conflictReports) {
      for (const record of report.conflicts) {
        expect(record.observationIds.length).toBeGreaterThanOrEqual(2);
        expect(record.values.length).toBe(record.observationIds.length);
        expect(record.resolution).toBe("none");
      }
    }
    // ARBITRATION: same-time ties decided by the canonical order
    // ("tracking-b" is the canonical survivor of every a/b tie —
    // "lo-tracking-b-…" sorts after "lo-tracking-a-…"); the operator's
    // precedence preference (tracking-a) is REPORTED, never overriding.
    expect(stats.conflictRowsWithheld).toBeGreaterThan(0);
    const decisions = composition.reports.flatMap((report) => report.arbitrationDecisions);
    expect(decisions.length).toBeGreaterThan(0);
    for (const decision of decisions) {
      expect(decision.survivorSourceId).toBe("tracking-b");
      expect(decision.withheldSourceIds).toContain("tracking-a");
      expect(decision.precedencePreferredSourceId).toBe("tracking-a");
      expect(decision.precedenceMatchesSurvivor).toBe(false);
    }
    // The withheld rows never bridged: tracking-a's co-observed rows are
    // absent from the store (the arbitrated stream IS the stored stream).
    const bridged = composition.store.all();
    const aBridged = bridged.filter((obs) => obs.componentId === "tracking-a");
    const bBridged = bridged.filter((obs) => obs.componentId === "tracking-b");
    expect(aBridged.length).toBe(0); // every later-arriving canonical-min row withheld
    expect(bBridged.length).toBeGreaterThan(0);
    // D8: the conflicted multi-source composition replays to the identical state.
    expectReplayEquality(composition);
  });

  test("two AGREEING sources (the same seed, different source ids) corroborate without conflicts", () => {
    const sourceA = drainSource(
      createDeterministicLiveSource({
        sessionId: SESSION_ID,
        sourceId: "tracking-a",
        seed: 424242,
        scenario: "normal",
        tickCount: 20,
        playersPerTeam: 3,
      }),
    );
    const sourceB = drainSource(
      createDeterministicLiveSource({
        sessionId: SESSION_ID,
        sourceId: "tracking-b",
        seed: 424242, // the SAME script: identical positions (agreement)
        scenario: "jitter",
        tickCount: 20,
        playersPerTeam: 3,
      }),
    );
    // The ball speed basis is CONFIGURED to the L002 script's envelope: the
    // synthetic ball peaks at ~70 m/s (44m·1.13rad/s + 26m·1.885rad/s —
    // faster than any physical football; the DEFAULT 35 m/s basis stays the
    // physically honest value for real data). The agreement semantics are
    // what this test pins — the same script observed twice NEVER conflicts
    // under a basis that covers the script's own motion envelope.
    const composition = driveComposition([...sourceA, ...sourceB], {
      policy: { ballMaxSpeedMps: 75 },
    });
    const stats = composition.fusion.stats();
    // Agreement within tolerance: corroboration counted, no conflicts, no withholding.
    expect(stats.conflicts).toBe(0);
    expect(stats.conflictRowsWithheld).toBe(0);
    expect(stats.corroborationRows).toBeGreaterThan(0);
    expectReplayEquality(composition);
  });
});
