/**
 * The canonical Sporta benchmark fixture set (R002) — the frozen, versioned
 * manifest every candidate technology is evaluated against.
 *
 * REAL vs FIXTURE BOUNDARY (honesty contract):
 *
 * - `real-footage` entries are actual football footage downloaded from
 *   clearly-licensed sources (public domain / CC0 / CC-BY), with the source
 *   URL, upstream license, derivation note, and a sha256 integrity pin
 *   recorded per clip in the manifest below.
 * - `synthetic-diagnostic` entries are procedurally generated patterns
 *   (this repository's own work product; see
 *   `scripts/generate-synthetic-diagnostic.ts`). They are legitimate
 *   determinism/diagnostic fixtures but are NEVER real footage and are
 *   never presented as such.
 *
 * Media availability note (network blocker record): the sandbox that
 * produced this manifest had Wikimedia Commons' upload CDN
 * (upload.wikimedia.org) rate-limiting its IP (HTTP 429) during R002, so
 * the real-footage download lane was throttled. The manifest therefore
 * ships with the synthetic-diagnostic entry fully wired; real-footage
 * entries are appended by the Tech Lead's media drop (or a later retry)
 * under a NEW fixtureSetVersion — the fixture set is immutable once used
 * for evaluation, so additions version-bump rather than mutate.
 */
import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parseFixtureSet } from "./fixture-set";
import type { FixtureSet } from "./fixture-set";

/** The version of the canonical fixture set defined here. */
export const DEFAULT_FIXTURE_SET_VERSION = "fixtures-football-v1";

/** This package's `fixtures/` root (media + annotations live here). */
const FIXTURES_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "fixtures");

/** When the canonical fixture set was frozen (2025-01-06T12:00:00.000Z). */
export const DEFAULT_FIXTURE_SET_CREATED_AT_MS = 1_736_164_800_000;

/**
 * The manifest. Kept as a typed literal so the license + provenance of
 * every clip is reviewable in one place.
 */
const DEFAULT_FIXTURE_SET: FixtureSet = {
  schemaVersion: "1.1",
  fixtureSetVersion: DEFAULT_FIXTURE_SET_VERSION,
  displayName: "Sporta canonical football benchmark fixtures",
  createdAtMs: DEFAULT_FIXTURE_SET_CREATED_AT_MS,
  entries: [
    {
      schemaVersion: "1.1",
      fixtureId: "synthetic-diagnostic-01",
      mediaKind: "synthetic-diagnostic",
      mediaRef: "synthetic-diagnostic-01-players-and-ball.mp4",
      media: {
        // Procedurally generated in-repo (see derivationNote): no external
        // source, so no sourceUrl — the schema enforces this honesty rule.
        derivationNote:
          "procedurally generated by packages/technology-registry/scripts/generate-synthetic-diagnostic.ts " +
          "(deterministic pure functions of the frame index; NOT real footage)",
        sha256: "e75abe1441fe2e6680b2aad5e7d2e66a5bcd21ab4b91928e25181f90a37f7f76",
        durationSeconds: 12,
      },
      license: {
        code: {
          status: "permissive",
          // In-repo work product: no third-party rights, no external license
          // document to cite; the review reference IS the generator script.
          commercialUse: true,
          reviewRef: "packages/technology-registry/scripts/generate-synthetic-diagnostic.ts",
        },
      },
      expectedAnnotationRefs: ["annotations/synthetic-diagnostic-01.json"],
      scenarioTags: ["open-play", "ball-action"],
      notes:
        "synthetic-diagnostic: geometric top-down pitch with 10 team discs + ball on deterministic " +
        "sinusoidal paths; per-frame ground truth in the expected annotations. For determinism and " +
        "evaluation-runner smoke tests — never to be presented as real footage.",
    },
  ],
  notes:
    "Real-footage lane pending: upload.wikimedia.org rate-limited (HTTP 429) the R002 sandbox; " +
    "clearly-licensed real clips (CC0 beach-soccer penalty, PD 1897 Glentoran film, CC BY-SA 3.0 nl " +
    "1944 Dutch cup newsreel, PD 2026 USAF sports-day soccer) were identified on Wikimedia Commons " +
    "and will be appended under a new fixtureSetVersion when the media drop lands.",
};

/** Load + validate the canonical fixture set (throws on drift). */
export function loadDefaultFixtureSet(): FixtureSet {
  return parseFixtureSet(DEFAULT_FIXTURE_SET);
}

/**
 * Real-footage candidates IDENTIFIED and LICENSE-VERIFIED during R002 but
 * NOT downloadable from the R002 sandbox: upload.wikimedia.org rate-limited
 * (HTTP 429) the sandbox's rotating NAT egress IPs for the whole session,
 * and no proxy route was reachable. These entries are the Tech Lead's media
 * drop checklist — once the files land in `fixtures/media/` (derive small
 * fixtures per the derivationNote), activate them under a NEW
 * fixtureSetVersion (the set is immutable once used for evaluation).
 *
 * NOT part of the active {@link DEFAULT_FIXTURE_SET}: no media files exist
 * for them yet, and presenting unavailable media as fixtures would be
 * dishonest.
 */
export interface RealFootageCandidate {
  /** The planned fixture id once activated. */
  fixtureId: string;
  sourceUrl: string;
  /** The upstream license page (file page on Wikimedia Commons). */
  licensePageUrl: string;
  licenseId: string;
  licenseStatus: "permissive" | "copyleft";
  /** CC0/PD clips are affirmatively commercially usable; CC BY-SA is too (with attribution + share-alike). */
  commercialUse: true;
  author: string;
  /** Planned scenario coverage once the clip is derived. */
  plannedScenarioTags: Array<FixtureSet["entries"][number]["scenarioTags"][number]>;
  derivationNote: string;
}

export const REAL_FOOTAGE_CANDIDATES: readonly RealFootageCandidate[] = [
  {
    fixtureId: "beach-soccer-penalty-01",
    sourceUrl:
      "https://upload.wikimedia.org/wikipedia/commons/d/da/2021-08-29_-_FIFA_Beach_Soccer_World_Cup_-_Match_31_-_Switzerland_v_Senegal_-_No%C3%ABl_Ott_scores_a_penalty_kick.webm",
    licensePageUrl:
      "https://commons.wikimedia.org/wiki/File:2021-08-29_-_FIFA_Beach_Soccer_World_Cup_-_Match_31_-_Switzerland_v_Senegal_-_No%C3%ABl_Ott_scores_a_penalty_kick.webm",
    licenseId: "CC0-1.0",
    licenseStatus: "permissive",
    commercialUse: true,
    author: "FIFA Beach Soccer World Cup 2021 broadcast footage released under CC0",
    plannedScenarioTags: ["set-piece", "ball-action", "open-play"],
    derivationNote: "trim to the penalty sequence (~20s), keep webm or re-encode h264",
  },
  {
    fixtureId: "dutch-cup-1944-newsreel-01",
    sourceUrl:
      "https://upload.wikimedia.org/wikipedia/commons/f/fe/Wedstrijd_om_de_Nederlandse_voetbalbeker_Weeknummer_44-24_-_Open_Beelden_-_10245.ogv",
    licensePageUrl:
      "https://commons.wikimedia.org/wiki/File:Wedstrijd_om_de_Nederlandse_voetbalbeker_Weeknummer_44-24_-_Open_Beelden_-_10245.ogv",
    licenseId: "CC-BY-SA-3.0-nl",
    licenseStatus: "copyleft",
    commercialUse: true,
    author: "Nederlands Instituut voor Beeld en Geluid (Open Beelden)",
    plannedScenarioTags: ["camera-movement", "cut-boundary", "open-play"],
    derivationNote: "newsreel with cuts and camera pans; trim to a grass-football segment",
  },
  {
    fixtureId: "glentoran-1897-first-filmed-match-01",
    sourceUrl:
      "https://upload.wikimedia.org/wikipedia/commons/a/ae/The_world%E2%80%99s_first_filmed_soccer_match_with_corrected_speed-_Glentoran....webm",
    licensePageUrl:
      "https://commons.wikimedia.org/wiki/File:The_world%E2%80%99s_first_filmed_soccer_match_with_corrected_speed-_Glentoran....webm",
    licenseId: "Public domain (PD)",
    licenseStatus: "permissive",
    commercialUse: true,
    author: "ElderberryDeep8746 (1897 footage, speed-corrected)",
    plannedScenarioTags: ["open-play", "occlusion"],
    derivationNote:
      "earliest filmed soccer match; historical quality is itself an occlusion/robustness scenario",
  },
  {
    fixtureId: "incirlik-sports-day-soccer-2026-01",
    sourceUrl:
      "https://upload.wikimedia.org/wikipedia/commons/7/78/Incirlik_LTL_Sports_Day_Soccer_Game_%281008728%29.webm",
    licensePageUrl:
      "https://commons.wikimedia.org/wiki/File:Incirlik_LTL_Sports_Day_Soccer_Game_(1008728).webm",
    licenseId: "Public domain (PD, US Air Force / DVIDS)",
    licenseStatus: "permissive",
    commercialUse: true,
    author: "Senior Airman Collin Wesson (DVIDS)",
    plannedScenarioTags: ["open-play", "ball-action", "camera-movement"],
    derivationNote: "wide-angle recreational soccer, USAF footage; trim to continuous-play segment",
  },
];

/**
 * Verify the manifest's on-disk media: every referenced file must exist and
 * (when pinned) match its sha256. Returns the list of issues (empty =
 * verified). Pure check — never throws, never mutates.
 */
export function verifyDefaultFixtureSetMedia(): string[] {
  const issues: string[] = [];
  const set = loadDefaultFixtureSet();
  for (const entry of set.entries) {
    const path = join(FIXTURES_ROOT, "media", entry.mediaRef);
    if (!existsSync(path)) {
      issues.push(
        `fixture '${entry.fixtureId}': media file missing at fixtures/media/${entry.mediaRef}`,
      );
      continue;
    }
    if (entry.media.sha256 !== undefined) {
      const actual = createHash("sha256").update(readFileSync(path)).digest("hex");
      if (actual !== entry.media.sha256) {
        issues.push(
          `fixture '${entry.fixtureId}': sha256 mismatch (expected ${entry.media.sha256}, got ${actual})`,
        );
      }
    }
    for (const annotationRef of entry.expectedAnnotationRefs) {
      const annotationPath = join(FIXTURES_ROOT, annotationRef);
      if (!existsSync(annotationPath)) {
        issues.push(
          `fixture '${entry.fixtureId}': expected annotation missing at fixtures/${annotationRef}`,
        );
      }
    }
  }
  return issues;
}
