/**
 * The deny/degraded fixture battery (W901): every fixture under `fixtures/v1`
 * must VALIDATE against the response schema AND its semantic invariants must
 * hold — the acceptance gate "contract fixtures cover every deny/degraded
 * path" made executable. Fixtures are regenerated by
 * `bun run regen-fixtures` (deterministic; Prettier-formatted with a
 * losslessness proof, the regen-golden precedent).
 */
import { describe, expect, test } from "bun:test";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import {
  CapabilityResponseSchema,
  buildCapabilityResponse,
  parseCapabilityResponse,
  serializeCapabilityResponse,
} from "../src/index";
import type { CapabilityResponse } from "../src/index";
import { FIXTURE_SCENARIOS } from "../scripts/scenarios";

const FIXTURE_DIR = join(import.meta.dir, "..", "fixtures", "v1");

/** The canonical eight (the brief's deny/degraded coverage list). */
const EXPECTED_FIXTURES = [
  "anonymous.json",
  "authenticated-no-roles.json",
  "live-unavailable.json",
  "partial-availability.json",
  "provider-degraded.json",
  "provider-down.json",
  "quota-exhausted.json",
  "rights-denied-renderer.json",
] as const;

function fixture(name: string): CapabilityResponse {
  return parseCapabilityResponse(readFileSync(join(FIXTURE_DIR, name), "utf8"));
}

function renderer(
  response: CapabilityResponse,
  id: string,
): CapabilityResponse["renderers"][number] {
  const entry = response.renderers.find((renderer) => renderer.rendererId === id);
  if (entry === undefined) throw new Error(`fixture has no renderer ${id}`);
  return entry;
}

function surface(
  response: CapabilityResponse,
  id: CapabilityResponse["content"]["catalogSurfaces"][number]["surfaceId"],
): CapabilityResponse["content"]["catalogSurfaces"][number] {
  const entry = response.content.catalogSurfaces.find((s) => s.surfaceId === id);
  if (entry === undefined) throw new Error(`fixture has no surface ${id}`);
  return entry;
}

describe("fixture inventory", () => {
  test("every deny/degraded fixture is present, and no others", () => {
    const files = readdirSync(FIXTURE_DIR)
      .filter((file) => file.endsWith(".json"))
      .sort();
    expect(files).toEqual([...EXPECTED_FIXTURES].sort());
  });

  test("the fixture files and the shared scenarios are the same eight", () => {
    const expected: string[] = [...EXPECTED_FIXTURES];
    expect(expected.sort()).toEqual(
      Object.keys(FIXTURE_SCENARIOS)
        .map((name) => `${name}.json`)
        .sort(),
    );
  });

  test("every fixture validates; its canonical re-serialization is stable", () => {
    for (const name of EXPECTED_FIXTURES) {
      const text = readFileSync(join(FIXTURE_DIR, name), "utf8");
      const parsed = parseCapabilityResponse(text);
      const result = CapabilityResponseSchema.safeParse(parsed);
      expect(result.success, `${name} must validate`).toBe(true);
      // The file is Prettier-formatted (whitespace only — the regen script
      // proves losslessness at write time); the parsed document must still
      // re-serialize to canonical bytes that re-parse to the SAME canonical
      // bytes (idempotent round-trip, no formatting-induced drift).
      const canonical = serializeCapabilityResponse(parsed);
      expect(
        serializeCapabilityResponse(parseCapabilityResponse(canonical)),
        `${name} must re-serialize stably`,
      ).toBe(canonical);
    }
  });

  test("every fixture is exactly as fresh as a live build (no hand drift)", () => {
    for (const name of EXPECTED_FIXTURES) {
      const scenario = FIXTURE_SCENARIOS[name.replace(/\.json$/, "")]!;
      const fromFile = serializeCapabilityResponse(
        parseCapabilityResponse(readFileSync(join(FIXTURE_DIR, name), "utf8")),
      );
      const live = serializeCapabilityResponse(buildCapabilityResponse(scenario));
      expect(live, `${name} must equal a fresh build of its scenario`).toBe(fromFile);
    }
  });
});

describe("anonymous", () => {
  const response = fixture("anonymous.json");

  test("auth state is anonymous with no account identity", () => {
    expect(response.auth.state).toBe("anonymous");
    expect(response.auth.sessionValid).toBe(false);
    expect(response.auth.activeRole).toBeNull();
    expect(response.account.authenticated).toBe(false);
    expect(response.account.userId).toBeUndefined();
    expect(response.account.roles).toEqual([]);
  });

  test("public surfaces are visible and role surfaces are authentication-required", () => {
    expect(surface(response, "home").visibility).toBe("visible");
    expect(surface(response, "watch").visibility).toBe("visible");
    expect(surface(response, "create-studio")).toEqual({
      surfaceId: "create-studio",
      visibility: "hidden",
      reasonCode: "authentication-required",
    });
    expect(surface(response, "operations")).toEqual({
      surfaceId: "operations",
      visibility: "hidden",
      reasonCode: "authentication-required",
    });
  });

  test("in-process transport is never live network (Simulation F)", () => {
    expect(response.modes.live.transportKind).toBe("in-process");
    expect(response.modes.live.availability).toBe("unavailable");
    expect(response.modes.live.reasonCode).toBe("in-process-transport-not-live");
  });

  test("a healthy anonymous world is overall ready (live gaps are not app-wide)", () => {
    expect(response.overall.state).toBe("ready");
  });
});

describe("authenticated-no-roles", () => {
  const response = fixture("authenticated-no-roles.json");

  test("authenticated with zero grants", () => {
    expect(response.auth.state).toBe("authenticated");
    expect(response.auth.activeRole).toBeNull();
    expect(response.account.userId).toBe("u-42");
    expect(response.account.roles).toEqual([]);
  });

  test("public surfaces visible; grant-gated surfaces are role-not-granted", () => {
    expect(surface(response, "home").reasonCode).toBe("surface-visible");
    expect(surface(response, "library").reasonCode).toBe("role-not-granted");
    expect(surface(response, "rights-center").reasonCode).toBe("role-not-granted");
    expect(surface(response, "jobs").reasonCode).toBe("role-not-granted");
  });
});

describe("rights-denied renderer", () => {
  const response = fixture("rights-denied-renderer.json");

  test("a rights-denied renderer is NEVER available", () => {
    const entry = renderer(response, "broadcast-enhanced.prototype");
    expect(entry.availability).not.toBe("available");
    expect(entry.availability).toBe("unavailable");
    expect(entry.reasonCode).toBe("rights-denied");
    expect(entry.requiresSourceFrames).toBe(true);
    expect(entry.rightsAwareness).toBe("rights-evaluated");
  });

  test("pure-SWM renderers remain available under the same policy", () => {
    expect(renderer(response, "sporta.testcard").availability).toBe("available");
    expect(renderer(response, "anime.prototype").availability).toBe("available");
  });

  test("live is unavailable under this policy (in-process transport, and no liveDelivery right)", () => {
    expect(response.modes.live.availability).toBe("unavailable");
    expect(response.modes.live.transportKind).toBe("in-process");
    expect(response.modes.live.reasonCode).toBe("in-process-transport-not-live");
  });

  test("overall is degraded with the renderer and live codes", () => {
    expect(response.overall.state).toBe("degraded");
    expect(response.overall.reasonCodes).toContain("rights-denied");
  });
});

describe("quota-exhausted", () => {
  const response = fixture("quota-exhausted.json");

  test("at-limit and over-limit counters are exhausted with zero remaining", () => {
    const daily = response.quotas.find((quota) => quota.quotaId === "user.daily-renders")!;
    expect(daily.exhausted).toBe(true);
    expect(daily.remaining).toBe(0);
    expect(daily.reasonCode).toBe("quota-exhausted");
    const concurrent = response.quotas.find((quota) => quota.quotaId === "job.concurrent-renders")!;
    expect(concurrent.exhausted).toBe(true);
    expect(concurrent.remaining).toBe(0);
    expect(concurrent.used).toBe(3);
    expect(concurrent.limit).toBe(2);
  });

  test("overall is degraded with quota-exhausted (Simulation E: stop admitting)", () => {
    expect(response.overall.state).toBe("degraded");
    expect(response.overall.reasonCodes).toContain("quota-exhausted");
  });

  test("renderers stay available (degraded, not unavailable — existing work stands)", () => {
    expect(renderer(response, "sporta.testcard").availability).toBe("available");
  });
});

describe("provider-down", () => {
  const response = fixture("provider-down.json");

  test("the down provider carries its reason code and detail", () => {
    const compute = response.providers.find((provider) => provider.kind === "compute")!;
    expect(compute.health).toBe("down");
    expect(compute.reasonCode).toBe("feed-reported-down");
    expect(compute.detail).toBe("compute adapter reports provider unreachable");
  });

  test("renderers depending on the down provider are unavailable with provider-down", () => {
    for (const id of ["sporta.testcard", "anime.prototype", "avatar-field.prototype"]) {
      const entry = renderer(response, id);
      expect(entry.availability, id).toBe("unavailable");
      expect(entry.reasonCode, id).toBe("provider-down");
    }
  });

  test("batch mode is unavailable (compute is down)", () => {
    expect(response.modes.batch.availability).toBe("unavailable");
    expect(response.modes.batch.reasonCode).toBe("provider-down");
  });

  test("overall is unavailable (nothing renderable)", () => {
    expect(response.overall.state).toBe("unavailable");
    expect(response.overall.reasonCodes).toContain("provider-down");
  });
});

describe("provider-degraded", () => {
  const response = fixture("provider-degraded.json");

  test("the degraded provider carries its degraded meaning for the user", () => {
    const storage = response.providers.find((provider) => provider.kind === "storage")!;
    expect(storage.health).toBe("degraded");
    expect(storage.reasonCode).toBe("feed-reported-degraded");
    expect(storage.degradedMeaning).toContain("playback is unaffected");
  });

  test("renderers not depending on storage stay available", () => {
    expect(renderer(response, "sporta.testcard").availability).toBe("available");
  });

  test("overall is degraded with provider-degraded", () => {
    expect(response.overall.state).toBe("degraded");
    expect(response.overall.reasonCodes).toContain("provider-degraded");
  });
});

describe("live-unavailable", () => {
  const response = fixture("live-unavailable.json");

  test("the in-process transport is NEVER reported as live network (Simulation F)", () => {
    expect(response.modes.live.transportKind).toBe("in-process");
    expect(response.modes.live.availability).toBe("unavailable");
    expect(response.modes.live.reasonCode).toBe("in-process-transport-not-live");
    expect(response.modes.live.transportKind === "live-network").toBe(false);
  });

  test("batch stays available (offline rendering is unaffected)", () => {
    expect(response.modes.batch.availability).toBe("available");
    expect(response.modes.batch.reasonCode).toBe("ok");
  });

  test("a live gap alone does not degrade the overall app state", () => {
    expect(response.overall.state).toBe("ready");
  });
});

describe("partial availability", () => {
  const response = fixture("partial-availability.json");

  test("each renderer carries its own state", () => {
    expect(renderer(response, "sporta.testcard")).toMatchObject({
      availability: "available",
      reasonCode: "ok",
    });
    expect(renderer(response, "broadcast-enhanced.prototype")).toMatchObject({
      availability: "unavailable",
      reasonCode: "renderer-not-registered",
    });
    expect(renderer(response, "avatar-field.prototype")).toMatchObject({
      availability: "degraded",
      reasonCode: "renderer-registry-degraded",
    });
  });

  test("overall is degraded (not unavailable — something is renderable)", () => {
    expect(response.overall.state).toBe("degraded");
    expect(response.overall.reasonCodes).toContain("renderer-not-registered");
    expect(response.overall.reasonCodes).toContain("renderer-registry-degraded");
  });

  test("live-transport none is live-transport-not-configured", () => {
    expect(response.modes.live.transportKind).toBe("none");
    expect(response.modes.live.reasonCode).toBe("live-transport-not-configured");
  });
});

describe("cross-fixture semantic invariants", () => {
  test("no fixture ever claims live-network without live availability, or vice versa", () => {
    for (const name of EXPECTED_FIXTURES) {
      const response = fixture(name);
      const { live } = response.modes;
      if (live.availability === "available") {
        expect(live.transportKind, name).toBe("live-network");
      } else {
        expect(live.reasonCode, name).not.toBe("ok");
      }
    }
  });

  test("no fixture marks a rights-denied renderer available", () => {
    for (const name of EXPECTED_FIXTURES) {
      const response = fixture(name);
      for (const entry of response.renderers) {
        if (entry.reasonCode === "rights-denied") {
          expect(entry.availability, name).not.toBe("available");
        }
      }
    }
  });

  test("every fixture carries the pinned notes and all four provider kinds", () => {
    for (const name of EXPECTED_FIXTURES) {
      const response = fixture(name);
      expect(response.auth.activeRoleContextNote.length, name).toBeGreaterThan(40);
      expect(response.account.rolesAreGrantsNote.length, name).toBeGreaterThan(40);
      expect(response.providers.map((provider) => provider.kind).sort()).toEqual([
        "compute",
        "control-plane",
        "queue-cache",
        "storage",
      ]);
    }
  });
});
