/**
 * The W804 real-seam integration test: a stream generated by the REAL W706
 * emitter (`createViewerTelemetry` over the real in-memory sink, driven the
 * way `viewer-core.ts` drives it — `setSessionId` BEFORE the establishing
 * transition, timings on the success landings, errors from the typed error
 * model) is consumed by `computeProductAnalytics` verbatim. This pins that
 * the analytics input boundary accepts EXACTLY what W706 produces — no
 * drift between the emitter's vocabulary and the analytics consumer.
 */
import { describe, expect, test } from "bun:test";
import {
  REMEDIATION_HINTS,
  createInMemoryTelemetrySink,
  createViewerTelemetry,
  toErrorView,
} from "@sporta/viewer-shell";
import type { InMemoryTelemetrySink } from "@sporta/viewer-shell";
import { TEST_EPOCH_MS } from "@sporta/testing";
import { computeProductAnalytics } from "../src/report.ts";

/** The real injected-clock convention: an explicit epoch, advanced explicitly. */
function deterministicClock(): () => number {
  let now = TEST_EPOCH_MS;
  return () => {
    now += 7;
    return now;
  };
}

describe("the REAL W706 emitter feeds the analytics computation", () => {
  test("every emitter output is a valid W706 event the analytics gate accepts", () => {
    const sink = createInMemoryTelemetrySink();
    const telemetry = createViewerTelemetry({ sink, nowMs: deterministicClock() });
    // The viewer-core sequence for a failed beginRender (id stamped before
    // the establishing transition — the emitter's documented convention):
    telemetry.stateTransition("disconnected", "connecting");
    telemetry.operationTiming("connect", 90);
    telemetry.stateTransition("connecting", "browsing-sessions");
    telemetry.setSessionId("sess-1");
    telemetry.stateTransition("browsing-sessions", "session-detail");
    telemetry.errorOccurred(toErrorView("beginRender", "resource-limit", "gpu at capacity"));
    telemetry.stateTransition("session-detail", "error");

    expect(sink.events).toHaveLength(6);
    expect(telemetry.status()).toEqual({ emitted: 6, dropped: 0, dropReason: null });
    const report = computeProductAnalytics(sink.events); // re-validates every event
    expect(report.accounting).toEqual({
      eventsIn: 6,
      classified: 6,
      unclassifiable: [],
      sequenceAnomalies: 0,
      sessionsObserved: 1,
      partialSessions: 0,
    });
    expect(
      report.failures.sessionOutcomes.find(
        (row) => row.outcome === "error-terminal" && row.failureClass === "resource-limit",
      )!.count,
    ).toBe(1);
  });

  test("a full happy-path run through the real emitter produces the expected report", () => {
    const sink = createInMemoryTelemetrySink();
    let now = TEST_EPOCH_MS;
    const telemetry = createViewerTelemetry({ sink, nowMs: () => now });

    telemetry.stateTransition("disconnected", "connecting"); // connect begin
    now += 90;
    telemetry.operationTiming("connect", 90); // connect success
    telemetry.stateTransition("connecting", "browsing-sessions");
    telemetry.setSessionId("sess-1"); // openSession onSuccess stamps BEFORE…
    telemetry.stateTransition("browsing-sessions", "session-detail"); // …the establishing transition
    // beginRender fails once (the typed error model, verbatim):
    telemetry.errorOccurred(toErrorView("beginRender", "resource-limit", "at capacity"));
    telemetry.stateTransition("session-detail", "error");
    // retry succeeds → selection → createRender → load (integrity + timing) → play:
    telemetry.stateTransition("error", "session-detail");
    telemetry.stateTransition("session-detail", "renderer-selection");
    telemetry.stateTransition("renderer-selection", "session-detail"); // createRender begin
    telemetry.stateTransition("session-detail", "render-queued");
    telemetry.stateTransition("render-queued", "loading-output");
    now += 240;
    telemetry.integrityVerified({ byteLength: 4096, frameCount: 6 });
    telemetry.operationTiming("load-output", 240);
    telemetry.stateTransition("loading-output", "ready");
    telemetry.stateTransition("ready", "playing");
    telemetry.rebufferStall({ frameIndex: 4, frameCount: 6, availableFrames: 4 });
    telemetry.userFeedback("playback-stalled");
    telemetry.stateTransition("playing", "ended");

    const report = computeProductAnalytics(sink.events);
    expect(report.accounting).toEqual({
      eventsIn: 18,
      classified: 18,
      unclassifiable: [],
      sequenceAnomalies: 0,
      sessionsObserved: 1,
      partialSessions: 0,
    });
    expect(report.connection).toEqual({
      attempts: 1,
      successes: 1,
      failures: 0,
      timing: { count: 1, minMs: 90, maxMs: 90, meanMs: 90, p50Ms: 90, p95Ms: 90 },
    });
    expect(report.timings["load-output"]!.p50Ms).toBe(240);
    // The recovered failure is carried verbatim in the histogram:
    const bucket = report.failures.byClass.find((b) => b.failureClass === "resource-limit")!;
    expect(bucket.events).toBe(1);
    expect(bucket.byOperation.beginRender).toBe(1);
    expect(bucket.sessionScoped).toBe(1);
    expect(report.playbackHealth.rebufferStalls.frameDeficit).toEqual({ total: 2, max: 2 });
    expect(report.feedback).toEqual({
      "playback-good": 0,
      "playback-stalled": 1,
      "playback-poor": 0,
    });
    // The cohort PLAYED: playback-started (the earlier, recovered error does
    // not outrank a reached goal):
    expect(
      report.failures.sessionOutcomes.find((row) => row.outcome === "playback-started")!.count,
    ).toBe(1);
  });

  test("the real emitter's error events carry the verbatim remediation hint from the W706 table", () => {
    const sink = createInMemoryTelemetrySink();
    const telemetry = createViewerTelemetry({ sink, nowMs: deterministicClock() });
    telemetry.errorOccurred(toErrorView("openLive", "rights-denied", "no canDeliverLive"));
    const event = sink.events[0]!;
    expect(event.kind).toBe("error-occurred");
    if (event.kind === "error-occurred") {
      expect(event.failureClass).toBe("rights-denied");
      expect(event.remediationHint).toBe(REMEDIATION_HINTS["rights-denied"]);
    }
    const report = computeProductAnalytics(sink.events);
    const denied = report.failures.byClass.find((b) => b.failureClass === "rights-denied")!;
    expect(denied.remediationHint).toBe(REMEDIATION_HINTS["rights-denied"]);
    expect(denied.viewerScoped).toBe(1); // no session open: viewer-scoped by construction
  });

  test("the sink's recorded events deep-equal a second recording (emitter determinism feeding analytics)", () => {
    function run(): InMemoryTelemetrySink {
      const sink = createInMemoryTelemetrySink();
      const telemetry = createViewerTelemetry({ sink, nowMs: deterministicClock() });
      telemetry.setSessionId("sess-1");
      telemetry.stateTransition("browsing-sessions", "session-detail");
      telemetry.userFeedback("playback-good");
      return sink;
    }
    expect(run().events).toEqual(run().events);
    expect(computeProductAnalytics(run().events)).toEqual(computeProductAnalytics(run().events));
  });
});
