/**
 * THE derived-reality artifact catalog + playback tests (R508-R510) — the
 * per-reality CATALOG-DESCRIPTOR battery: a REAL ffmpeg-generated MP4
 * upload becomes the session, a REAL derived-reality render dispatch (per
 * reality) walks the honest job states to terminal success, and:
 *
 * - the catalog's derived-reality descriptors become REAL MP4 video
 *   descriptors (mp4-container content types, the frozen manifest's own
 *   integrity hash, honest availability) — the ADDITIVE catalog: the
 *   original reality's descriptors and the anime prototype's W504 SVG
 *   review segments (the diagnostics surface) stay exactly as they were;
 * - the watch byte route serves the derived MP4s through the SAME
 *   verified-read + Range path as the original reality (200 full object
 *   whose sha-256 EQUALS the descriptor's integrity hash, 206 partial);
 * - the honest not-video boundary: a W504 animated-SVG review segment
 *   still answers the typed 415 (never presented as video);
 * - the same-event integrity: every reality's frozen manifest references
 *   the SAME canonical session + SWM provenance.
 *
 * REAL vs FIXTURE BOUNDARY: the uploaded clip is generated by the REAL
 * ffmpeg in-test (generateTestMp4 — never a committed fixture); every
 * derived MP4 is encoded in-test by the REAL system ffmpeg through the
 * REAL renderers + the R306 bridges.
 */
import { beforeAll, afterAll, describe, expect, test } from "bun:test";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createDeterministicTestHasher } from "@sporta/identity";
import { generateTestMp4, LocalFilesystemStorage, sha256OfBytes } from "@sporta/media-platform";
import { RenderArtifactManifest } from "@sporta/contracts";
import { createSportaServer, installSportaServerForTests } from "../src/server/composition";
import type { SportaServer } from "../src/server/composition";
import { SPORTA_SESSION_COOKIE } from "../src/server/auth-service";
import { InMemoryRedis } from "../src/server/platform/upstash/redis";
import { POST as registerRoute } from "../src/app/api/auth/register/route";
import { POST as uploadSessionRoute } from "../src/app/api/create/upload-sessions/route";
import { POST as renderRoute } from "../src/app/api/create/sessions/[sessionId]/renders/route";
import { GET as jobRoute } from "../src/app/api/create/sessions/[sessionId]/jobs/[jobId]/route";
import { GET as mediaJobRoute } from "../src/app/api/media/jobs/[jobId]/route";
import { GET as artifactCatalogRoute } from "../src/app/api/catalog/sessions/[sessionId]/artifacts/route";
import { GET as videoRoute } from "../src/app/api/watch/[sessionId]/realities/[kind]/artifacts/[artifactId]/content/route";
import { buildWatchArtifactCatalog } from "../src/server/catalog-service";
import { videoDescriptorOf } from "../src/lib/reality-catalog";
import { videoSourceOf } from "../src/lib/reality-catalog";

/** A deterministic stepping clock (the repo's hermetic rig). */
function steppingClock(): () => number {
  let current = 1_888_888_888_000;
  return () => {
    current += 17;
    return current;
  };
}

function withCookie(token: string | null, path: string, init: RequestInit = {}): Request {
  return new Request(`http://sporta.test${path}`, {
    ...init,
    headers: {
      ...((init.headers as Record<string, string> | undefined) ?? {}),
      ...(token === null ? {} : { cookie: `${SPORTA_SESSION_COOKIE}=${token}` }),
    },
  });
}

async function bodyOf(response: Response): Promise<Record<string, unknown>> {
  return (await response.json()) as Record<string, unknown>;
}

function jsonPost(payload: unknown): RequestInit {
  return {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(payload),
  };
}

let server: SportaServer;
let scratch = "";
let token = "";
let sessionId = "";

/** Dispatches ONE real render and polls the job to terminal success. */
async function dispatchAndAwait(
  rendererId: string,
  styleId: string,
): Promise<{ renderId: string; outputs: { artifactId: string; contentType: string }[] }> {
  const dispatch = await renderRoute(
    withCookie(token, `/api/create/sessions/${sessionId}/renders`, jsonPost({ rendererId, styleId })),
    { params: Promise.resolve({ sessionId }) },
  );
  expect(dispatch.status).toBe(202);
  const dispatchBody = (await bodyOf(dispatch)) as { jobId: string };
  let terminal: { renderId: string; outputs: { artifactId: string; contentType: string }[] } | null =
    null;
  for (let attempt = 0; attempt < 400; attempt += 1) {
    const response = await jobRoute(
      withCookie(token, `/api/create/sessions/${sessionId}/jobs/${dispatchBody.jobId}`),
      { params: Promise.resolve({ sessionId, jobId: dispatchBody.jobId }) },
    );
    expect(response.status).toBe(200);
    const job = (await bodyOf(response)) as {
      state: string;
      completion?: {
        status: string;
        renderId: string;
        outputs: { artifactId: string; contentType: string }[];
      };
    };
    if (job.completion !== undefined) {
      expect(job.completion.status).toBe("succeeded");
      terminal = {
        renderId: job.completion.renderId,
        outputs: job.completion.outputs,
      };
      break;
    }
    await Bun.sleep(25);
  }
  expect(terminal).not.toBeNull();
  return terminal!;
}

beforeAll(async () => {
  scratch = await mkdtemp(join(tmpdir(), "sporta-derived-catalog-"));
  server = createSportaServer({
    nowMs: steppingClock(),
    passwordHasher: createDeterministicTestHasher(),
    transient: { redis: new InMemoryRedis(steppingClock()), provider: "in-memory" },
    seed: true,
    media: {
      db: ":memory:",
      storage: new LocalFilesystemStorage(join(scratch, "media-storage")),
    },
  });
  installSportaServerForTests(server);
  await server.ready;

  const registered = await server.auth.register({
    username: "derived-catalog-creator",
    password: "a-real-derived-password",
    roles: ["creator", "viewer"],
  });
  token = (await server.auth.issueSession({ userId: registered.userId })).token;

  // THE REAL UPLOAD: ffmpeg generates the clip; the real pipeline
  // normalizes it and stores the original-reality artifact.
  const clipPath = await generateTestMp4(join(scratch, "clip.mp4"), {
    durationSeconds: 2,
    withAudio: true,
  });
  const bytes = new Uint8Array(await Bun.file(clipPath).arrayBuffer());
  const form = new FormData();
  form.append(
    "file",
    new File([bytes.slice().buffer as ArrayBuffer], "clip.mp4", { type: "video/mp4" }),
  );
  form.append(
    "operations",
    JSON.stringify(["analysis", "transformation", "derivativeGeneration", "storage"]),
  );
  form.append("label", "The derived-reality catalog clip");
  const upload = await uploadSessionRoute(
    withCookie(token, "/api/create/upload-sessions", { method: "POST", body: form }),
  );
  expect(upload.status).toBe(201);
  const uploadBody = (await bodyOf(upload)) as {
    sessionId: string;
    source: { job: { jobId: string } | null };
  };
  sessionId = uploadBody.sessionId;
  expect(uploadBody.source.job).not.toBeNull();
  // The media job settles (the original reality's artifact exists).
  let mediaTerminal = false;
  for (let attempt = 0; attempt < 400; attempt += 1) {
    const response = await mediaJobRoute(
      withCookie(token, `/api/media/jobs/${uploadBody.source.job!.jobId}`),
      { params: Promise.resolve({ jobId: uploadBody.source.job!.jobId }) },
    );
    const job = (await bodyOf(response)) as { terminal: boolean; state: string };
    if (job.terminal) {
      expect(job.state).toBe("succeeded");
      mediaTerminal = true;
      break;
    }
    await Bun.sleep(25);
  }
  expect(mediaTerminal).toBe(true);
});

afterAll(async () => {
  await rm(scratch, { recursive: true, force: true });
});

describe("the derived-reality artifact catalog + playback (R508-R510)", () => {
  test("R508 — the tactical reality's descriptor is a REAL MP4 with the manifest's integrity hash", async () => {
    const settled = await dispatchAndAwait("tactical.prototype", "derived-catalog-tactical");
    expect(settled.outputs.length).toBeGreaterThan(0);
    expect(settled.outputs[0]!.contentType).toBe("video/mp4+base64");

    const catalog = await buildWatchArtifactCatalog(server, sessionId);
    expect(catalog.playback.state).toBe("authorized");
    const tactical = catalog.realities!.find((entry) => entry.kind === "tactical")!;
    expect(tactical.availability).toBe("ready");
    expect(tactical.artifacts.length).toBeGreaterThan(0);
    // The PRIMARY descriptor: the media platform's real MP4 artifact.
    const descriptor = tactical.artifacts[0]!;
    expect(descriptor.contentType).toBe("mp4/avc1.42E01E");
    expect(descriptor.artifactId).toMatch(/^tactical-/);
    expect(descriptor.integrityHash).toMatch(/^[0-9a-f]{64}$/);
    expect(descriptor.byteSize).toBeGreaterThan(1024);
    expect(descriptor.producerId).toBe("tactical.prototype");
    // The video source resolution picks it (the player's own model).
    expect(videoDescriptorOf(tactical)).not.toBeNull();
    // The frozen manifest behind the descriptor (the store's own record).
    const frozen = RenderArtifactManifest.parse(server.media.artifact(descriptor.artifactId));
    expect(frozen.reality).toBe("tactical");
    expect(frozen.contentHash).toBe(descriptor.integrityHash);
    expect(frozen.byteSize).toBe(descriptor.byteSize);
    expect(frozen.swm).not.toBeNull();
  });

  test("R508 — the watch byte route serves the tactical MP4, integrity-verified, with Range support", async () => {
    const catalog = await buildWatchArtifactCatalog(server, sessionId);
    const tactical = catalog.realities!.find((entry) => entry.kind === "tactical")!;
    const descriptor = videoDescriptorOf(tactical)!;
    expect(descriptor).not.toBeNull();

    const full = await videoRoute(
      withCookie(token, videoSourceOf(sessionId, "tactical", descriptor.artifactId)),
      {
        params: Promise.resolve({
          sessionId,
          kind: "tactical",
          artifactId: descriptor.artifactId,
        }),
      },
    );
    expect(full.status).toBe(200);
    expect(full.headers.get("content-type")).toBe("video/mp4");
    expect(full.headers.get("accept-ranges")).toBe("bytes");
    expect(full.headers.get("x-sporta-integrity-verified")).toBe("sha256");
    const bytes = new Uint8Array(await full.arrayBuffer());
    expect(bytes.byteLength).toBe(descriptor.byteSize);
    // THE INTEGRITY EVIDENCE: the served bytes' sha-256 EQUALS the catalog
    // descriptor's integrityHash (the store re-verifies per request).
    expect(sha256OfBytes(bytes)).toBe(descriptor.integrityHash);
    // Real raster video: the MP4 container magic.
    expect(Buffer.from(bytes.subarray(4, 8)).toString("ascii")).toBe("ftyp");

    // The browser's Range fetch (exactly what <video> issues on seek).
    const range = await videoRoute(
      withCookie(token, videoSourceOf(sessionId, "tactical", descriptor.artifactId), {
        headers: { range: "bytes=0-1023" },
      }),
      {
        params: Promise.resolve({
          sessionId,
          kind: "tactical",
          artifactId: descriptor.artifactId,
        }),
      },
    );
    expect(range.status).toBe(206);
    expect(range.headers.get("content-range")).toBe(`bytes 0-1023/${descriptor.byteSize}`);
    const slice = new Uint8Array(await range.arrayBuffer());
    expect(slice.byteLength).toBe(1024);
    expect(Array.from(slice)).toEqual(Array.from(bytes.slice(0, 1024)));
  });

  test("R508 — the additive catalog: the original reality and the SVG diagnostics stay unchanged", async () => {
    // An anime.prototype render stages the W504 SVG review segment (the
    // DIAGNOSTICS surface of the anime-npr reality).
    const settled = await dispatchAndAwait("anime.prototype", "derived-catalog-anime");
    expect(settled.outputs[0]!.contentType).toBe("image/svg+xml");

    const response = await artifactCatalogRoute(
      withCookie(token, `/api/catalog/sessions/${sessionId}/artifacts`),
      { params: Promise.resolve({ sessionId }) },
    );
    expect(response.status).toBe(200);
    const body = (await bodyOf(response)) as {
      playback: { state: string };
      readyRealityCount: number;
      realities: {
        kind: string;
        availability: string;
        artifacts: {
          artifactId: string;
          contentType: string;
          integrityHash: string;
          producerId: string;
        }[];
      }[];
    };
    expect(body.playback.state).toBe("authorized");
    // The four realities in the frozen order; the tactical + anime-npr +
    // original realities hold real artifacts now.
    expect(body.realities.map((entry) => entry.kind)).toEqual([
      "original",
      "tactical",
      "three-d-game",
      "anime-npr",
    ]);
    const original = body.realities.find((entry) => entry.kind === "original")!;
    expect(original.availability).toBe("ready");
    expect(original.artifacts[0]!.contentType).toContain("mp4");
    expect(original.artifacts[0]!.producerId).not.toBe("tactical.prototype");
    // The tactical reality: still ready, still the MP4 descriptor.
    const tactical = body.realities.find((entry) => entry.kind === "tactical")!;
    expect(tactical.availability).toBe("ready");
    expect(tactical.artifacts[0]!.contentType).toBe("mp4/avc1.42E01E");
    // The 3D reality: producer registered, no render yet — honest.
    const threeD = body.realities.find((entry) => entry.kind === "three-d-game")!;
    expect(threeD.availability).toBe("requires-render");
    expect(threeD.artifacts).toHaveLength(0);
    // The anime-npr reality: the W504 SVG review segment (diagnostics) —
    // the honest not-video boundary still applies to it.
    const anime = body.realities.find((entry) => entry.kind === "anime-npr")!;
    expect(anime.availability).toBe("ready");
    expect(anime.artifacts.length).toBeGreaterThan(0);
    expect(anime.artifacts[0]!.contentType).toBe("image/svg+xml");

    // The 415: the SVG review segment is never presented as video.
    const notVideo = await videoRoute(
      withCookie(
        token,
        videoSourceOf(sessionId, "anime-npr", anime.artifacts[0]!.artifactId),
      ),
      {
        params: Promise.resolve({
          sessionId,
          kind: "anime-npr",
          artifactId: anime.artifacts[0]!.artifactId,
        }),
      },
    );
    expect(notVideo.status).toBe(415);
    const errorBody = (await bodyOf(notVideo)) as { error: { failureClass: string } };
    expect(errorBody.error.failureClass).toBe("media-invalid");
  });

  test("R508 same-event integrity — the tactical MP4's SWM provenance matches the session's canonical world model", async () => {
    const catalog = await buildWatchArtifactCatalog(server, sessionId);
    const tactical = catalog.realities!.find((entry) => entry.kind === "tactical")!;
    const descriptor = tactical.artifacts[0]!;
    const frozen = RenderArtifactManifest.parse(server.media.artifact(descriptor.artifactId));
    // The session's OWN world model (the canonical truth every reality reads).
    const engine = server.engines.get(sessionId)!;
    const snapshot = engine.snapshot();
    const events = engine.eventsSince(snapshot.watermark.sequence);
    // The frozen manifest references the SAME canonical session and the SWM
    // provenance within the world model's own accounting (the render READ
    // the world model — the session id is the constant).
    expect(frozen.sessionId).toBe(sessionId);
    expect(frozen.swm!.snapshotVersion).toBeLessThanOrEqual(engine.snapshotVersion);
    const lastSequence = events.at(-1)?.sequence ?? snapshot.watermark.sequence;
    expect(frozen.swm!.lastEventSequence).toBeGreaterThanOrEqual(lastSequence);
  });
});
