/**
 * THE F1 LIBRARY/STORED-OUTPUT TESTS (the J015 finding's fix lane) — the
 * cross-surface truth pin for the card model's stored-output projection:
 *
 * THE DEFECT (J015, reproduced live over the production build): a session
 * created through the REAL one-submission upload flow — the J004 shape,
 * all four renders succeeding, the four artifacts STORED and SERVED by the
 * Watch surface — showed on the LIBRARY surface "renders exist but no
 * stored output has been produced yet / STORED OUTPUTS 0 / Not watchable".
 * The J004 derived-reality MP4s land (by design, R508-R510) in the MEDIA
 * platform's per-reality artifact store, while the card's
 * `hasStoredOutputs` read ONLY the render-output segment store
 * (`listRenderOutputs`) — so the catalog's projection could never see the
 * upload path's real outputs. Two surfaces disagreed for the SAME session.
 *
 * THE FIX'S PINS (this battery):
 *
 * - THE J004 ONE-SUBMISSION JOURNEY (real generated MP4, all three derived
 *   realities + the original under ONE compute directive): after the four
 *   renders succeed, the LIBRARY answer (`/api/catalog/library` — the API
 *   the Library surface renders) and the requester-scoped CATALOG answer
 *   (`/api/catalog/sessions`) show the REAL stored-output truth — every
 *   derived render row `hasStoredOutputs: true`, `outputCount` counting the
 *   three derived-reality MP4s PLUS the original reality's normalized MP4,
 *   the session honestly WATCHABLE (the `isWatchable` derivation the
 *   Library card itself uses) — and the rows AGREE with the Watch reality
 *   catalog (`/api/catalog/sessions/[id]/artifacts`: four ready realities;
 *   the same four stored outputs, counted through the other surface).
 *
 * - THE LEGACY W504 SEGMENT-STORE PATH stays green: an `anime.prototype`
 *   render through the single-render route lands its animated-SVG review
 *   segments in the render-output segment store ONLY (no anime-reality
 *   artifact in the media platform for that session) — and its card row
 *   still counts them (`hasStoredOutputs: true`).
 *
 * - THE HONEST NEGATIVE: a render whose outputs landed in NEITHER store
 *   (the sync `sporta.testcard` surface — no segments, no media-platform
 *   artifact) stays honestly `hasStoredOutputs: false`, contributing
 *   nothing to `outputCount` — never a fabricated output.
 *
 * Every media byte is REAL (the in-test MP4s are generated by the real
 * ffmpeg through `generateTestMp4`), every job settles through the real
 * route surfaces, and every card row is the catalog service's own answer.
 */
import { beforeAll, afterAll, describe, expect, test } from "bun:test";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createDeterministicTestHasher } from "@sporta/identity";
import { generateTestMp4, LocalFilesystemStorage } from "@sporta/media-platform";
import { createSportaServer, installSportaServerForTests } from "../src/server/composition";
import type { SportaServer } from "../src/server/composition";
import { SPORTA_SESSION_COOKIE } from "../src/server/auth-service";
import { InMemoryRedis } from "../src/server/platform/upstash/redis";
import { isWatchable } from "../src/lib/surface-state";
import { POST as uploadSessionRoute } from "../src/app/api/create/upload-sessions/route";
import { POST as renderRoute } from "../src/app/api/create/sessions/[sessionId]/renders/route";
import { GET as jobRoute } from "../src/app/api/create/sessions/[sessionId]/jobs/[jobId]/route";
import { GET as mediaJobRoute } from "../src/app/api/media/jobs/[jobId]/route";
import { GET as libraryRoute } from "../src/app/api/catalog/library/route";
import { GET as catalogRoute } from "../src/app/api/catalog/sessions/route";
import { GET as artifactCatalogRoute } from "../src/app/api/catalog/sessions/[sessionId]/artifacts/route";

/** A deterministic stepping clock (the repo's hermetic rig). */
function steppingClock(): () => number {
  let current = 1_999_999_999_000;
  return () => {
    current += 17;
    return current;
  };
}

function withCookie(token: string | null, path: string, init: RequestInit = {}): Request {
  return new Request(`http://sporta.test${path}`, {
    ...init,
    headers: {
      ...((init.headers as Record<string, string> | undefined) ?? {}),
      ...(token === null ? {} : { cookie: `${SPORTA_SESSION_COOKIE}=${token}` }),
    },
  });
}

async function bodyOf(response: Response): Promise<Record<string, unknown>> {
  return (await response.json()) as Record<string, unknown>;
}

function jsonPost(payload: unknown): RequestInit {
  return {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(payload),
  };
}

/** Builds one real MP4 upload request (multipart, like a browser form). */
function uploadRequest(
  token: string | null,
  bytes: Uint8Array,
  operations: string[],
  options: { realitiesJson?: string; computeJson?: string; styleId?: string } = {},
): Request {
  const form = new FormData();
  form.append(
    "file",
    new File([bytes.slice().buffer as ArrayBuffer], "clip.mp4", { type: "video/mp4" }),
  );
  form.append("operations", JSON.stringify(operations));
  if (options.realitiesJson !== undefined) form.append("realities", options.realitiesJson);
  if (options.computeJson !== undefined) form.append("compute", options.computeJson);
  if (options.styleId !== undefined) form.append("styleId", options.styleId);
  return withCookie(token, "/api/create/upload-sessions", { method: "POST", body: form });
}

const FULL_OPERATIONS = ["analysis", "transformation", "derivativeGeneration", "storage"];

/** The card row shape the catalog/library answers carry. */
interface CardRow {
  renderId: string;
  rendererId: string;
  segmentCount: number;
  hasStoredOutputs: boolean;
}

/** One session card, as the API answers it (the fields this lane fixes). */
interface SessionCardAnswer {
  sessionId: string;
  label: string;
  status: string;
  createdAtIso: string;
  playback: { state: "authorized" | "denied"; reasonCode: "ok" | "rights-denied" };
  renders: CardRow[] | null;
  outputCount: number | null;
  realities:
    | {
        rendererId: string;
        renderId: string;
        state: "ready" | "no-stored-output" | "renderer-unavailable";
        segmentCount: number;
        hasStoredOutputs: boolean;
      }[]
    | null;
  realityCount: number | null;
  story: { source: "dev-seed"; storyKey: string; eventCount: number } | null;
}

let server: SportaServer;
let scratch = "";
let creatorToken = "";

beforeAll(async () => {
  scratch = await mkdtemp(join(tmpdir(), "sporta-f1-library-"));
  server = createSportaServer({
    nowMs: steppingClock(),
    passwordHasher: createDeterministicTestHasher(),
    transient: { redis: new InMemoryRedis(steppingClock()), provider: "in-memory" },
    seed: true,
    media: {
      db: ":memory:",
      storage: new LocalFilesystemStorage(join(scratch, "media-storage")),
    },
  });
  installSportaServerForTests(server);
  await server.ready;

  const registered = await server.auth.register({
    username: "f1-library-creator",
    password: "a-real-f1-password",
    roles: ["creator", "viewer"],
  });
  creatorToken = (await server.auth.issueSession({ userId: registered.userId })).token;
});

afterAll(async () => {
  await rm(scratch, { recursive: true, force: true });
});

/** Polls one compute job (through the REAL route) to its terminal state. */
async function pollComputeJob(
  token: string,
  sessionId: string,
  jobId: string,
): Promise<Record<string, unknown>> {
  for (let attempt = 0; attempt < 400; attempt += 1) {
    const response = await jobRoute(
      withCookie(token, `/api/create/sessions/${sessionId}/jobs/${jobId}`),
      { params: Promise.resolve({ sessionId, jobId }) },
    );
    expect(response.status).toBe(200);
    const job = await bodyOf(response);
    if (job.completion !== undefined) return job;
    await Bun.sleep(25);
  }
  throw new Error(`compute job ${jobId} did not settle in the bounded poll`);
}

/** Polls one media job (through the REAL route) to its terminal state. */
async function pollMediaJob(token: string, jobId: string): Promise<Record<string, unknown>> {
  for (let attempt = 0; attempt < 400; attempt += 1) {
    const response = await mediaJobRoute(withCookie(token, `/api/media/jobs/${jobId}`), {
      params: Promise.resolve({ jobId }),
    });
    expect(response.status).toBe(200);
    const job = await bodyOf(response);
    if (job.terminal === true) return job;
    await Bun.sleep(25);
  }
  throw new Error(`media job ${jobId} did not settle in the bounded poll`);
}

/** The library's card for one session (the Library surface's own API). */
async function libraryCardOf(sessionId: string): Promise<SessionCardAnswer> {
  const response = await libraryRoute(withCookie(creatorToken, "/api/catalog/library"));
  expect(response.status).toBe(200);
  const body = (await bodyOf(response)) as { sessions: SessionCardAnswer[] };
  const card = body.sessions.find((entry) => entry.sessionId === sessionId);
  expect(card).toBeDefined();
  return card!;
}

/** The requester-scoped catalog's card for one session (the catalog rows). */
async function catalogCardOf(sessionId: string): Promise<SessionCardAnswer> {
  const response = await catalogRoute(withCookie(creatorToken, "/api/catalog/sessions"));
  expect(response.status).toBe(200);
  const body = (await bodyOf(response)) as { sessions: SessionCardAnswer[] };
  const card = body.sessions.find((entry) => entry.sessionId === sessionId);
  expect(card).toBeDefined();
  return card!;
}

describe("F1 — the J004 one-submission journey shows the stored-output truth on the Library/catalog rows", () => {
  let sessionId = "";
  const planJobIds: string[] = [];

  test("the ONE submission (real MP4, three derived realities, one compute directive) settles all four renders", async () => {
    const providerId = server.selection?.providerId ?? "";
    expect(server.selection).not.toBeNull();
    const clipPath = await generateTestMp4(join(scratch, "f1-four-realities.mp4"), {
      durationSeconds: 1,
      withAudio: false,
    });
    const bytes = new Uint8Array(await Bun.file(clipPath).arrayBuffer());
    const response = await uploadSessionRoute(
      uploadRequest(creatorToken, bytes, FULL_OPERATIONS, {
        realitiesJson: JSON.stringify(["tactical", "three-d-game", "anime-npr"]),
        computeJson: JSON.stringify({ mode: "user-explicit", providerId }),
        styleId: "f1-one-submission",
      }),
    );
    expect(response.status).toBe(201);
    const body = (await bodyOf(response)) as {
      sessionId: string;
      renderPlan: {
        realities: { reality: string; disposition: string; jobId?: string }[];
      };
      source: { job: { jobId: string } | null };
    };
    sessionId = body.sessionId;
    for (const entry of body.renderPlan.realities) {
      expect(entry.disposition).toBe("admitted");
      expect(entry.jobId).toBeTruthy();
      planJobIds.push(entry.jobId!);
    }
    // The media job settles first (the plan dispatched only after the
    // stored-original state) — the original reality's artifact is real.
    expect(body.source.job).not.toBeNull();
    const media = await pollMediaJob(creatorToken, body.source.job!.jobId);
    expect((media as { state: string }).state).toBe("succeeded");
    // Every plan render settles to real success (the MP4s land).
    for (const jobId of planJobIds) {
      const done = (await pollComputeJob(creatorToken, sessionId, jobId)) as {
        state: string;
        renderId: string;
        completion: { status: string; outputs: { contentType: string }[] };
      };
      expect(done.state).toBe("succeeded");
      expect(done.completion.status).toBe("succeeded");
      expect(done.renderId).toBeTruthy();
      expect(done.completion.outputs.length).toBeGreaterThan(0);
    }
  });

  test("THE LIBRARY ANSWER: every derived render row shows its stored output, the session is honestly watchable", async () => {
    const card = await libraryCardOf(sessionId);
    expect(card.playback).toEqual({ state: "authorized", reasonCode: "ok" });
    expect(card.renders).not.toBeNull();
    // The three derived renders — the J004 plan's producers, verbatim.
    expect(card.renders!.map((render) => render.rendererId).sort()).toEqual([
      "anime-npr.prototype",
      "game-3d.prototype",
      "tactical.prototype",
    ]);
    // THE F1 CORE: every render row's outputs ARE stored (the R508+ media
    // landing) — the pre-fix answer here was `false` x3 ("STORED OUTPUTS 0").
    for (const render of card.renders!) {
      expect(render.hasStoredOutputs).toBe(true);
    }
    // The reality groups agree (the Reality Switcher's card-side view).
    expect(card.realities).not.toBeNull();
    for (const group of card.realities!) {
      expect(group.state).toBe("ready");
      expect(group.hasStoredOutputs).toBe(true);
    }
    expect(card.realityCount).toBe(3);
    // The count: three derived-reality MP4s + the original's normalized MP4.
    expect(card.outputCount).toBe(4);
    // The Library card's own watchability derivation (the "Not watchable"
    // verdict of the defect) — now the honest watchable state.
    expect(isWatchable(card)).toBe(true);
  });

  test("THE CATALOG ROWS agree (the requester-scoped answer carries the same truth)", async () => {
    const card = await catalogCardOf(sessionId);
    expect(card.playback).toEqual({ state: "authorized", reasonCode: "ok" });
    expect(card.renders).not.toBeNull();
    for (const render of card.renders!) {
      expect(render.hasStoredOutputs).toBe(true);
    }
    expect(card.outputCount).toBe(4);
    expect(isWatchable(card)).toBe(true);
  });

  test("the rows AGREE with the Watch reality catalog (the same four stored outputs, through the other surface)", async () => {
    const response = await artifactCatalogRoute(
      withCookie(creatorToken, `/api/catalog/sessions/${sessionId}/artifacts`),
      { params: Promise.resolve({ sessionId }) },
    );
    expect(response.status).toBe(200);
    const catalog = (await bodyOf(response)) as {
      realities: { kind: string; availability: string; artifacts: unknown[] }[] | null;
      readyRealityCount: number;
    };
    expect(catalog.realities).not.toBeNull();
    const byKind = new Map(catalog.realities!.map((entry) => [entry.kind, entry]));
    // The Watch surface's truth: ALL FOUR realities ready.
    expect(byKind.get("original")!.availability).toBe("ready");
    expect(byKind.get("tactical")!.availability).toBe("ready");
    expect(byKind.get("three-d-game")!.availability).toBe("ready");
    expect(byKind.get("anime-npr")!.availability).toBe("ready");
    expect(catalog.readyRealityCount).toBe(4);
    // The cross-surface agreement, counted: the card's stored outputs (4)
    // are exactly the Watch reality catalog's ready realities (4) — the two
    // surfaces tell the SAME truth for the SAME session.
    const card = await libraryCardOf(sessionId);
    expect(card.outputCount).toBe(catalog.readyRealityCount);
    // And per renderer: every render row the card says has a stored output
    // maps to a ready derived reality in the Watch catalog.
    const rendererToReality: Record<string, string> = {
      "tactical.prototype": "tactical",
      "game-3d.prototype": "three-d-game",
      "anime-npr.prototype": "anime-npr",
    };
    for (const render of card.renders!) {
      expect(render.hasStoredOutputs).toBe(true);
      const realityKind = rendererToReality[render.rendererId];
      expect(realityKind).toBeDefined();
      expect(byKind.get(realityKind!)!.availability).toBe("ready");
    }
  });
});

describe("F1 — the legacy W504 segment-store path stays green (the SVG review segments still count)", () => {
  let sessionId = "";

  test("an anime.prototype render through the single-render route lands its SVG review segments (no media artifact for it)", async () => {
    const clipPath = await generateTestMp4(join(scratch, "f1-legacy-svg.mp4"), {
      durationSeconds: 1,
      withAudio: false,
    });
    const bytes = new Uint8Array(await Bun.file(clipPath).arrayBuffer());
    const response = await uploadSessionRoute(uploadRequest(creatorToken, bytes, FULL_OPERATIONS));
    expect(response.status).toBe(201);
    const body = (await bodyOf(response)) as {
      sessionId: string;
      source: { job: { jobId: string } | null };
    };
    sessionId = body.sessionId;
    expect(body.source.job).not.toBeNull();
    const media = await pollMediaJob(creatorToken, body.source.job!.jobId);
    expect((media as { state: string }).state).toBe("succeeded");

    const dispatch = await renderRoute(
      withCookie(
        creatorToken,
        `/api/create/sessions/${sessionId}/renders`,
        jsonPost({ rendererId: "anime.prototype", styleId: "f1-legacy-svg" }),
      ),
      { params: Promise.resolve({ sessionId }) },
    );
    expect(dispatch.status).toBe(202);
    const dispatchBody = (await bodyOf(dispatch)) as { jobId: string };
    const done = (await pollComputeJob(creatorToken, sessionId, dispatchBody.jobId)) as {
      state: string;
      renderId: string;
      completion: { status: string };
    };
    expect(done.state).toBe("succeeded");
    expect(done.renderId).toBeTruthy();

    // The truth source is the SEGMENT store: this session's media platform
    // holds NO anime-reality artifact (the legacy path never lands one).
    const animeArtifacts = server.media
      .artifactsOfSession(sessionId)
      .filter((artifact) => artifact.reality === "anime-npr");
    expect(animeArtifacts).toHaveLength(0);
    // ...and the render's segments ARE in the render-output segment store.
    const outputs = await server.control.listRenderOutputs(sessionId, done.renderId);
    expect(outputs.segments.length).toBeGreaterThan(0);
  });

  test("the card row still counts the segment-store outputs (watchable through the legacy path)", async () => {
    const card = await libraryCardOf(sessionId);
    expect(card.playback).toEqual({ state: "authorized", reasonCode: "ok" });
    expect(card.renders).not.toBeNull();
    const anime = card.renders!.find((render) => render.rendererId === "anime.prototype");
    expect(anime).toBeDefined();
    expect(anime!.hasStoredOutputs).toBe(true);
    // The count: the SVG review segment(s) + the original's normalized MP4.
    const outputs = await server.control.listRenderOutputs(sessionId, anime!.renderId);
    expect(card.outputCount).toBe(outputs.segments.length + 1);
    expect(isWatchable(card)).toBe(true);
  });
});

describe("F1 — a render with NO outputs anywhere stays honestly false", () => {
  let sessionId = "";

  test("a sync testcard render (no segment outputs, no media artifact) — the honest negative", async () => {
    const clipPath = await generateTestMp4(join(scratch, "f1-no-outputs.mp4"), {
      durationSeconds: 1,
      withAudio: false,
    });
    const bytes = new Uint8Array(await Bun.file(clipPath).arrayBuffer());
    const response = await uploadSessionRoute(uploadRequest(creatorToken, bytes, FULL_OPERATIONS));
    expect(response.status).toBe(201);
    const body = (await bodyOf(response)) as {
      sessionId: string;
      source: { job: { jobId: string } | null };
    };
    sessionId = body.sessionId;
    expect(body.source.job).not.toBeNull();
    const media = await pollMediaJob(creatorToken, body.source.job!.jobId);
    expect((media as { state: string }).state).toBe("succeeded");

    // The sync control-plane surface (the dev-seed's own pattern): a real
    // render record whose outputs landed in NEITHER store.
    const render = await server.control.createRender(sessionId, {
      rendererId: "sporta.testcard",
    });
    expect(render.renderId).toBeTruthy();
    const outputs = await server.control.listRenderOutputs(sessionId, render.renderId);
    expect(outputs.segments).toHaveLength(0);
    expect(server.media.artifactsOfSession(sessionId).length).toBe(1); // the original only
  });

  test("the card row says no stored output; the count stays honest (only the upload's original)", async () => {
    const card = await libraryCardOf(sessionId);
    expect(card.playback).toEqual({ state: "authorized", reasonCode: "ok" });
    expect(card.renders).not.toBeNull();
    expect(card.renders).toHaveLength(1);
    expect(card.renders![0]!.rendererId).toBe("sporta.testcard");
    // THE HONEST NEGATIVE: no segment outputs, no attributable media
    // artifact — the row stays false, never a fabricated output.
    expect(card.renders![0]!.hasStoredOutputs).toBe(false);
    // The session's real stored outputs: the upload's original MP4 only —
    // the render contributes nothing it did not store.
    expect(card.outputCount).toBe(1);
    // The reality group honestly reports the render's emptiness.
    expect(card.realities).not.toBeNull();
    expect(card.realities![0]!.state).toBe("no-stored-output");
    expect(card.realities![0]!.hasStoredOutputs).toBe(false);
    // The session is still watchable through its original reality (the
    // Watch surface serves it) — the same truth, both surfaces.
    expect(isWatchable(card)).toBe(true);
  });
});
