/**
 * THE REAL BROWSER GOLDEN PATH (R507) — the test-pinned end-to-end walk a
 * CLEAN browser completes over the REAL seams, with NO fixture standing in
 * for user input:
 *
 *   register + sign in (the clean browser's own account)
 *     → UPLOAD a real MP4 through the R501 upload-sessions route (the
 *       exact multipart the studio UI posts; the MP4 is generated by the
 *       REAL ffmpeg in-test — never a committed fixture)
 *     → the honest job states (the R103 media pipeline + the W914 compute
 *       job, every observed state a real server state)
 *     → the COMPUTE legibility (R506: the SelectionDirector's explanation
 *       pinned; the plane's ownership)
 *     → the CATALOG (R503: the four realities, real descriptors)
 *     → WATCH with REAL MP4 PLAYBACK (R504: the HTML5 player's byte route
 *       serves the real artifact — 200 full + 206 range, and the served
 *       bytes' sha-256 EQUALS the descriptor's integrity hash)
 *     → the REALITY SWITCH (R505: the same session held constant; the
 *       pure selection function over the real catalog; the URL-addressable
 *       deep link; the honest not-video boundary for the SVG reality).
 *
 * The walk FAILS LOUDLY at any seam that silently degrades to a non-real
 * path: every step asserts the real shape it depends on, and the final
 * integrity check re-hashes the served bytes against the catalog's own
 * descriptor. REAL vs FIXTURE BOUNDARY: the only non-product input is the
 * generated test clip (real ffmpeg output — no committed media fixture);
 * the seeded story sessions exist but the golden path never touches them.
 */
import { beforeAll, afterAll, describe, expect, test } from "bun:test";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createDeterministicTestHasher } from "@sporta/identity";
import { generateTestMp4, sha256OfBytes } from "@sporta/media-platform";
import { createSportaServer, installSportaServerForTests } from "../src/server/composition";
import type { SportaServer } from "../src/server/composition";
import { SPORTA_SESSION_COOKIE } from "../src/server/auth-service";
import { InMemoryRedis } from "../src/server/platform/upstash/redis";
import { POST as registerRoute } from "../src/app/api/auth/register/route";
import { POST as uploadSessionRoute } from "../src/app/api/create/upload-sessions/route";
import { POST as computePreviewRoute } from "../src/app/api/create/compute-preview/route";
import { GET as computeStatusRoute } from "../src/app/api/create/compute-status/route";
import { POST as renderRoute } from "../src/app/api/create/sessions/[sessionId]/renders/route";
import { GET as jobRoute } from "../src/app/api/create/sessions/[sessionId]/jobs/[jobId]/route";
import { GET as mediaJobRoute } from "../src/app/api/media/jobs/[jobId]/route";
import { GET as artifactCatalogRoute } from "../src/app/api/catalog/sessions/[sessionId]/artifacts/route";
import { GET as watchRoute } from "../src/app/api/watch/[sessionId]/route";
import { GET as realitiesRoute } from "../src/app/api/watch/[sessionId]/realities/route";
import { GET as videoRoute } from "../src/app/api/watch/[sessionId]/realities/[kind]/artifacts/[artifactId]/content/route";
import { GET as sessionStateRoute } from "../src/app/api/create/sessions/[sessionId]/route";
import {
  selectedRealityOf,
  videoDescriptorOf,
  videoSourceOf,
  watchUrlOf,
} from "../src/lib/reality-catalog";
import type { SessionArtifactCatalogLike } from "../src/lib/api-types";

/** A deterministic stepping clock (the repo's hermetic rig). */
function steppingClock(): () => number {
  let current = 2_222_222_222_000;
  return () => {
    current += 17;
    return current;
  };
}

function withCookie(token: string | null, path: string, init: RequestInit = {}): Request {
  return new Request(`http://sporta.test${path}`, {
    ...init,
    headers: {
      ...((init.headers as Record<string, string> | undefined) ?? {}),
      ...(token === null ? {} : { cookie: `${SPORTA_SESSION_COOKIE}=${token}` }),
    },
  });
}

async function bodyOf(response: Response): Promise<Record<string, unknown>> {
  return (await response.json()) as Record<string, unknown>;
}

function jsonPost(payload: unknown): RequestInit {
  return {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(payload),
  };
}

let server: SportaServer;
let scratch = "";
let token = "";
let sessionId = "";
let mediaJobId = "";
let computeJobId = "";
let providerId = "";
/** The derived-reality compute jobs (R508-R510: tactical / 3D / anime-NPR). */
const derivedJobIds: string[] = [];
/** The session's ONE realities acquisition (steps 6/7 share it - the switch never re-acquires). */
let acquiredCatalog: SessionArtifactCatalogLike | null = null;

/** The observed job states along the walk (pinned: every one is real). */
const observedComputeStates: string[] = [];
const observedMediaStates: string[] = [];

beforeAll(async () => {
  scratch = await mkdtemp(join(tmpdir(), "sporta-golden-path-"));
  server = createSportaServer({
    nowMs: steppingClock(),
    passwordHasher: createDeterministicTestHasher(),
    transient: { redis: new InMemoryRedis(steppingClock()), provider: "in-memory" },
    seed: true,
    media: { db: ":memory:" },
  });
  installSportaServerForTests(server);
  await server.ready;
  providerId = server.selection?.providerId ?? "";
});

afterAll(async () => {
  await rm(scratch, { recursive: true, force: true });
});

// ---------------------------------------------------------------------------
// Step 0 — the clean browser: a fresh account (no seeded session, no
// developer action, no fixture selection — the R603 posture, proven here).
// ---------------------------------------------------------------------------

/** The last (diagnostics) descriptor's content type of one reality entry. */
function diagnosticsContentTypeOf(entry: { artifacts: { contentType: string }[] }): string {
  return entry.artifacts[entry.artifacts.length - 1]!.contentType;
}

describe("the golden path (R507: clean browser → upload → jobs → catalog → watch → switch)", () => {
  test("step 0 — the clean browser registers its own account", async () => {
    const response = await registerRoute(
      withCookie(null, "/api/auth/register", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          username: "golden-path-browser",
          password: "a-fresh-browser-password",
          roles: ["creator", "viewer"],
        }),
      }),
    );
    expect(response.status).toBe(200);
    const body = (await bodyOf(response)) as { userId: string };
    expect(body.userId.length).toBeGreaterThan(0);
    const session = await server.auth.issueSession({ userId: body.userId });
    token = session.token; // the browser's HttpOnly cookie value
    expect(token.length).toBeGreaterThan(0);
  });

  test("step 1 — a REAL MP4 upload becomes the session (the R101/R501 seams)", async () => {
    // REAL ffmpeg generates the clip (320×240, 2s, audio) — no committed fixture.
    const clipPath = await generateTestMp4(join(scratch, "golden-clip.mp4"), {
      durationSeconds: 2,
      withAudio: true,
    });
    const bytes = new Uint8Array(await Bun.file(clipPath).arrayBuffer());
    expect(bytes.byteLength).toBeGreaterThan(1024);

    const form = new FormData();
    form.append(
      "file",
      new File([bytes.slice().buffer as ArrayBuffer], "golden.mp4", { type: "video/mp4" }),
    );
    form.append(
      "operations",
      JSON.stringify(["analysis", "transformation", "derivativeGeneration", "storage"]),
    );
    form.append("label", "The golden path clip");
    const response = await uploadSessionRoute(
      withCookie(token, "/api/create/upload-sessions", { method: "POST", body: form }),
    );
    expect(response.status).toBe(201);
    const body = (await bodyOf(response)) as {
      sessionId: string;
      rightsCapabilities: { canStoreDerivatives: boolean };
      source: {
        asset: { uploadState: string; checksumVerified: boolean; container: string };
        job: { jobId: string; state: string } | null;
      };
      perception: { frameCount: number; summary: string };
    };
    sessionId = body.sessionId;
    // The honest source states (R502): the real R101 records, verbatim.
    expect(body.source.asset.uploadState).toBe("stored");
    expect(body.source.asset.checksumVerified).toBe(true);
    expect(body.source.asset.container).toBe("mp4");
    expect(body.rightsCapabilities.canStoreDerivatives).toBe(true);
    expect(body.source.job).not.toBeNull();
    mediaJobId = body.source.job!.jobId;
    // The real R207 perception: the session's world model came from the
    // UPLOADED clip's own decoded frames.
    expect(body.perception.frameCount).toBe(48);
    expect(body.perception.summary.length).toBeGreaterThan(0);
  });

  test("step 2 — the compute step runs the REAL SelectionDirector (R501/R506)", async () => {
    const response = await computePreviewRoute(
      withCookie(
        token,
        "/api/create/compute-preview",
        jsonPost({
          rendererId: "anime.prototype",
          latencyClass: "offline",
          compute: { mode: "sporta-auto", preference: { privacyPosture: "privacy-any" } },
        }),
      ),
    );
    expect(response.status).toBe(200);
    const body = (await bodyOf(response)) as {
      selection: { providerId: string };
      explanation: { mode: string; selectedProviderId: string; selectionReason: string };
    };
    expect(body.selection.providerId).toBe(providerId);
    expect(body.explanation.selectedProviderId).toBe(providerId);
    expect(body.explanation.selectionReason.length).toBeGreaterThan(0);
  });

  test("step 2b — the compute/cost status answers the plane's ownership + allowances (R506)", async () => {
    const response = await computeStatusRoute(withCookie(token, "/api/create/compute-status"));
    expect(response.status).toBe(200);
    const body = (await bodyOf(response)) as {
      plane: { executionOwnership: string; providerId: string } | null;
      quotas: { used: number | null; limit: number | null }[];
    };
    expect(body.plane!.executionOwnership).toBe("sporta-managed");
    expect(body.plane!.providerId).toBe(providerId);
    expect(body.quotas.length).toBeGreaterThan(0);
    for (const quota of body.quotas) {
      expect(quota.used).not.toBeNull();
      expect(quota.limit).not.toBeNull();
    }
  });

  test("step 3 — the render dispatch (with the user's explicit compute choice) is admitted", async () => {
    const response = await renderRoute(
      withCookie(
        token,
        `/api/create/sessions/${sessionId}/renders`,
        jsonPost({
          rendererId: "anime.prototype",
          styleId: "golden-path",
          compute: { mode: "user-explicit", providerId },
        }),
      ),
      { params: Promise.resolve({ sessionId }) },
    );
    expect(response.status).toBe(202);
    const body = (await bodyOf(response)) as {
      disposition: string;
      jobId: string;
      selection: { providerId: string; mode: string };
    };
    expect(body.disposition).toBe("admitted");
    expect(body.selection.providerId).toBe(providerId);
    expect(body.selection.mode).toBe("user-explicit");
    computeJobId = body.jobId;
  });

  test("step 3b — the DERIVED-REALITY dispatches: tactical, 3D game, and anime/NPR (R508-R510)", async () => {
    // The same explicit compute choice, the same session, the SAME canonical
    // SWM (the control plane materializes one snapshot + one event window
    // per dispatch from the session's own world model).
    for (const rendererId of ["tactical.prototype", "game-3d.prototype", "anime-npr.prototype"]) {
      const response = await renderRoute(
        withCookie(
          token,
          `/api/create/sessions/${sessionId}/renders`,
          jsonPost({
            rendererId,
            styleId: "golden-path-derived",
            compute: { mode: "user-explicit", providerId },
          }),
        ),
        { params: Promise.resolve({ sessionId }) },
      );
      expect(response.status).toBe(202);
      const body = (await bodyOf(response)) as {
        disposition: string;
        jobId: string;
        selection: { providerId: string; mode: string };
      };
      expect(body.disposition).toBe("admitted");
      expect(body.selection.providerId).toBe(providerId);
      expect(body.selection.mode).toBe("user-explicit");
      derivedJobIds.push(body.jobId);
    }
    expect(derivedJobIds).toHaveLength(3);
  });

  test("step 4 — the honest job states walk to terminal success (R502/R103)", async () => {
    // The compute job: every observed state is the control plane's own.
    let computeTerminal: Record<string, unknown> | null = null;
    for (let attempt = 0; attempt < 400; attempt += 1) {
      const response = await jobRoute(
        withCookie(token, `/api/create/sessions/${sessionId}/jobs/${computeJobId}`),
        { params: Promise.resolve({ sessionId, jobId: computeJobId }) },
      );
      expect(response.status).toBe(200);
      const job = (await bodyOf(response)) as { state: string; completion?: unknown };
      observedComputeStates.push(job.state);
      if (job.completion !== undefined) {
        computeTerminal = job;
        break;
      }
      await Bun.sleep(25);
    }
    expect(computeTerminal).not.toBeNull();
    const done = computeTerminal as {
      state: string;
      renderId: string;
      selection: { providerId: string; mode: string; explanation: { selectionReason: string } };
      completion: {
        status: string;
        outputs: { artifactId: string }[];
        usage: { unitId: string; quantity: number }[];
      };
    };
    expect(done.state).toBe("succeeded");
    expect(done.completion.status).toBe("succeeded");
    expect(done.renderId.length).toBeGreaterThan(0);
    expect(done.completion.outputs.length).toBeGreaterThan(0);
    // R506 rides the golden path: the selection explanation is carried
    // VERBATIM on the job the whole way.
    expect(done.selection.providerId).toBe(providerId);
    expect(done.selection.mode).toBe("user-explicit");
    expect(done.selection.explanation.selectionReason.length).toBeGreaterThan(0);

    // R508-R510: the three derived-reality compute jobs (tactical / 3D /
    // anime-NPR) walk to terminal success the same way — each completion's
    // output artifact is the REAL MP4 the R306 bridge encoded (the honest
    // video/mp4+base64 inline representation, never an SVG stand-in).
    for (const jobId of derivedJobIds) {
      let derivedTerminal: Record<string, unknown> | null = null;
      for (let attempt = 0; attempt < 400; attempt += 1) {
        const response = await jobRoute(
          withCookie(token, `/api/create/sessions/${sessionId}/jobs/${jobId}`),
          { params: Promise.resolve({ sessionId, jobId }) },
        );
        expect(response.status).toBe(200);
        const job = (await bodyOf(response)) as {
          state: string;
          completion?: unknown;
        };
        observedComputeStates.push(job.state);
        if (job.completion !== undefined) {
          derivedTerminal = job;
          break;
        }
        await Bun.sleep(25);
      }
      expect(derivedTerminal).not.toBeNull();
      const derivedDone = derivedTerminal as {
        state: string;
        completion: {
          status: string;
          outputs: { artifactId: string; contentType: string }[];
        };
      };
      expect(derivedDone.state).toBe("succeeded");
      expect(derivedDone.completion.status).toBe("succeeded");
      expect(derivedDone.completion.outputs.length).toBeGreaterThan(0);
      for (const output of derivedDone.completion.outputs) {
        expect(output.contentType).toBe("video/mp4+base64");
        expect(output.artifactId).toMatch(/^[0-9a-f]{64}$/);
      }
    }

    // The media job (the normalization pipeline): real stages to success.
    let mediaTerminal: Record<string, unknown> | null = null;
    for (let attempt = 0; attempt < 400; attempt += 1) {
      const response = await mediaJobRoute(withCookie(token, `/api/media/jobs/${mediaJobId}`), {
        params: Promise.resolve({ jobId: mediaJobId }),
      });
      expect(response.status).toBe(200);
      const job = (await bodyOf(response)) as { state: string; terminal: boolean };
      observedMediaStates.push(job.state);
      if (job.terminal) {
        mediaTerminal = job;
        break;
      }
      await Bun.sleep(25);
    }
    expect(mediaTerminal).not.toBeNull();
    const mediaDone = mediaTerminal as {
      state: string;
      result: { artifactId: string };
    };
    expect(mediaDone.state).toBe("succeeded");
    expect(mediaDone.result.artifactId.length).toBeGreaterThan(0);
    // The observed states were REAL states throughout (the closed vocab).
    for (const state of observedComputeStates) {
      expect(state.length).toBeGreaterThan(0);
    }
    expect(observedMediaStates.length).toBeGreaterThan(0);
  });

  test("step 5 — the four-reality artifact catalog links the REAL outputs (R503)", async () => {
    const response = await artifactCatalogRoute(
      withCookie(token, `/api/catalog/sessions/${sessionId}/artifacts`),
      { params: Promise.resolve({ sessionId }) },
    );
    expect(response.status).toBe(200);
    const body = (await bodyOf(response)) as {
      playback: { state: string };
      readyRealityCount: number;
      realities: {
        kind: string;
        availability: string;
        artifacts: {
          artifactId: string;
          kind: string;
          manifestLink: string;
          integrityHash: string;
          byteSize: number;
          contentType: string;
          producerId: string;
        }[];
      }[];
    };
    expect(body.playback.state).toBe("authorized");
    expect(body.realities.map((entry) => entry.kind)).toEqual([
      "original",
      "tactical",
      "three-d-game",
      "anime-npr",
    ]);
    const original = body.realities.find((entry) => entry.kind === "original")!;
    expect(original.availability).toBe("ready");
    expect(original.artifacts.length).toBeGreaterThan(0);
    // The original reality's descriptor is the REAL MP4 artifact.
    expect(original.artifacts[0]!.contentType).toContain("mp4");
    expect(original.artifacts[0]!.integrityHash).toMatch(/^[0-9a-f]{64}$/);
    expect(original.artifacts[0]!.byteSize).toBeGreaterThan(1024);
    // R508-R510 — THE FOUR-REALITY GATE: every reality is READY and holds a
    // REAL MP4 descriptor (the acceptance contract §D: Original, Tactical,
    // 3D Game, and Anime/NPR are actual MP4 videos, integrity-verifiable).
    expect(body.readyRealityCount).toBe(4);
    for (const entry of body.realities) {
      expect(entry.availability, `${entry.kind} must be ready`).toBe("ready");
      expect(entry.artifacts.length, `${entry.kind} must hold artifacts`).toBeGreaterThan(0);
      // The descriptor's own video resolution (the player's pure model).
      const video = entry.artifacts.find(
        (artifact) =>
          artifact.contentType === "video/mp4" || artifact.contentType.startsWith("mp4/"),
      );
      expect(video, `${entry.kind} must hold a real MP4 descriptor`).toBeDefined();
      expect(video!.integrityHash).toMatch(/^[0-9a-f]{64}$/);
      expect(video!.byteSize).toBeGreaterThan(1024);
    }
    // The derived realities' primary MP4 descriptors name their producers.
    expect(
      body.realities.find((entry) => entry.kind === "tactical")!.artifacts[0]!.producerId,
    ).toBe("tactical.prototype");
    expect(
      body.realities.find((entry) => entry.kind === "three-d-game")!.artifacts[0]!.producerId,
    ).toBe("game-3d.prototype");
    expect(
      body.realities.find((entry) => entry.kind === "anime-npr")!.artifacts[0]!.producerId,
    ).toBe("anime-npr.prototype");
    // The anime-npr reality ALSO carries the W504 SVG review segment (the
    // explicitly-labeled diagnostics surface — listed AFTER the MP4).
    const anime = body.realities.find((entry) => entry.kind === "anime-npr")!;
    expect(anime.artifacts.length).toBeGreaterThan(1);
    expect(diagnosticsContentTypeOf(anime)).toBe("image/svg+xml");
  });

  test("step 6 — WATCH with REAL MP4 PLAYBACK: the byte route serves ALL FOUR realities, integrity-verified (R504/R508-R510)", async () => {
    // The watch acquisition (the page's own first read).
    const watchResponse = await watchRoute(withCookie(token, `/api/watch/${sessionId}`), {
      params: Promise.resolve({ sessionId }),
    });
    expect(watchResponse.status).toBe(200);
    const watch = (await bodyOf(watchResponse)) as {
      sessionId: string;
      playback: { state: string };
      renders: { renderId: string }[] | null;
    };
    expect(watch.sessionId).toBe(sessionId);
    expect(watch.playback.state).toBe("authorized");
    expect(watch.renders!.length).toBeGreaterThan(0);

    // THE ONE realities acquisition (the switcher + the player's catalog —
    // steps 6 AND 7 run on this same acquisition; the switch never
    // re-acquires and never changes the session).
    const realitiesResponse = await realitiesRoute(
      withCookie(token, `/api/watch/${sessionId}/realities`),
      { params: Promise.resolve({ sessionId }) },
    );
    expect(realitiesResponse.status).toBe(200);
    const realities = (await bodyOf(realitiesResponse)) as {
      sessionId: string;
      artifacts: SessionArtifactCatalogLike;
    };
    expect(realities.sessionId).toBe(sessionId); // the session CONSTANT
    const catalog = realities.artifacts;
    expect(catalog.realities).not.toBeNull();
    acquiredCatalog = catalog; // step 7 switches on THIS acquisition

    // ALL FOUR REALITIES PLAY: the HTML5 player's source resolution + the
    // byte route's verified read, per reality — Original, Tactical, 3D
    // Game, and Anime/NPR are REAL MP4s on the SAME session.
    const kinds = ["original", "tactical", "three-d-game", "anime-npr"] as const;
    for (const kind of kinds) {
      const entry = catalog.realities!.find((candidate) => candidate.kind === kind)!;
      expect(entry.availability).toBe("ready");
      const descriptor = videoDescriptorOf(entry);
      expect(descriptor, `${kind} must hold a video-playable descriptor`).not.toBeNull();
      const sourceUrl = videoSourceOf(sessionId, kind, descriptor!.artifactId);

      // THE REAL MP4 PLAYBACK: the byte route serves the artifact's bytes.
      const full = await videoRoute(withCookie(token, sourceUrl), {
        params: Promise.resolve({
          sessionId,
          kind,
          artifactId: descriptor!.artifactId,
        }),
      });
      expect(full.status, `${kind} must serve 200`).toBe(200);
      expect(full.headers.get("content-type")).toBe("video/mp4");
      expect(full.headers.get("accept-ranges")).toBe("bytes");
      const bytes = new Uint8Array(await full.arrayBuffer());
      expect(bytes.byteLength).toBe(descriptor!.byteSize);
      // THE INTEGRITY EVIDENCE: the served bytes' sha-256 EQUALS the catalog
      // descriptor's integrityHash (the store re-verifies per request).
      expect(sha256OfBytes(bytes)).toBe(descriptor!.integrityHash);
      // Real raster video: the MP4 container magic.
      expect(Buffer.from(bytes.subarray(4, 8)).toString("ascii")).toBe("ftyp");

      // The browser's Range fetch (exactly what <video> issues on seek).
      const range = await videoRoute(
        withCookie(token, sourceUrl, { headers: { range: "bytes=0-1023" } }),
        {
          params: Promise.resolve({
            sessionId,
            kind,
            artifactId: descriptor!.artifactId,
          }),
        },
      );
      expect(range.status, `${kind} must serve a 206 range`).toBe(206);
      expect(range.headers.get("content-range")).toBe(`bytes 0-1023/${descriptor!.byteSize}`);
      const slice = new Uint8Array(await range.arrayBuffer());
      expect(slice.byteLength).toBe(1024);
      expect(Array.from(slice)).toEqual(Array.from(bytes.slice(0, 1024)));
    }

    // The HONEST not-video boundary rides the same acquisition: the
    // anime-npr reality's W504 SVG review segment (the diagnostics
    // descriptor) still answers the typed 415 — never presented as video.
    const animeEntry = catalog.realities!.find((entry) => entry.kind === "anime-npr")!;
    const diagnostics = animeEntry.artifacts.find(
      (artifact) => artifact.contentType === "image/svg+xml",
    );
    expect(diagnostics).toBeDefined();
    const notVideo = await videoRoute(
      withCookie(token, videoSourceOf(sessionId, "anime-npr", diagnostics!.artifactId)),
      {
        params: Promise.resolve({
          sessionId,
          kind: "anime-npr",
          artifactId: diagnostics!.artifactId,
        }),
      },
    );
    expect(notVideo.status).toBe(415); // typed, never a silent fallback
  });

  test("step 7 — THE REALITY SWITCH across ALL FOUR: same session, same acquisition, the URL addresses it (R505 + acceptance §E)", async () => {
    // The switcher runs on the SAME acquisition step 6 captured (no
    // re-acquisition, no session change — the session is the constant of
    // every switch; the acceptance contract §F).
    const catalog = acquiredCatalog!;
    expect(catalog).not.toBeNull();
    expect(catalog.sessionId).toBe(sessionId);

    // The deterministic default: the first ready reality (original).
    const initial = selectedRealityOf(null, catalog);
    expect(initial.kind).toBe("original");

    // THE FULL SWITCH WALK: original → tactical → three-d-game → anime-npr
    // → original. Every switch selects the reality's REAL MP4 descriptor,
    // every deep link addresses the switched state, and every playback
    // re-serves the SAME bytes (hash-verified) on the SAME session.
    const switchOrder = ["tactical", "three-d-game", "anime-npr", "original"] as const;
    for (const kind of switchOrder) {
      const switched = selectedRealityOf(kind, catalog);
      expect(switched.kind).toBe(kind);
      expect(switched.fromUrl).toBe(true);
      expect(watchUrlOf(sessionId, kind)).toBe(
        `/watch?session=${encodeURIComponent(sessionId)}&reality=${encodeURIComponent(kind)}`,
      );
      const entry = catalog.realities!.find((candidate) => candidate.kind === kind)!;
      const descriptor = videoDescriptorOf(entry);
      expect(descriptor, `${kind} must hold a video descriptor to switch to`).not.toBeNull();
      const replay = await videoRoute(
        withCookie(token, videoSourceOf(sessionId, kind, descriptor!.artifactId)),
        {
          params: Promise.resolve({
            sessionId,
            kind,
            artifactId: descriptor!.artifactId,
          }),
        },
      );
      expect(replay.status, `${kind} must re-serve after the switch`).toBe(200);
      expect(sha256OfBytes(new Uint8Array(await replay.arrayBuffer()))).toBe(
        descriptor!.integrityHash,
      );
    }

    // A deep link to an UNRENDERED reality on a fresh session would select
    // it and show its honest state; here every reality IS rendered — the
    // honest deep-link selection is the four-reality walk above.

    // ------------------------------------------------------------------
    // SAME-EVENT INTEGRITY (acceptance contract §E, R605 evidence): the
    // four realities reference ONE canonical session/SWM. Event ordering,
    // game clock, and ball/player continuity flow from that ONE SWM; no
    // renderer invented or changed a canonical event.
    // ------------------------------------------------------------------
    const engine = server.engines.get(sessionId)!;
    const snapshot = engine.snapshot();
    // (1) The session id is CONSTANT across every reality acquisition (the
    //     one acquisition + every descriptor's frozen manifest).
    expect(snapshot.sessionId).toBe(sessionId);
    const { RenderArtifactManifest } = await import("@sporta/contracts");
    const derivedKinds = ["tactical", "three-d-game", "anime-npr"] as const;
    const frozenManifests = derivedKinds.map((kind) => {
      const entry = catalog.realities!.find((candidate) => candidate.kind === kind)!;
      const descriptor = videoDescriptorOf(entry)!;
      return RenderArtifactManifest.parse(server.media.artifact(descriptor.artifactId));
    });
    for (const frozen of frozenManifests) {
      // (1) The session id is the constant of every reality.
      expect(frozen.sessionId).toBe(sessionId);
      // (2) Event ordering: every reality consumed the SAME canonical event
      //     window (the engine's watermark anchored the window; the
      //     manifests' lastEventSequence is the highest sequence the
      //     renderer actually applied — never asserted, never invented).
      expect(frozen.swm!.lastEventSequence).toBe(frozenManifests[0]!.swm!.lastEventSequence);
      // (3) The canonical SWM version every reality read is the SAME.
      expect(frozen.swm!.snapshotVersion).toBe(frozenManifests[0]!.swm!.snapshotVersion);
    }
    // The canonical world model's own accounting: the event stream is
    // strictly ascending (the ordering every reality consumed), and the
    // derived manifests' provenance is within the world model's own truth.
    const events = engine.eventsSince(0);
    for (let i = 1; i < events.length; i += 1) {
      expect(events[i]!.sequence).toBeGreaterThan(events[i - 1]!.sequence);
    }
    expect(frozenManifests[0]!.swm!.lastEventSequence).toBeLessThanOrEqual(
      Math.max(snapshot.watermark.sequence, events.at(-1)?.sequence ?? 0),
    );
    // (4) Game clock: the snapshot's football clock/score state is the ONE
    //     canonical substrate the realities rendered (the tactical
    //     overlay, the 3D HUD, and the anime HUD draw it VERBATIM from the
    //     snapshot — the shared snapshotVersion pins them to the same
    //     clock state; a renderer never re-derives it).
    expect(snapshot.football).toBeDefined();
    expect(snapshot.football!.clock.clockMs).toBeGreaterThanOrEqual(0);
    expect(Number.isFinite(snapshot.football!.clock.clockMs)).toBe(true);
    // (5) Ball/player continuity: the snapshot's entity set (the ball via
    //     the football possession reference + the participants) is the
    //     shared continuity substrate — the same entity identities every
    //     reality rendered, held stable by the ONE snapshot version.
    expect(snapshot.entities.length).toBeGreaterThan(0);
    const entityIds = snapshot.entities.map((entity) => entity.entityId);
    expect(new Set(entityIds).size).toBe(entityIds.length); // identities are unique

    // The compute provenance rides the switched surface (R506): the
    // session state's job row for the anime render carries the selection.
    const sessionState = await sessionStateRoute(
      withCookie(token, `/api/create/sessions/${sessionId}`),
      { params: Promise.resolve({ sessionId }) },
    );
    expect(sessionState.status).toBe(200);
    const state = (await bodyOf(sessionState)) as {
      sessionId: string;
      jobs: { rendererId: string | null; selection?: { providerId: string; mode: string } }[];
    };
    expect(state.sessionId).toBe(sessionId); // the session NEVER changed
    for (const rendererId of [
      "anime.prototype",
      "tactical.prototype",
      "game-3d.prototype",
      "anime-npr.prototype",
    ]) {
      const job = state.jobs.find((row) => row.rendererId === rendererId);
      expect(job, `${rendererId}'s job row must exist`).not.toBeUndefined();
      expect(job!.selection!.providerId).toBe(providerId);
      expect(job!.selection!.mode).toBe("user-explicit");
    }
  });
});
