/**
 * THE REAL-MEDIA LOOP ROUTE TEST (R101-R104) — the hermetic route-level
 * proof the packet demands, following the cost-guardrails pattern exactly:
 * real route handlers over a real composed server (deterministic hasher,
 * in-memory transient state, the real dev seed), with the media seams
 * injected (temp storage dir + sqlite) and EVERY media byte REAL — the
 * in-test MP4 is generated by the real ffmpeg (`generateTestMp4`), never a
 * committed fixture.
 *
 * The end-to-end hash chain (§D acceptance):
 *
 *   upload bytes (sha-256 #1)
 *     → 201 SourceAsset { contentHash: #1, uploadState "stored",
 *                        checksumVerified: true }
 *     → poll job → succeeded (stage trail: upload-complete →
 *       normalization-complete → artifact-stored)
 *     → MediaManifest { contentHash: #2 } (the re-encoded canonical MP4)
 *     → RenderArtifactManifest { reality "original", contentHash: #2,
 *                                integrity.verified: true }
 *     → GET .../content serves bytes whose sha-256 IS #2 (end to end).
 *
 * Plus the honest negatives: fail-closed rights (mismatched policy id),
 * the pre-storage container refusal, the uniform 404 for a non-owner, the
 * 401 for anonymous callers, and full HTTP Range semantics on playback.
 */
import { beforeAll, afterAll, describe, expect, test } from "bun:test";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createDeterministicTestHasher } from "@sporta/identity";
import { generateTestMp4, LocalFilesystemStorage, sha256OfBytes } from "@sporta/media-platform";
import { createSportaServer, installSportaServerForTests } from "../src/server/composition";
import type { SportaServer } from "../src/server/composition";
import { SPORTA_SESSION_COOKIE } from "../src/server/auth-service";
import { InMemoryRedis } from "../src/server/platform/upstash/redis";
import { POST as uploadRoute } from "../src/app/api/media/uploads/route";
import { GET as jobRoute } from "../src/app/api/media/jobs/[jobId]/route";
import { GET as assetRoute } from "../src/app/api/media/assets/[assetId]/route";
import { GET as artifactRoute } from "../src/app/api/media/artifacts/[artifactId]/route";
import { GET as contentRoute } from "../src/app/api/media/artifacts/[artifactId]/content/route";
import { POST as createSessionRoute } from "../src/app/api/create/sessions/route";

/** A deterministic stepping clock (the repo's hermetic rig). */
function steppingClock(): () => number {
  let current = 1_777_777_777_000;
  return () => {
    current += 17;
    return current;
  };
}

function withCookie(token: string | null, path: string, init: RequestInit = {}): Request {
  return new Request(`http://sporta.test${path}`, {
    ...init,
    headers: {
      ...((init.headers as Record<string, string> | undefined) ?? {}),
      ...(token === null ? {} : { cookie: `${SPORTA_SESSION_COOKIE}=${token}` }),
    },
  });
}

async function bodyOf(response: Response): Promise<Record<string, unknown>> {
  return (await response.json()) as Record<string, unknown>;
}

/** The studio-session creation body (transformation allowed — the pipeline gate). */
function post(payload: unknown): RequestInit {
  return {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(payload),
  };
}

/** Builds one real MP4 upload request (multipart, like a browser form). */
function uploadRequest(
  token: string | null,
  bytes: Uint8Array,
  sessionId: string,
  declaredRightsPolicyId: string,
): Request {
  const form = new FormData();
  form.append(
    "file",
    new File([bytes.slice().buffer as ArrayBuffer], "clip.mp4", { type: "video/mp4" }),
  );
  form.append("sessionId", sessionId);
  form.append("declaredRightsPolicyId", declaredRightsPolicyId);
  return withCookie(token, "/api/media/uploads", { method: "POST", body: form });
}

let server: SportaServer;
let scratch = "";
let creatorToken = "";
let outsiderToken = "";
let sessionId = "";
let policyId = "";

beforeAll(async () => {
  scratch = await mkdtemp(join(tmpdir(), "sporta-media-loop-"));
  server = createSportaServer({
    nowMs: steppingClock(),
    passwordHasher: createDeterministicTestHasher(),
    transient: { redis: new InMemoryRedis(steppingClock()), provider: "in-memory" },
    seed: true,
    media: {
      db: ":memory:",
      storage: new LocalFilesystemStorage(join(scratch, "media-storage")),
    },
  });
  installSportaServerForTests(server);
  await server.ready;

  const registered = await server.auth.register({
    username: "media-loop-creator",
    password: "a-real-studio-password",
    roles: ["creator", "viewer"],
  });
  creatorToken = (await server.auth.issueSession({ userId: registered.userId })).token;
  const outsider = await server.auth.register({
    username: "media-loop-outsider",
    password: "another-real-password",
    roles: ["viewer"],
  });
  outsiderToken = (await server.auth.issueSession({ userId: outsider.userId })).token;

  // A real studio session (the creation-time rights attestation the upload
  // must reference; transformation is allowed so the pipeline may run).
  const created = await createSessionRoute(
    withCookie(
      creatorToken,
      "/api/create/sessions",
      post({
        sourceKey: "derby",
        operations: ["analysis", "transformation", "storage"],
      }),
    ),
  );
  expect(created.status).toBe(201);
  sessionId = ((await bodyOf(created)) as { sessionId: string }).sessionId;
  const policy = server.rightsPolicies.effectiveOf(sessionId);
  expect(policy).not.toBeNull();
  policyId = policy!.policyId;
});

afterAll(async () => {
  await rm(scratch, { recursive: true, force: true });
});

describe("the real-media loop (upload → job → manifest → artifact → playback)", () => {
  let assetId = "";
  let jobId = "";
  let artifactId = "";
  let manifestId = "";
  /** sha-256 of the UPLOADED bytes (chain link #1). */
  let uploadedHash = "";
  /** sha-256 of the ARTIFACT bytes (chain link #2 — the re-encode). */
  let artifactHash = "";
  let artifactByteSize = 0;
  let uploadedBytes = new Uint8Array(0);

  test("R101: a real browser upload stores a hash-verified SourceAsset and admits a job", async () => {
    // REAL MP4 bytes from the real ffmpeg (2s, 320x240@24, AAC audio).
    const clipPath = await generateTestMp4(join(scratch, "clip.mp4"), {
      durationSeconds: 2,
      withAudio: true,
    });
    uploadedBytes = new Uint8Array(await Bun.file(clipPath).arrayBuffer());
    uploadedHash = sha256OfBytes(uploadedBytes);

    const response = await uploadRoute(
      uploadRequest(creatorToken, uploadedBytes, sessionId, policyId),
    );
    expect(response.status).toBe(201);
    const body = (await bodyOf(response)) as {
      asset: {
        assetId: string;
        contentHash: string;
        uploadState: string;
        checksumVerified: boolean;
        container: string;
        durationMs: number;
        videoStreamCount: number;
        audioStreamCount: number;
        declaredRightsPolicyId: string;
      };
      job: { jobId: string; state: string; progress: number; stages: { stage: string }[] };
    };
    expect(body.asset.contentHash).toBe(uploadedHash);
    expect(body.asset.uploadState).toBe("stored");
    expect(body.asset.checksumVerified).toBe(true);
    expect(body.asset.container).toBe("mp4");
    expect(body.asset.videoStreamCount).toBeGreaterThanOrEqual(1);
    expect(body.asset.audioStreamCount).toBe(1);
    expect(body.asset.durationMs).toBeGreaterThanOrEqual(1900);
    expect(body.asset.declaredRightsPolicyId).toBe(policyId);
    assetId = body.asset.assetId;
    jobId = body.job.jobId;
    // The admitted job: queued, upload-complete already earned (it WAS).
    expect(["queued", "in-flight"]).toContain(body.job.state);
    expect(body.job.stages.map((stage) => stage.stage)).toContain("upload-complete");
  });

  test("R103: the job poll surface reports the REAL pipeline to terminal success", async () => {
    let terminal: Record<string, unknown> | null = null;
    const observedStates = new Set<string>();
    for (let attempt = 0; attempt < 400; attempt += 1) {
      const response = await jobRoute(withCookie(creatorToken, `/api/media/jobs/${jobId}`), {
        params: Promise.resolve({ jobId }),
      });
      expect(response.status).toBe(200);
      const job = await bodyOf(response);
      observedStates.add(job.state as string);
      if (job.terminal === true) {
        terminal = job;
        break;
      }
      await Bun.sleep(25);
    }
    expect(terminal).not.toBeNull();
    const done = terminal as {
      state: string;
      progress: number;
      result: { manifestId: string; artifactId: string };
      stages: { stage: string; fraction: number }[];
    };
    expect(done.state).toBe("succeeded");
    expect(done.progress).toBe(1);
    // The honest stage trail, in order, with derived fractions.
    expect(done.stages.map((stage) => stage.stage)).toEqual([
      "created",
      "upload-complete",
      "normalization-complete",
      "artifact-stored",
      "terminal",
    ]);
    expect(done.stages[1]!.fraction).toBeCloseTo(1 / 3, 5);
    expect(done.stages[2]!.fraction).toBeCloseTo(2 / 3, 5);
    expect(done.stages[3]!.fraction).toBe(1);
    expect(done.result.manifestId).toBeTruthy();
    expect(done.result.artifactId).toBeTruthy();
    manifestId = done.result.manifestId;
    artifactId = done.result.artifactId;
  });

  test("R102/R104: the asset surface carries the frozen manifest + artifact chain", async () => {
    const response = await assetRoute(withCookie(creatorToken, `/api/media/assets/${assetId}`), {
      params: Promise.resolve({ assetId }),
    });
    expect(response.status).toBe(200);
    const body = (await bodyOf(response)) as {
      asset: { contentHash: string; checksumVerified: boolean };
      manifest: {
        manifestId: string;
        contentHash: string;
        sourceAssetId: string;
        video: { codec: string; widthPx: number; heightPx: number };
        audio: { codec: string; sampleRateHz: number } | null;
        frameCount: number;
        durationMs: number;
      };
      jobs: { jobId: string; state: string; terminal: boolean }[];
    };
    expect(body.manifest.manifestId).toBe(manifestId);
    expect(body.manifest.sourceAssetId).toBe(assetId);
    // The canonical encoding is a REAL re-encode: different bytes.
    artifactHash = body.manifest.contentHash;
    expect(artifactHash).not.toBe(uploadedHash);
    expect(body.manifest.video.codec).toBe("h264");
    expect(body.manifest.video.widthPx).toBe(320);
    expect(body.manifest.video.heightPx).toBe(240);
    expect(body.manifest.audio?.codec).toBe("aac");
    expect(body.manifest.audio?.sampleRateHz).toBe(48000);
    expect(body.manifest.frameCount).toBeGreaterThanOrEqual(46);
    expect(body.manifest.durationMs).toBeGreaterThanOrEqual(1900);
    expect(body.jobs[0]!.state).toBe("succeeded");
  });

  test("R104: the artifact manifest is the honest original-reality record", async () => {
    const response = await artifactRoute(
      withCookie(creatorToken, `/api/media/artifacts/${artifactId}`),
      { params: Promise.resolve({ artifactId }) },
    );
    expect(response.status).toBe(200);
    const artifact = (await bodyOf(response)) as {
      artifactId: string;
      sessionId: string;
      reality: string;
      contentHash: string;
      byteSize: number;
      container: string;
      videoCodec: string;
      audioCodec: string | null;
      rendererId: string;
      swm: null;
      sourceAssetId: string;
      integrity: { algorithm: string; verified: boolean };
    };
    expect(artifact.reality).toBe("original");
    expect(artifact.sessionId).toBe(sessionId);
    expect(artifact.contentHash).toBe(artifactHash);
    expect(artifact.swm).toBe(null);
    expect(artifact.sourceAssetId).toBe(assetId);
    expect(artifact.rendererId).toBe("media-platform/normalize");
    expect(artifact.container).toBe("mp4");
    expect(artifact.videoCodec).toBe("h264");
    expect(artifact.audioCodec).toBe("aac");
    expect(artifact.integrity).toEqual({ algorithm: "sha256", verified: true });
    artifactByteSize = artifact.byteSize;
  });

  test("R104: the playback route serves the SAME bytes (hash-verified end to end)", async () => {
    const response = await contentRoute(
      withCookie(creatorToken, `/api/media/artifacts/${artifactId}/content`),
      { params: Promise.resolve({ artifactId }) },
    );
    expect(response.status).toBe(200);
    expect(response.headers.get("content-type")).toBe("video/mp4");
    expect(response.headers.get("accept-ranges")).toBe("bytes");
    expect(response.headers.get("content-length")).toBe(String(artifactByteSize));
    const served = new Uint8Array(await response.arrayBuffer());
    // THE END-TO-END PROOF: the served bytes hash to the artifact's
    // content address (upload → stored → normalized → artifact → playback).
    expect(sha256OfBytes(served)).toBe(artifactHash);
    expect(served.byteLength).toBe(artifactByteSize);
  });

  test("R104: Range requests answer 206 with correct Content-Range slices", async () => {
    const full = await contentRoute(
      withCookie(creatorToken, `/api/media/artifacts/${artifactId}/content`),
      { params: Promise.resolve({ artifactId }) },
    );
    const fullBytes = new Uint8Array(await full.arrayBuffer());

    const partial = await contentRoute(
      withCookie(creatorToken, `/api/media/artifacts/${artifactId}/content`, {
        headers: { range: "bytes=100-199" },
      }),
      { params: Promise.resolve({ artifactId }) },
    );
    expect(partial.status).toBe(206);
    expect(partial.headers.get("content-range")).toBe(`bytes 100-199/${artifactByteSize}`);
    expect(partial.headers.get("content-length")).toBe("100");
    const slice = new Uint8Array(await partial.arrayBuffer());
    expect(slice.byteLength).toBe(100);
    expect(slice).toEqual(fullBytes.slice(100, 200));

    // Open-ended range: from 500 to the last byte.
    const open = await contentRoute(
      withCookie(creatorToken, `/api/media/artifacts/${artifactId}/content`, {
        headers: { range: "bytes=500-" },
      }),
      { params: Promise.resolve({ artifactId }) },
    );
    expect(open.status).toBe(206);
    expect(open.headers.get("content-range")).toBe(
      `bytes 500-${artifactByteSize - 1}/${artifactByteSize}`,
    );

    // Suffix range: the last 64 bytes.
    const suffix = await contentRoute(
      withCookie(creatorToken, `/api/media/artifacts/${artifactId}/content`, {
        headers: { range: "bytes=-64" },
      }),
      { params: Promise.resolve({ artifactId }) },
    );
    expect(suffix.status).toBe(206);
    const suffixBytes = new Uint8Array(await suffix.arrayBuffer());
    expect(suffixBytes).toEqual(fullBytes.slice(artifactByteSize - 64));

    // Unsatisfiable range (start beyond the object): 416 with the proof.
    const unsat = await contentRoute(
      withCookie(creatorToken, `/api/media/artifacts/${artifactId}/content`, {
        headers: { range: `bytes=${artifactByteSize + 10}-` },
      }),
      { params: Promise.resolve({ artifactId }) },
    );
    expect(unsat.status).toBe(416);
    expect(unsat.headers.get("content-range")).toBe(`bytes */${artifactByteSize}`);
  });
});

describe("the honest negatives (fail-closed boundaries)", () => {
  test("a mismatched declared policy id refuses (403, nothing stored)", async () => {
    const clipPath = await generateTestMp4(join(scratch, "neg-1.mp4"), {
      durationSeconds: 1,
      withAudio: false,
    });
    const bytes = new Uint8Array(await Bun.file(clipPath).arrayBuffer());
    const response = await uploadRoute(
      uploadRequest(creatorToken, bytes, sessionId, "policy-that-does-not-match"),
    );
    expect(response.status).toBe(403);
    const body = await bodyOf(response);
    expect((body.error as { failureClass: string }).failureClass).toBe("rights-denied");
  });

  test("a non-mp4 container refuses BEFORE storage (400, the violated constraint)", async () => {
    const webm = new Uint8Array([0x1a, 0x45, 0xdf, 0xa3, 1, 2, 3, 4, 5, 6, 7, 8]);
    const response = await uploadRoute(uploadRequest(creatorToken, webm, sessionId, policyId));
    expect(response.status).toBe(400);
    const body = (await bodyOf(response)) as {
      error: { failureClass: string; details: { constraint: string } };
    };
    expect(body.error.failureClass).toBe("media-invalid");
    expect(body.error.details.constraint).toBe("container-not-mp4");
  });

  test("a session without a transformation allowance refuses (403)", async () => {
    // `sharing` derives a capability (session creation is admitted) but NOT
    // `canReferenceSourceFrames` — the media pipeline's fail-closed gate.
    const created = await createSessionRoute(
      withCookie(
        creatorToken,
        "/api/create/sessions",
        post({ sourceKey: "derby", operations: ["analysis", "sharing"] }),
      ),
    );
    expect(created.status).toBe(201);
    const analysisOnly = ((await bodyOf(created)) as { sessionId: string }).sessionId;
    const analysisPolicy = server.rightsPolicies.effectiveOf(analysisOnly)!;
    const clipPath = await generateTestMp4(join(scratch, "neg-2.mp4"), {
      durationSeconds: 1,
      withAudio: false,
    });
    const bytes = new Uint8Array(await Bun.file(clipPath).arrayBuffer());
    const response = await uploadRoute(
      uploadRequest(creatorToken, bytes, analysisOnly, analysisPolicy.policyId),
    );
    expect(response.status).toBe(403);
    const body = await bodyOf(response);
    expect((body.error as { failureClass: string }).failureClass).toBe("rights-denied");
  });

  test("a non-owner answers the uniform 404 on every media surface (no probing)", async () => {
    const clipPath = await generateTestMp4(join(scratch, "neg-3.mp4"), {
      durationSeconds: 1,
      withAudio: false,
    });
    const bytes = new Uint8Array(await Bun.file(clipPath).arrayBuffer());
    // The upload itself: the outsider does not own the session → 404-shaped
    // refusal (the identity gate's uniform denial).
    const upload = await uploadRoute(uploadRequest(outsiderToken, bytes, sessionId, policyId));
    expect(upload.status).toBe(403);

    // An unknown job/asset/artifact id answers the typed 404 even for the
    // owner; the outsider never learns existence.
    const job = await jobRoute(withCookie(outsiderToken, "/api/media/jobs/mjob-none"), {
      params: Promise.resolve({ jobId: "mjob-none" }),
    });
    expect(job.status).toBe(404);
    const asset = await assetRoute(withCookie(outsiderToken, "/api/media/assets/asset-none"), {
      params: Promise.resolve({ assetId: "asset-none" }),
    });
    expect(asset.status).toBe(404);
    const artifact = await artifactRoute(
      withCookie(outsiderToken, "/api/media/artifacts/art-none"),
      { params: Promise.resolve({ artifactId: "art-none" }) },
    );
    expect(artifact.status).toBe(404);
  });

  test("anonymous callers answer the real 401 on every media surface", async () => {
    const upload = await uploadRequest(null, new Uint8Array([1, 2, 3]), sessionId, policyId);
    const response = await uploadRoute(upload);
    expect(response.status).toBe(401);
    const job = await jobRoute(withCookie(null, "/api/media/jobs/x"), {
      params: Promise.resolve({ jobId: "x" }),
    });
    expect(job.status).toBe(401);
  });
});
