/**
 * THE J004 MULTI-REALITY CREATE TESTS — the ONE-submission render plan over
 * the FROZEN contract `docs/contracts/multi-reality-create.md`:
 *
 * - SUBMISSION SHAPE: the upload route's additive `realities` field accepts
 *   a JSON array of strings OR repeated form fields; "original" is NOT a
 *   selection (400 typed); unknown kinds are 400 typed; malformed JSON is
 *   400 typed; a malformed compute directive is 400 typed;
 * - ABSENCE = LEGACY BEHAVIOR: without the field the 201 answer carries NO
 *   render plan member and NO derived dispatch happens (byte-compatible
 *   with the R501 answer — the additive/backward-compatible rule);
 * - RENDER PLAN SEMANTICS: after the media job reaches its stored-original
 *   state, ONE render per selected derived reality dispatches through the
 *   SAME control-plane async surface (createRenderAsync → the W914 seam);
 *   each kind resolves through the composition's frozen producer map; ONE
 *   compute selection directive covers the whole plan; the 201 answer
 *   carries per-reality renderId/jobId/state;
 * - FAILURE ISOLATION: one reality refusing (producer-unavailable, compute
 *   refusal / rate-limit) NEVER silently cancels the others — each refusal
 *   surfaces with its typed failure class;
 * - DURABLE RESULT STATE rides the EXISTING job/render surfaces: the plan
 *   jobs appear in the session state, poll to real terminal states, and the
 *   catalog's availability states remain the single renderer-availability
 *   truth per reality (the ONE-SUBMISSION FOUR-REALITY journey);
 * - EXPLICIT NON-GOAL (verified by absence of change): the single-render
 *   POST /api/create/sessions/[sessionId]/renders route keeps working
 *   exactly as before (its own batteries pin it; nothing here re-shapes it).
 *
 * Every media byte is REAL (the in-test MP4 is generated by the real
 * ffmpeg), every job state is the control plane's own projection, and every
 * refusal is the platform's typed answer — never a simulated anything.
 */
import { beforeAll, afterAll, describe, expect, test } from "bun:test";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createDeterministicTestHasher } from "@sporta/identity";
import { generateTestMp4, LocalFilesystemStorage } from "@sporta/media-platform";
import { createSportaServer, installSportaServerForTests } from "../src/server/composition";
import type { SportaServer } from "../src/server/composition";
import { CreateStudioService } from "../src/server/create-studio-service";
import { SPORTA_SESSION_COOKIE } from "../src/server/auth-service";
import { RENDER_REQUESTS_QUOTA } from "../src/server/platform/upstash/hosted";
import { InMemoryRedis } from "../src/server/platform/upstash/redis";
import { POST as uploadSessionRoute } from "../src/app/api/create/upload-sessions/route";
import { GET as jobRoute } from "../src/app/api/create/sessions/[sessionId]/jobs/[jobId]/route";
import { GET as mediaJobRoute } from "../src/app/api/media/jobs/[jobId]/route";
import { GET as sessionStateRoute } from "../src/app/api/create/sessions/[sessionId]/route";
import { GET as artifactCatalogRoute } from "../src/app/api/catalog/sessions/[sessionId]/artifacts/route";

/** A deterministic stepping clock (the repo's hermetic rig). */
function steppingClock(): () => number {
  let current = 1_777_777_777_000;
  return () => {
    current += 17;
    return current;
  };
}

function withCookie(token: string | null, path: string, init: RequestInit = {}): Request {
  return new Request(`http://sporta.test${path}`, {
    ...init,
    headers: {
      ...((init.headers as Record<string, string> | undefined) ?? {}),
      ...(token === null ? {} : { cookie: `${SPORTA_SESSION_COOKIE}=${token}` }),
    },
  });
}

async function bodyOf(response: Response): Promise<Record<string, unknown>> {
  return (await response.json()) as Record<string, unknown>;
}

/** Builds one real MP4 upload request (multipart, like a browser form). */
function uploadRequest(
  token: string | null,
  bytes: Uint8Array,
  operations: string[],
  options: {
    realitiesJson?: string;
    realityFields?: string[];
    computeJson?: string;
    styleId?: string;
  } = {},
): Request {
  const form = new FormData();
  form.append(
    "file",
    new File([bytes.slice().buffer as ArrayBuffer], "clip.mp4", { type: "video/mp4" }),
  );
  form.append("operations", JSON.stringify(operations));
  if (options.realitiesJson !== undefined) form.append("realities", options.realitiesJson);
  for (const field of options.realityFields ?? []) form.append("realities", field);
  if (options.computeJson !== undefined) form.append("compute", options.computeJson);
  if (options.styleId !== undefined) form.append("styleId", options.styleId);
  return withCookie(token, "/api/create/upload-sessions", { method: "POST", body: form });
}

const FULL_OPERATIONS = ["analysis", "transformation", "derivativeGeneration", "storage"];

let server: SportaServer;
let scratch = "";
let creatorToken = "";

beforeAll(async () => {
  scratch = await mkdtemp(join(tmpdir(), "sporta-multi-reality-"));
  server = createSportaServer({
    nowMs: steppingClock(),
    passwordHasher: createDeterministicTestHasher(),
    transient: { redis: new InMemoryRedis(steppingClock()), provider: "in-memory" },
    seed: true,
    media: {
      db: ":memory:",
      storage: new LocalFilesystemStorage(join(scratch, "media-storage")),
    },
  });
  installSportaServerForTests(server);
  await server.ready;

  const registered = await server.auth.register({
    username: "multi-reality-creator",
    password: "a-real-studio-password",
    roles: ["creator", "viewer"],
  });
  creatorToken = (await server.auth.issueSession({ userId: registered.userId })).token;
});

afterAll(async () => {
  await rm(scratch, { recursive: true, force: true });
});

/** Polls one compute job (through the REAL route) to its terminal state. */
async function pollComputeJob(
  token: string,
  sessionId: string,
  jobId: string,
): Promise<Record<string, unknown>> {
  for (let attempt = 0; attempt < 400; attempt += 1) {
    const response = await jobRoute(
      withCookie(token, `/api/create/sessions/${sessionId}/jobs/${jobId}`),
      { params: Promise.resolve({ sessionId, jobId }) },
    );
    expect(response.status).toBe(200);
    const job = await bodyOf(response);
    if (job.completion !== undefined) return job;
    await Bun.sleep(25);
  }
  throw new Error(`compute job ${jobId} did not settle in the bounded poll`);
}

describe("J004 — the submission shape (route parse semantics)", () => {
  let clipBytes = new Uint8Array(0);

  test("the realities field accepts a JSON array of strings", async () => {
    const clipPath = await generateTestMp4(join(scratch, "clip.mp4"), {
      durationSeconds: 1,
      withAudio: false,
    });
    clipBytes = new Uint8Array(await Bun.file(clipPath).arrayBuffer());

    const response = await uploadSessionRoute(
      uploadRequest(creatorToken, clipBytes, FULL_OPERATIONS, {
        realitiesJson: JSON.stringify(["tactical", "anime-npr"]),
        computeJson: JSON.stringify({ mode: "sporta-auto" }),
      }),
    );
    expect(response.status).toBe(201);
    const body = (await bodyOf(response)) as {
      renderPlan?: { realities: { reality: string; disposition: string }[] };
    };
    expect(body.renderPlan).toBeDefined();
    expect(body.renderPlan!.realities.map((entry) => entry.reality)).toEqual([
      "tactical",
      "anime-npr",
    ]);
    for (const entry of body.renderPlan!.realities) {
      expect(entry.disposition).toBe("admitted");
    }
  });

  test("the realities field accepts repeated form fields", async () => {
    const response = await uploadSessionRoute(
      uploadRequest(creatorToken, clipBytes, FULL_OPERATIONS, {
        realityFields: ["tactical", "three-d-game", "anime-npr"],
      }),
    );
    expect(response.status).toBe(201);
    const body = (await bodyOf(response)) as {
      renderPlan?: { realities: { reality: string }[] };
    };
    expect(body.renderPlan).toBeDefined();
    expect(body.renderPlan!.realities.map((entry) => entry.reality).sort()).toEqual([
      "anime-npr",
      "tactical",
      "three-d-game",
    ]);
  });

  test("'original' is NOT a selection — the typed 400, nothing stored", async () => {
    const response = await uploadSessionRoute(
      uploadRequest(creatorToken, clipBytes, FULL_OPERATIONS, {
        realitiesJson: JSON.stringify(["original", "tactical"]),
      }),
    );
    expect(response.status).toBe(400);
    const body = (await bodyOf(response)) as { error: { failureClass: string; message: string } };
    expect(body.error.failureClass).toBe("validation");
    expect(body.error.message).toContain("original");
  });

  test("an unknown reality kind is the typed 400", async () => {
    const response = await uploadSessionRoute(
      uploadRequest(creatorToken, clipBytes, FULL_OPERATIONS, {
        realitiesJson: JSON.stringify(["tactical", "vr-prototype"]),
      }),
    );
    expect(response.status).toBe(400);
    const body = (await bodyOf(response)) as { error: { message: string } };
    expect(body.error.message).toContain("vr-prototype");
  });

  test("a malformed realities JSON array is the typed 400", async () => {
    const response = await uploadSessionRoute(
      uploadRequest(creatorToken, clipBytes, FULL_OPERATIONS, {
        realitiesJson: "[tactical,",
      }),
    );
    expect(response.status).toBe(400);
    const body = (await bodyOf(response)) as { error: { message: string } };
    expect(body.error.message).toContain("realities");
  });

  test("a malformed compute directive is the typed 400", async () => {
    const response = await uploadSessionRoute(
      uploadRequest(creatorToken, clipBytes, FULL_OPERATIONS, {
        realitiesJson: JSON.stringify(["tactical"]),
        computeJson: '{"mode":"wrong-mode"}',
      }),
    );
    expect(response.status).toBe(400);
    const body = (await bodyOf(response)) as { error: { message: string } };
    expect(body.error.message).toContain("compute");
  });
});

describe("J004 — absence of the field preserves today's behavior (legacy)", () => {
  test("no realities field → no renderPlan member, no derived dispatch, the session is the R501 answer", async () => {
    const clipPath = await generateTestMp4(join(scratch, "legacy.mp4"), {
      durationSeconds: 1,
      withAudio: false,
    });
    const bytes = new Uint8Array(await Bun.file(clipPath).arrayBuffer());
    const response = await uploadSessionRoute(uploadRequest(creatorToken, bytes, FULL_OPERATIONS));
    expect(response.status).toBe(201);
    const body = (await bodyOf(response)) as {
      sessionId: string;
      renderPlan?: unknown;
      source: { job: { jobId: string } | null };
      perception: { frameCount: number };
    };
    // The additive rule: the plan member is ABSENT (never null, never empty)
    // and the answer's shape is byte-compatible with the R501 upload answer.
    expect(body.renderPlan).toBeUndefined();
    expect(body.perception.frameCount).toBeGreaterThan(0);
    // The legacy posture: the media job runs (the original reality) but NO
    // compute job was dispatched for this session through the plan path.
    expect(body.source.job).not.toBeNull();
    const state = await bodyOf(
      await sessionStateRoute(withCookie(creatorToken, `/api/create/sessions/${body.sessionId}`), {
        params: Promise.resolve({ sessionId: body.sessionId }),
      }),
    );
    expect((state as { jobs: unknown[] }).jobs).toEqual([]);
  });
});

describe("J004 — the ONE-submission four-reality journey (render plan semantics)", () => {
  let sessionId = "";
  let planJobIds: string[] = [];
  let providerId = "";

  test("ONE submission with all three derived realities produces ONE plan under ONE compute directive", async () => {
    providerId = server.selection?.providerId ?? "";
    expect(server.selection).not.toBeNull();
    const clipPath = await generateTestMp4(join(scratch, "four-realities.mp4"), {
      durationSeconds: 1,
      withAudio: false,
    });
    const bytes = new Uint8Array(await Bun.file(clipPath).arrayBuffer());

    const response = await uploadSessionRoute(
      uploadRequest(creatorToken, bytes, FULL_OPERATIONS, {
        realitiesJson: JSON.stringify(["tactical", "three-d-game", "anime-npr"]),
        computeJson: JSON.stringify({ mode: "user-explicit", providerId }),
        styleId: "one-submission",
      }),
    );
    expect(response.status).toBe(201);
    const body = (await bodyOf(response)) as {
      sessionId: string;
      renderPlan: {
        realities: {
          reality: string;
          rendererId: string | null;
          disposition: string;
          jobId?: string;
          jobState?: string;
        }[];
        selection?: { providerId: string; mode: string };
      };
      source: { job: { jobId: string } | null };
      perception: { frameCount: number; summary: string };
    };
    sessionId = body.sessionId;

    // The frozen producer map resolves each kind (verbatim producer ids).
    const byReality = new Map(body.renderPlan.realities.map((entry) => [entry.reality, entry]));
    expect(byReality.get("tactical")!.rendererId).toBe("tactical.prototype");
    expect(byReality.get("three-d-game")!.rendererId).toBe("game-3d.prototype");
    expect(byReality.get("anime-npr")!.rendererId).toBe("anime-npr.prototype");
    for (const entry of body.renderPlan.realities) {
      expect(entry.disposition).toBe("admitted");
      expect(entry.jobId).toBeTruthy();
      expect(entry.jobState).toBeTruthy();
    }
    planJobIds = body.renderPlan.realities
      .map((entry) => entry.jobId!)
      .filter((jobId) => jobId !== undefined);

    // ONE compute selection covered the whole plan (the user's explicit
    // choice, the same provider for every dispatch — no per-reality
    // re-selection).
    expect(body.renderPlan.selection).toBeDefined();
    expect(body.renderPlan.selection!.providerId).toBe(providerId);
    expect(body.renderPlan.selection!.mode).toBe("user-explicit");

    // The honest perception summary rides unchanged.
    expect(body.perception.frameCount).toBeGreaterThan(0);

    // The media job is ALREADY settled (the plan dispatched only after the
    // stored-original state — the contract's sequencing).
    expect(body.source.job).not.toBeNull();
    const mediaView = await bodyOf(
      await mediaJobRoute(withCookie(creatorToken, `/api/media/jobs/${body.source.job!.jobId}`), {
        params: Promise.resolve({ jobId: body.source.job!.jobId }),
      }),
    );
    expect((mediaView as { state: string }).state).toBe("succeeded");
  });

  test("each plan job is a REAL compute job on the EXISTING surface (session state + poll)", async () => {
    const state = (await bodyOf(
      await sessionStateRoute(withCookie(creatorToken, `/api/create/sessions/${sessionId}`), {
        params: Promise.resolve({ sessionId }),
      }),
    )) as { jobs: { jobId: string; rendererId: string | null }[] };
    // The plan's jobs ride the studio's EXISTING session-state surface.
    const stateJobIds = state.jobs.map((job) => job.jobId);
    for (const jobId of planJobIds) {
      expect(stateJobIds).toContain(jobId);
    }
    expect(state.jobs.map((job) => job.rendererId).sort()).toEqual([
      "anime-npr.prototype",
      "game-3d.prototype",
      "tactical.prototype",
    ]);
    // Poll each to terminal success (real renders through the W914 seam).
    for (const jobId of planJobIds) {
      const done = (await pollComputeJob(creatorToken, sessionId, jobId)) as {
        state: string;
        renderId: string;
        completion: { status: string; outputs: { artifactId: string; contentType: string }[] };
        selection: { providerId: string; mode: string };
      };
      expect(done.state).toBe("succeeded");
      expect(done.completion.status).toBe("succeeded");
      expect(done.renderId).toBeTruthy();
      expect(done.completion.outputs.length).toBeGreaterThan(0);
      for (const output of done.completion.outputs) {
        expect(output.contentType).toBe("video/mp4+base64");
      }
      // The SAME one selection rode every dispatch (verified per job).
      expect(done.selection.providerId).toBe(providerId);
      expect(done.selection.mode).toBe("user-explicit");
    }
  });

  test("the catalog's availability states remain the single truth: ALL FOUR realities ready", async () => {
    const catalog = (await bodyOf(
      await artifactCatalogRoute(
        withCookie(creatorToken, `/api/catalog/sessions/${sessionId}/artifacts`),
        { params: Promise.resolve({ sessionId }) },
      ),
    )) as {
      realities: { kind: string; availability: string }[] | null;
      readyRealityCount: number;
    };
    expect(catalog.realities).not.toBeNull();
    const byKind = new Map(catalog.realities!.map((entry) => [entry.kind, entry]));
    expect(byKind.get("original")!.availability).toBe("ready");
    expect(byKind.get("tactical")!.availability).toBe("ready");
    expect(byKind.get("three-d-game")!.availability).toBe("ready");
    expect(byKind.get("anime-npr")!.availability).toBe("ready");
    expect(catalog.readyRealityCount).toBe(4);
  });
});

describe("J004 — per-reality failure isolation (honest, independent, typed)", () => {
  let clipBytes = new Uint8Array(0);

  beforeAll(async () => {
    const clipPath = await generateTestMp4(join(scratch, "isolation.mp4"), {
      durationSeconds: 1,
      withAudio: false,
    });
    clipBytes = new Uint8Array(await Bun.file(clipPath).arrayBuffer());
  });

  test("a producer-unavailable reality fails ALONE — the others still dispatch", async () => {
    // A studio service wired with an EMPTY producer map over the SAME real
    // server: every kind is honestly producer-unavailable on it — the exact
    // posture of a control plane whose derived-reality encode plane did not
    // compose. The upload + media job still run (the composition is real).
    const producerless = new CreateStudioService({
      getServer: () => server,
      engines: new Map(),
      storyIndex: new Map(),
      publication: {
        set: () => undefined,
        visibilityOf: () => "public" as const,
      },
      attestations: { record: () => undefined },
      operations: { noteAdmissionRefusal: () => undefined },
      derivedRealityProducers: new Map(),
      nowMs: steppingClock(),
    });
    const account = await server.auth.resolve(creatorToken);
    expect(account).not.toBeNull();
    const view = await producerless.createUploadSession({
      token: creatorToken,
      bytes: clipBytes,
      declaration: { operations: FULL_OPERATIONS },
      realities: ["tactical", "three-d-game", "anime-npr"],
      compute: { mode: "sporta-auto" },
    });
    expect(view.renderPlan).toBeDefined();
    expect(view.renderPlan!.realities).toHaveLength(3);
    for (const entry of view.renderPlan!.realities) {
      expect(entry.disposition).toBe("failed");
      expect(entry.rendererId).toBeNull();
      expect(entry.failure).toBeDefined();
      expect(entry.failure!.errorClass).toBe("producer-unavailable");
    }
    // The upload itself still succeeded (the plan's refusals are NOT the
    // upload's failure) — the session exists with its asset + media job.
    expect(view.source.asset.uploadState).toBe("stored");
    expect(view.source.job).not.toBeNull();
  });

  test("a rate-limited reality fails with its typed class while an earlier one still admitted", async () => {
    // Exhaust the render-request quota for a FRESH account down to exactly
    // one remaining unit: the plan's FIRST dispatch consumes it (admitted);
    // the second and third refuse with the platform's typed rate-limited
    // class — honest isolation, never a silent plan-wide cancellation.
    const registered = await server.auth.register({
      username: "multi-reality-quota",
      password: "another-real-password",
      roles: ["creator", "viewer"],
    });
    const quotaToken = (await server.auth.issueSession({ userId: registered.userId })).token;
    for (let consumed = 0; consumed < RENDER_REQUESTS_QUOTA.limit - 1; consumed += 1) {
      const outcome = await server.transientState.quotas.consume(
        RENDER_REQUESTS_QUOTA,
        registered.userId,
      );
      expect(outcome.allowed).toBe(true);
    }

    const response = await uploadSessionRoute(
      uploadRequest(quotaToken, clipBytes, FULL_OPERATIONS, {
        realitiesJson: JSON.stringify(["tactical", "three-d-game", "anime-npr"]),
        computeJson: JSON.stringify({ mode: "sporta-auto" }),
      }),
    );
    expect(response.status).toBe(201);
    const body = (await bodyOf(response)) as {
      renderPlan: {
        realities: {
          reality: string;
          disposition: string;
          jobId?: string;
          failure?: { errorClass: string; message: string };
        }[];
      };
    };
    const entries = body.renderPlan.realities;
    expect(entries).toHaveLength(3);
    const admitted = entries.filter((entry) => entry.disposition === "admitted");
    const refused = entries.filter((entry) => entry.disposition === "failed");
    // One admitted (the last quota unit), two refused — isolation proven.
    expect(admitted).toHaveLength(1);
    expect(refused).toHaveLength(2);
    expect(admitted[0]!.jobId).toBeTruthy();
    for (const entry of refused) {
      expect(entry.failure).toBeDefined();
      expect(entry.failure!.errorClass).toBe("rate-limited");
      expect(entry.jobId).toBeUndefined();
    }
  });

  test("a refused compute directive surfaces its typed class on every entry (the plan-level refusal)", async () => {
    const response = await uploadSessionRoute(
      uploadRequest(creatorToken, clipBytes, FULL_OPERATIONS, {
        realitiesJson: JSON.stringify(["tactical", "anime-npr"]),
        computeJson: JSON.stringify({ mode: "user-explicit", providerId: "no-such-provider" }),
      }),
    );
    expect(response.status).toBe(201);
    const body = (await bodyOf(response)) as {
      renderPlan: {
        realities: { disposition: string; jobId?: string; failure?: { errorClass: string } }[];
        selection?: unknown;
      };
    };
    for (const entry of body.renderPlan.realities) {
      expect(entry.disposition).toBe("failed");
      expect(entry.failure).toBeDefined();
      // The director's typed refusal class (the platform's own vocabulary).
      expect(["resource-limit", "media-invalid", "internal"]).toContain(entry.failure!.errorClass);
      expect(entry.jobId).toBeUndefined();
    }
    // No selection was recorded (nothing was admitted under the directive).
    expect(body.renderPlan.selection).toBeUndefined();
  });
});
