/**
 * THE STUDIO UPLOAD FLOW TEST (R501 + R503) — the hermetic route-level
 * proof of the REAL creation path, following the media-loop pattern
 * exactly: real route handlers over a real composed server (deterministic
 * hasher, in-memory transient state, the real dev seed, the media seams
 * injected), with EVERY media byte REAL — the in-test MP4 is generated by
 * the real ffmpeg (`generateTestMp4`), never a committed fixture.
 *
 * THE R501 CYCLE (upload → rights → compute → render, every seam REAL):
 *
 *   POST /api/create/upload-sessions (multipart: the real MP4 + the rights
 *     declaration) → 201: the session + the durable hash-verified
 *     SourceAsset + the admitted media job + the honest R207 perception
 *     summary (the session's world model is derived from the UPLOADED
 *     clip's frames);
 *   POST /api/create/compute-preview → 200: the REAL SelectionDirector's
 *     selection + the auditable explanation (auto AND explicit; an
 *     explicit UNKNOWN provider → the typed 422 refusal with reasons);
 *   POST .../renders with the compute directive → 202: the dispatch
 *     verified the same selection (the explanation rides in the answer);
 *   poll the compute job → succeeded (real renderer + real W504 store);
 *   poll the media job → succeeded (real normalization + the
 *     original-reality artifact);
 *   GET /api/create/sessions/[id] (the "refresh") → the PERSISTENT source
 *     state visible: the asset (stored, checksum-verified) + the job
 *     (succeeded) + the artifact.
 *
 * THE R503 CATALOG: GET /api/catalog/sessions/[id]/artifacts links ALL
 * FOUR realities for the one session through the real stores — original
 * READY (the media artifact: manifest link + integrity hash), anime-npr
 * READY (the render's stored W504 output), tactical + 3D honestly
 * producer-unavailable (no registered producer — never invented). A
 * playback-denied session reveals NOTHING (realities: null — the W916
 * posture), and a non-discoverable caller gets the uniform 404.
 *
 * THE HONEST NEGATIVES: a non-mp4 container is refused typed BEFORE
 * anything is stored (400, container-not-mp4); an anonymous caller gets
 * the real 401; a non-owner gets the uniform denial.
 */
import { beforeAll, afterAll, describe, expect, test } from "bun:test";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createDeterministicTestHasher } from "@sporta/identity";
import { generateTestMp4, LocalFilesystemStorage, sha256OfBytes } from "@sporta/media-platform";
import { createSportaServer, installSportaServerForTests } from "../src/server/composition";
import type { SportaServer } from "../src/server/composition";
import { SPORTA_SESSION_COOKIE } from "../src/server/auth-service";
import { InMemoryRedis } from "../src/server/platform/upstash/redis";
import { POST as uploadSessionRoute } from "../src/app/api/create/upload-sessions/route";
import { POST as computePreviewRoute } from "../src/app/api/create/compute-preview/route";
import { POST as renderRoute } from "../src/app/api/create/sessions/[sessionId]/renders/route";
import { GET as sessionStateRoute } from "../src/app/api/create/sessions/[sessionId]/route";
import { GET as jobRoute } from "../src/app/api/create/sessions/[sessionId]/jobs/[jobId]/route";
import { GET as mediaJobRoute } from "../src/app/api/media/jobs/[jobId]/route";
import { GET as artifactCatalogRoute } from "../src/app/api/catalog/sessions/[sessionId]/artifacts/route";

/** A deterministic stepping clock (the repo's hermetic rig). */
function steppingClock(): () => number {
  let current = 1_888_888_888_000;
  return () => {
    current += 17;
    return current;
  };
}

function withCookie(token: string | null, path: string, init: RequestInit = {}): Request {
  return new Request(`http://sporta.test${path}`, {
    ...init,
    headers: {
      ...((init.headers as Record<string, string> | undefined) ?? {}),
      ...(token === null ? {} : { cookie: `${SPORTA_SESSION_COOKIE}=${token}` }),
    },
  });
}

async function bodyOf(response: Response): Promise<Record<string, unknown>> {
  return (await response.json()) as Record<string, unknown>;
}

function jsonPost(payload: unknown): RequestInit {
  return {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(payload),
  };
}

/** Builds one real MP4 upload request (multipart, like a browser form). */
function uploadSessionRequest(
  token: string | null,
  bytes: Uint8Array,
  operations: string[],
  filename = "clip.mp4",
): Request {
  const form = new FormData();
  form.append(
    "file",
    new File([bytes.slice().buffer as ArrayBuffer], filename, { type: "video/mp4" }),
  );
  form.append("operations", JSON.stringify(operations));
  return withCookie(token, "/api/create/upload-sessions", { method: "POST", body: form });
}

let server: SportaServer;
let scratch = "";
let creatorToken = "";
let outsiderToken = "";

beforeAll(async () => {
  scratch = await mkdtemp(join(tmpdir(), "sporta-studio-upload-"));
  server = createSportaServer({
    nowMs: steppingClock(),
    passwordHasher: createDeterministicTestHasher(),
    transient: { redis: new InMemoryRedis(steppingClock()), provider: "in-memory" },
    seed: true,
    media: {
      db: ":memory:",
      storage: new LocalFilesystemStorage(join(scratch, "media-storage")),
    },
  });
  installSportaServerForTests(server);
  await server.ready;

  const registered = await server.auth.register({
    username: "studio-upload-creator",
    password: "a-real-studio-password",
    roles: ["creator", "viewer"],
  });
  creatorToken = (await server.auth.issueSession({ userId: registered.userId })).token;
  const outsider = await server.auth.register({
    username: "studio-upload-outsider",
    password: "another-real-password",
    roles: ["viewer"],
  });
  outsiderToken = (await server.auth.issueSession({ userId: outsider.userId })).token;
});

afterAll(async () => {
  await rm(scratch, { recursive: true, force: true });
});

describe("the studio's real upload flow (R501: upload → rights → compute → render)", () => {
  let uploadedBytes = new Uint8Array(0);
  let uploadedHash = "";
  /** The storage-allowing session (the full cycle). */
  let sessionId = "";
  let mediaJobId = "";
  let computeJobId = "";
  /** The playback-denied session (the W916 posture). */
  let deniedSessionId = "";

  test("R501-a: a real browser upload becomes a session with a durable source + a perception run", async () => {
    const clipPath = await generateTestMp4(join(scratch, "clip.mp4"), {
      durationSeconds: 2,
      withAudio: true,
    });
    uploadedBytes = new Uint8Array(await Bun.file(clipPath).arrayBuffer());
    uploadedHash = sha256OfBytes(uploadedBytes);

    const response = await uploadSessionRoute(
      uploadSessionRequest(creatorToken, uploadedBytes, [
        "analysis",
        "transformation",
        "derivativeGeneration",
        "storage",
      ]),
    );
    expect(response.status).toBe(201);
    const body = (await bodyOf(response)) as {
      sessionId: string;
      rightsCapabilities: { canReferenceSourceFrames: boolean; canStoreDerivatives: boolean };
      source: {
        asset: {
          assetId: string;
          contentHash: string;
          uploadState: string;
          checksumVerified: boolean;
          container: string;
          durationMs: number;
        };
        job: { jobId: string; state: string; terminal: boolean } | null;
        artifact: unknown;
      };
      perception: {
        frameCount: number;
        snapshotCount: number;
        eventCount: number;
        degradationCount: number;
        summary: string;
      };
    };
    sessionId = body.sessionId;
    // The R101 boundary's own records, verbatim.
    expect(body.source.asset.contentHash).toBe(uploadedHash);
    expect(body.source.asset.uploadState).toBe("stored");
    expect(body.source.asset.checksumVerified).toBe(true);
    expect(body.source.asset.container).toBe("mp4");
    expect(body.source.asset.durationMs).toBeGreaterThanOrEqual(1900);
    // The rights derivation the studio previewed, fail-closed.
    expect(body.rightsCapabilities.canReferenceSourceFrames).toBe(true);
    expect(body.rightsCapabilities.canStoreDerivatives).toBe(true);
    // The admitted media job (the normalization pipeline).
    expect(body.source.job).not.toBeNull();
    expect(["queued", "in-flight", "succeeded"]).toContain(body.source.job!.state);
    mediaJobId = body.source.job!.jobId;
    // The honest R207 perception summary: the session's world model came
    // from the UPLOADED clip's 48 real decoded frames.
    expect(body.perception.frameCount).toBe(48);
    expect(body.perception.snapshotCount).toBeGreaterThanOrEqual(1);
    expect(body.perception.summary.length).toBeGreaterThan(0);
  });

  test("R501-b: a playback-denying declaration still uploads (transformation allowed) — the W916 posture session", async () => {
    const response = await uploadSessionRoute(
      uploadSessionRequest(creatorToken, uploadedBytes, ["analysis", "transformation"]),
    );
    expect(response.status).toBe(201);
    const body = (await bodyOf(response)) as {
      sessionId: string;
      rightsCapabilities: { canStoreDerivatives: boolean };
    };
    deniedSessionId = body.sessionId;
    expect(body.rightsCapabilities.canStoreDerivatives).toBe(false);
  });

  test("R501-c: the compute step runs the REAL SelectionDirector (auto + explicit + typed refusal)", async () => {
    const providerId = server.selection?.providerId ?? "";
    expect(server.selection).not.toBeNull();

    // Auto: the deterministic policy order, explained.
    const auto = await computePreviewRoute(
      withCookie(
        creatorToken,
        "/api/create/compute-preview",
        jsonPost({
          rendererId: "anime.prototype",
          latencyClass: "offline",
          compute: { mode: "sporta-auto", preference: { privacyPosture: "privacy-any" } },
        }),
      ),
    );
    expect(auto.status).toBe(200);
    const autoBody = (await bodyOf(auto)) as {
      selection: { providerId: string };
      explanation: {
        mode: string;
        selectedProviderId: string;
        selectionReason: string;
        considered: { providerId: string; quote?: { estimatedCostUsd: number | null } }[];
      };
    };
    expect(autoBody.selection.providerId).toBe(providerId);
    expect(autoBody.explanation.selectedProviderId).toBe(providerId);
    expect(autoBody.explanation.selectionReason).toContain("registration order");
    expect(autoBody.explanation.considered).toHaveLength(1);
    expect(autoBody.explanation.considered[0]!.providerId).toBe(providerId);

    // Explicit on the registered provider: the user's choice wins.
    const explicit = await computePreviewRoute(
      withCookie(
        creatorToken,
        "/api/create/compute-preview",
        jsonPost({
          rendererId: "anime.prototype",
          latencyClass: "offline",
          compute: { mode: "user-explicit", providerId },
        }),
      ),
    );
    expect(explicit.status).toBe(200);
    const explicitBody = (await bodyOf(explicit)) as { selection: { providerId: string } };
    expect(explicitBody.selection.providerId).toBe(providerId);

    // Explicit on an UNKNOWN provider: the typed refusal, never a fallback.
    const refused = await computePreviewRoute(
      withCookie(
        creatorToken,
        "/api/create/compute-preview",
        jsonPost({
          rendererId: "anime.prototype",
          latencyClass: "offline",
          compute: { mode: "user-explicit", providerId: "no-such-provider" },
        }),
      ),
    );
    expect(refused.status).toBe(422);
    const refusedBody = (await bodyOf(refused)) as {
      error: { failureClass: string; details: { refusals: unknown[] } };
    };
    expect(refusedBody.error.details.refusals.length).toBeGreaterThan(0);
  });

  test("R501-d: the render dispatch verifies the selection and executes the real job to success", async () => {
    const providerId = server.selection?.providerId ?? "";
    const dispatch = await renderRoute(
      withCookie(
        creatorToken,
        `/api/create/sessions/${sessionId}/renders`,
        jsonPost({
          rendererId: "anime.prototype",
          styleId: "upload-flow-test",
          compute: { mode: "user-explicit", providerId },
        }),
      ),
      { params: Promise.resolve({ sessionId }) },
    );
    expect(dispatch.status).toBe(202);
    const dispatchBody = (await bodyOf(dispatch)) as {
      disposition: string;
      jobId: string;
      adapterId: string;
      jobState: string;
      selection: { providerId: string; mode: string; explanation: { selectedProviderId: string } };
    };
    expect(dispatchBody.disposition).toBe("admitted");
    expect(dispatchBody.selection.providerId).toBe(providerId);
    expect(dispatchBody.selection.mode).toBe("user-explicit");
    expect(dispatchBody.selection.explanation.selectedProviderId).toBe(providerId);
    computeJobId = dispatchBody.jobId;

    // Poll the REAL compute projection to terminal success.
    let terminal: Record<string, unknown> | null = null;
    for (let attempt = 0; attempt < 400; attempt += 1) {
      const response = await jobRoute(
        withCookie(creatorToken, `/api/create/sessions/${sessionId}/jobs/${computeJobId}`),
        { params: Promise.resolve({ sessionId, jobId: computeJobId }) },
      );
      expect(response.status).toBe(200);
      const job = await bodyOf(response);
      if (job.completion !== undefined) {
        terminal = job;
        break;
      }
      await Bun.sleep(25);
    }
    expect(terminal).not.toBeNull();
    const done = terminal as {
      state: string;
      renderId: string;
      completion: { status: string; outputs: { artifactId: string }[] };
    };
    expect(done.state).toBe("succeeded");
    expect(done.completion.status).toBe("succeeded");
    expect(done.renderId).toBeTruthy();
    expect(done.completion.outputs.length).toBeGreaterThan(0);
  });

  test("R501-e: the media pipeline stores the original artifact (the R103 honest states)", async () => {
    let terminal: Record<string, unknown> | null = null;
    for (let attempt = 0; attempt < 400; attempt += 1) {
      const response = await mediaJobRoute(
        withCookie(creatorToken, `/api/media/jobs/${mediaJobId}`),
        { params: Promise.resolve({ jobId: mediaJobId }) },
      );
      expect(response.status).toBe(200);
      const job = await bodyOf(response);
      if (job.terminal === true) {
        terminal = job;
        break;
      }
      await Bun.sleep(25);
    }
    expect(terminal).not.toBeNull();
    const done = terminal as {
      state: string;
      result: { manifestId: string; artifactId: string };
    };
    expect(done.state).toBe("succeeded");
    expect(done.result.artifactId).toBeTruthy();
  });

  test("R501-f: a fresh read (the refresh) sees the PERSISTENT source state", async () => {
    const response = await sessionStateRoute(
      withCookie(creatorToken, `/api/create/sessions/${sessionId}`),
      { params: Promise.resolve({ sessionId }) },
    );
    expect(response.status).toBe(200);
    const state = (await bodyOf(response)) as {
      source: {
        kind: string;
        asset: { contentHash: string; uploadState: string; checksumVerified: boolean };
        job: { state: string; terminal: boolean } | null;
        artifact: { artifactId: string; reality: string } | null;
      };
    };
    expect(state.source.kind).toBe("upload");
    expect(state.source.asset.contentHash).toBe(uploadedHash);
    expect(state.source.asset.uploadState).toBe("stored");
    expect(state.source.asset.checksumVerified).toBe(true);
    expect(state.source.job?.terminal).toBe(true);
    expect(state.source.artifact?.reality).toBe("original");
  });

  test("R503: the artifact catalog links ALL FOUR realities for the one session (real stores only)", async () => {
    const response = await artifactCatalogRoute(
      withCookie(creatorToken, `/api/catalog/sessions/${sessionId}/artifacts`),
      { params: Promise.resolve({ sessionId }) },
    );
    expect(response.status).toBe(200);
    const catalog = (await bodyOf(response)) as {
      playback: { state: string; reasonCode: string };
      realities:
        | {
            kind: string;
            availability: string;
            reason: string;
            artifacts: {
              artifactId: string;
              kind: string;
              manifestLink: string;
              integrityHash: string;
              byteSize: number;
            }[];
          }[]
        | null;
      readyRealityCount: number;
    };
    expect(catalog.playback.state).toBe("authorized");
    expect(catalog.realities).not.toBeNull();
    expect(catalog.realities!.map((entry) => entry.kind)).toEqual([
      "original",
      "tactical",
      "three-d-game",
      "anime-npr",
    ]);
    const byKind = new Map(catalog.realities!.map((entry) => [entry.kind, entry]));

    // original: the REAL media artifact (manifest link + integrity hash).
    const original = byKind.get("original")!;
    expect(original.availability).toBe("ready");
    expect(original.artifacts.length).toBe(1);
    expect(original.artifacts[0]!.integrityHash).toMatch(/^[0-9a-f]{64}$/);
    expect(original.artifacts[0]!.manifestLink).toContain("/api/media/artifacts/");

    // anime-npr: the REAL render output (the W504 store's segment).
    const anime = byKind.get("anime-npr")!;
    expect(anime.availability).toBe("ready");
    expect(anime.artifacts.length).toBeGreaterThan(0);
    expect(anime.artifacts[0]!.manifestLink).toContain("/watch/");
    expect(anime.artifacts[0]!.integrityHash).toMatch(/^[0-9a-f]{64}$/);

    // tactical + 3D: producers are REGISTERED (R508-R510's derived-reality
    // plane composes when the real ffmpeg toolchain is present) but no
    // render has been dispatched for them — the honest requires-render,
    // never invented artifacts.
    expect(byKind.get("tactical")!.availability).toBe("requires-render");
    expect(byKind.get("tactical")!.artifacts).toHaveLength(0);
    expect(byKind.get("three-d-game")!.availability).toBe("requires-render");
    expect(byKind.get("three-d-game")!.artifacts).toHaveLength(0);

    expect(catalog.readyRealityCount).toBe(2);
  });

  test("R503 (W916 posture): a playback-denied session reveals NOTHING (realities: null)", async () => {
    const response = await artifactCatalogRoute(
      withCookie(creatorToken, `/api/catalog/sessions/${deniedSessionId}/artifacts`),
      { params: Promise.resolve({ sessionId: deniedSessionId }) },
    );
    expect(response.status).toBe(200);
    const catalog = (await bodyOf(response)) as {
      playback: { state: string; reasonCode: string };
      realities: unknown;
      readyRealityCount: unknown;
    };
    expect(catalog.playback.state).toBe("denied");
    expect(catalog.playback.reasonCode).toBe("rights-denied");
    expect(catalog.realities).toBeNull();
    expect(catalog.readyRealityCount).toBeNull();
  });

  test("R503 (no existence oracle): a non-discoverable caller gets the uniform unknown-session 404", async () => {
    const response = await artifactCatalogRoute(
      withCookie(outsiderToken, `/api/catalog/sessions/${sessionId}/artifacts`),
      { params: Promise.resolve({ sessionId }) },
    );
    expect(response.status).toBe(404);
    const first = (await bodyOf(response)) as {
      error: { failureClass: string };
    };
    expect(first.error.failureClass).toBe("unknown-session");
    // The same STATUS + failureClass as a truly unknown id — a caller can
    // never distinguish "exists but not yours" from "does not exist" (the
    // typed error body names the requested id in both cases; no 403-vs-404
    // distinction ever leaks).
    const unknown = await artifactCatalogRoute(
      withCookie(outsiderToken, "/api/catalog/sessions/sess-does-not-exist/artifacts"),
      { params: Promise.resolve({ sessionId: "sess-does-not-exist" }) },
    );
    expect(unknown.status).toBe(404);
    const second = (await bodyOf(unknown)) as {
      error: { failureClass: string };
    };
    expect(second.error.failureClass).toBe("unknown-session");
  });

  test("R501 negative: a non-mp4 container is refused typed BEFORE anything is stored", async () => {
    // A real WebM header (EBML magic) — the ingestion seam's own sniffer
    // classifies it; the R101 constraint refuses it.
    const webmBytes = new Uint8Array([
      0x1a, 0x45, 0xdf, 0xa3, 0x84, 0x42, 0x82, 0x84, 0x77, 0x65, 0x62, 0x6d, 0x00, 0x00, 0x00,
    ]);
    const response = await uploadSessionRoute(
      uploadSessionRequest(creatorToken, webmBytes, ["analysis", "transformation", "storage"]),
    );
    expect(response.status).toBe(400);
    const body = (await bodyOf(response)) as {
      error: { failureClass: string; message: string };
    };
    expect(body.error.failureClass).toBe("media-invalid");
    expect(body.error.message).toContain("mp4");
  });

  test("R501 negative: a declaration without transformation is refused (the pipeline references source frames)", async () => {
    const response = await uploadSessionRoute(
      uploadSessionRequest(creatorToken, uploadedBytes, ["analysis"]),
    );
    expect(response.status).toBe(400);
  });

  test("R501 negative: anonymous callers get the real 401", async () => {
    const response = await uploadSessionRoute(
      uploadSessionRequest(null, uploadedBytes, ["analysis", "transformation", "storage"]),
    );
    expect(response.status).toBe(401);
  });

  test("R501 negative: a non-owner's session read is the uniform denial", async () => {
    const response = await sessionStateRoute(
      withCookie(outsiderToken, `/api/create/sessions/${sessionId}`),
      { params: Promise.resolve({ sessionId }) },
    );
    expect([403, 404]).toContain(response.status);
  });
});
