/**
 * THE URL-SOURCE FLOW TEST (W6 Worker B) — the hermetic route-level proof
 * of the real-source acquisition machine, following the studio-upload-flow
 * pattern exactly: real route handlers over a real composed server
 * (deterministic hasher, in-memory transient state, the real dev seed, the
 * media seams injected), with EVERY media byte REAL — the in-test MP4 is
 * generated by the real ffmpeg (`generateTestMp4`), never a committed
 * fixture. The oEmbed fetcher is a hermetic FAKE (tests never touch the
 * network); the REAL fetcher's honest-absence behavior is asserted through
 * the fake's failure answers.
 *
 * THE ACQUISITION CYCLE (register → begin → ingest → session, every seam
 * REAL):
 *
 *   POST /api/create/url-sources (the exact URL + the SAME rights
 *     declaration vocabulary the upload path uses) → 201: the registration,
 *     born PENDING_TRANSFER, the URL VERBATIM, the public oEmbed metadata
 *     (or its honest absence), and the ONE-TIME acquisition capability;
 *   POST …/[id]/transfer {phase: "begin"} → ACQUIRING (recorded BEFORE any
 *     byte moves);
 *   POST …/[id]/transfer {phase: "ingest", bytesPath, via, claimed} → the
 *     SEAM measures the bytes itself (size + sha-256, cross-checked against
 *     the claim), re-derives the rights posture at ingestion time, and runs
 *     the studio's OWN upload-path session creation over the bytes (the
 *     W101/W102 boundary + the R207 pipeline + the W921 write-through) →
 *     ACQUIRED + the session join;
 *   GET /api/create/sessions/[id] → the source's COMBINED truth (the
 *     registration's acquisition record JOINED with the same R101 records
 *     the upload path serves);
 *   the media job settles succeeded; the catalog's `original` reality is
 *     READY (the stored artifact).
 *
 * THE HONEST NEGATIVES: an integrity claim that does not match the bytes
 * refuses typed (422) and records FAILED — nothing ingested; a non-mp4
 * transfer refuses through the R101 boundary's own class and is recorded;
 * ingest without begin refuses (409); a re-ingest over an ACQUIRED
 * registration refuses (409); a wrong/missing capability answers the SAME
 * uniform 404 as an unknown registration (no oracle); a declaration that
 * cannot transform refuses registration itself (fail-closed); a
 * non-owner's read answers the uniform 404. THE STRUCTURAL NEGATIVE: the
 * fixture path and the upload path leave NO url-source registration behind
 * — only the seam ever writes ACQUIRED (the validating store refuses
 * anything without the measured integrity + the session join).
 *
 * THE DURABLE VARIANT (the second describe): two compositions over the
 * SAME durable planes — the shared record store + the shared url-source
 * store + ONE sqlite media db file + one storage dir. Instance A registers
 * + ingests; instance B (which never saw A's in-process state)
 * RECONSTRUCTS the session through the durable layer's `urlsrc:` join: the
 * registration must be ACQUIRED, the stored bytes hash-verified, and the
 * R207 pipeline re-run over them — the same engine determinism the upload
 * variant proves.
 */
import { beforeAll, afterAll, describe, expect, test } from "bun:test";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  InMemoryAccountStore,
  InMemoryMediaOwnershipStore,
  InMemorySessionStore,
  SessionService,
  createDeterministicTestHasher,
  createSequentialEntropySource,
} from "@sporta/identity";
import { generateTestMp4, LocalFilesystemStorage, sha256OfBytes } from "@sporta/media-platform";
import { createSportaServer, installSportaServerForTests } from "../src/server/composition";
import type { SportaServer } from "../src/server/composition";
import { SPORTA_SESSION_COOKIE } from "../src/server/auth-service";
import { InMemoryControlPlaneRecordStore } from "../src/server/platform/control/records";
import { InMemoryRedis } from "../src/server/platform/upstash/redis";
import { InMemoryUrlSourceStore } from "../src/server/url-source-service";
import type { UrlOEmbedFetcher } from "../src/server/url-source-service";
import { POST as registerRoute, GET as listRoute } from "../src/app/api/create/url-sources/route";
import { GET as showRoute } from "../src/app/api/create/url-sources/[registrationId]/route";
import { POST as transferRoute } from "../src/app/api/create/url-sources/[registrationId]/transfer/route";
import { POST as oembedPreviewRoute } from "../src/app/api/create/url-source-oembed-preview/route";
import { GET as sessionStateRoute } from "../src/app/api/create/sessions/[sessionId]/route";
import { GET as catalogArtifactsRoute } from "../src/app/api/catalog/sessions/[sessionId]/artifacts/route";
import { POST as uploadSessionRoute } from "../src/app/api/create/upload-sessions/route";
import { POST as fixtureSessionRoute } from "../src/app/api/create/sessions/route";

/** A deterministic stepping clock (the repo's hermetic rig). */
function steppingClock(): () => number {
  let current = 1_888_888_888_000;
  return () => {
    current += 17;
    return current;
  };
}

const SOURCE_URL = "https://www.youtube.com/watch?v=93LPZJkCW2w";
const OPERATIONS = ["analysis", "transformation", "derivativeGeneration", "storage"];

/** The hermetic oEmbed fake (tests never touch the network). */
const OEMBED_SUCCESS: UrlOEmbedFetcher = async () => ({
  ok: true,
  metadata: {
    title: "BETIS 3 vs 5 FC BARCELONA | LALIGA 2025/26 MD15 (hermetic fixture answer)",
    authorName: "FC Barcelona",
    thumbnailUrl: null,
    providerName: "YouTube",
  },
});
const OEMBED_WALLED: UrlOEmbedFetcher = async (url) => ({
  ok: false,
  reason: `the public oEmbed endpoint answered HTTP 403 for '${url}' (the hermetic bot-wall fixture) — the metadata stays honestly absent`,
});

function withCookie(token: string | null, path: string, init: RequestInit = {}): Request {
  return new Request(`http://sporta.test${path}`, {
    ...init,
    headers: {
      ...((init.headers as Record<string, string> | undefined) ?? {}),
      ...(token === null ? {} : { cookie: `${SPORTA_SESSION_COOKIE}=${token}` }),
    },
  });
}

async function bodyOf(response: Response): Promise<Record<string, unknown>> {
  return (await response.json()) as Record<string, unknown>;
}

function jsonPost(payload: unknown): RequestInit {
  return {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(payload),
  };
}

/** A transfer-route request carrying the machine capability. */
function transferRequest(
  registrationId: string,
  capability: string | null,
  payload: unknown,
): Request {
  return new Request(
    `http://sporta.test/api/create/url-sources/${encodeURIComponent(registrationId)}/transfer`,
    {
      method: "POST",
      headers: {
        "content-type": "application/json",
        accept: "application/json",
        ...(capability === null ? {} : { "x-acquisition-token": capability }),
      },
      body: JSON.stringify(payload),
    },
  );
}

/** Registers a URL source through the real route; returns the answer. */
async function registerSource(
  token: string,
  url: string,
  operations: string[] = OPERATIONS,
  extra: Record<string, unknown> = {},
): Promise<{ status: number; body: Record<string, unknown> }> {
  const response = await registerRoute(
    withCookie(
      token,
      "/api/create/url-sources",
      jsonPost({ url, operations, sharingScope: "private", ...extra }),
    ),
  );
  return { status: response.status, body: await bodyOf(response) };
}

describe("the url-source acquisition machine (W6 Worker B: register → begin → ingest → session)", () => {
  let server: SportaServer;
  let scratch = "";
  let creatorToken = "";
  let outsiderToken = "";
  /** The main happy-path registration. */
  let registrationId = "";
  let capability = "";
  let sessionId = "";
  let mediaJobId = "";
  let clipPath = "";
  let clipBytes = new Uint8Array(0);
  /** The J004 plan registration (anime-npr). */
  let planRegistrationId = "";
  let planCapability = "";
  let planSessionId = "";

  beforeAll(async () => {
    scratch = await mkdtemp(join(tmpdir(), "sporta-url-source-"));
    server = createSportaServer({
      nowMs: steppingClock(),
      passwordHasher: createDeterministicTestHasher(),
      transient: { redis: new InMemoryRedis(steppingClock()), provider: "in-memory" },
      seed: true,
      media: {
        db: ":memory:",
        storage: new LocalFilesystemStorage(join(scratch, "media-storage")),
      },
      urlSources: {
        db: ":memory:",
        // The hermetic oEmbed fake: the YouTube-family URL answers with the
        // fixture metadata; every other URL answers the honest wall.
        fetchOEmbed: async (url) =>
          url.includes("93LPZJkCW2w") ? OEMBED_SUCCESS(url) : OEMBED_WALLED(url),
      },
    });
    installSportaServerForTests(server);
    await server.ready;

    const registered = await server.auth.register({
      username: "url-source-creator",
      password: "a-real-url-source-password",
      roles: ["creator", "viewer"],
    });
    creatorToken = (await server.auth.issueSession({ userId: registered.userId })).token;
    const outsider = await server.auth.register({
      username: "url-source-outsider",
      password: "another-real-password",
      roles: ["viewer"],
    });
    outsiderToken = (await server.auth.issueSession({ userId: outsider.userId })).token;

    // The real transferred bytes (the in-test stand-in: a REAL ffmpeg MP4 —
    // legitimate engineering evidence for the machine, explicitly NOT the
    // operator's real source).
    clipPath = await generateTestMp4(join(scratch, "transferred.mp4"), {
      durationSeconds: 2,
      withAudio: true,
    });
    clipBytes = new Uint8Array(await Bun.file(clipPath).arrayBuffer());
  });

  afterAll(async () => {
    await rm(scratch, { recursive: true, force: true });
  });

  test("W6-a: registration records the URL verbatim, the honest oEmbed, and the capability", async () => {
    const { status, body } = await registerSource(creatorToken, SOURCE_URL);
    expect(status).toBe(201);
    expect(body.url).toBe(SOURCE_URL);
    expect(body.oEmbed).toMatchObject({
      title: "BETIS 3 vs 5 FC BARCELONA | LALIGA 2025/26 MD15 (hermetic fixture answer)",
      authorName: "FC Barcelona",
      unavailableReason: null,
    });
    expect((body.acquisition as Record<string, unknown>).state).toBe("PENDING_TRANSFER");
    expect((body.acquisition as Record<string, unknown>).method).toBe("operator-transfer");
    expect((body.acquisition as Record<string, unknown>).integrity).toBeNull();
    expect(body.sessionId).toBeNull();
    expect(typeof body.acquisitionCapability).toBe("string");
    expect((body.acquisitionCapability as string).length).toBeGreaterThan(0);
    registrationId = body.registrationId as string;
    capability = body.acquisitionCapability as string;
  });

  test("W6-b: a bot-walled host records the honest absence — never a fabricated title", async () => {
    // The preview route answers the honest absence for a non-matching URL.
    const preview = await oembedPreviewRoute(
      withCookie(
        creatorToken,
        "/api/create/url-source-oembed-preview",
        jsonPost({ url: "https://www.youtube.com/watch?v=another-video-id" }),
      ),
    );
    expect(preview.status).toBe(200);
    const previewBody = (await bodyOf(preview)) as { available: boolean; reason?: string };
    expect(previewBody.available).toBe(false);
    expect(previewBody.reason ?? "").toContain("honestly absent");

    // A registration over the walled URL still succeeds — with the honest
    // absence recorded on the registration itself.
    const { status, body } = await registerSource(
      creatorToken,
      "https://www.youtube.com/watch?v=another-video-id",
    );
    expect(status).toBe(201);
    expect((body.oEmbed as Record<string, unknown>).title).toBeNull();
    expect(String((body.oEmbed as Record<string, unknown>).unavailableReason ?? "")).toContain(
      "honestly absent",
    );
  });

  test("W6-c: the honest registration refusals (rights fail-closure, url parse, anonymous)", async () => {
    // A declaration that cannot transform refuses registration itself (the
    // media pipeline references source frames — fail-closed).
    const noTransform = await registerSource(creatorToken, SOURCE_URL, ["analysis"]);
    expect(noTransform.status).toBe(403);
    expect(((noTransform.body.error as Record<string, unknown>) ?? {}).failureClass).toBe(
      "rights-denied",
    );

    // An unparsable url answers the typed 400.
    const badUrl = await registerSource(creatorToken, "not-a-url");
    expect(badUrl.status).toBe(400);
    expect(((badUrl.body.error as Record<string, unknown>) ?? {}).failureClass).toBe("url-invalid");

    // http (not https) refuses the same way.
    const httpUrl = await registerSource(creatorToken, `http://${SOURCE_URL.slice(8)}`);
    expect(httpUrl.status).toBe(400);

    // Anonymous callers get the real 401.
    const anonymous = await registerRoute(
      withCookie(
        null,
        "/api/create/url-sources",
        jsonPost({ url: SOURCE_URL, operations: OPERATIONS }),
      ),
    );
    expect(anonymous.status).toBe(401);
  });

  test("W6-d: THE SEAM — begin → ingest binds the real bytes into a real session (ACQUIRED)", async () => {
    // begin (the honest in-flight state, BEFORE any byte moves).
    const begin = await transferRoute(
      transferRequest(registrationId, capability, {
        phase: "begin",
        kind: "file",
        detail: "test transfer",
      }),
      { params: Promise.resolve({ registrationId: registrationId }) },
    );
    expect(begin.status).toBe(200);
    expect(((await bodyOf(begin)).registration as Record<string, unknown>).state).toBe("ACQUIRING");

    // ingest — the seam measures the bytes itself and cross-checks the claim.
    const claim = { byteSize: clipBytes.byteLength, sha256: sha256OfBytes(clipBytes) };
    const ingest = await transferRoute(
      transferRequest(registrationId, capability, {
        phase: "ingest",
        bytesPath: clipPath,
        via: { kind: "file", detail: "the operator's transferred file (test stand-in)" },
        claimed: claim,
      }),
      { params: Promise.resolve({ registrationId: registrationId }) },
    );
    expect(ingest.status).toBe(200);
    const ingestBody = (await bodyOf(ingest)) as {
      registration: {
        acquisition: { state: string; integrity: { byteSize: number; sha256: string } };
        sessionId: string;
        assetId: string;
      };
      session: {
        sessionId: string;
        source: {
          asset: {
            contentHash: string;
            uploadState: string;
            checksumVerified: boolean;
            container: string;
          };
          job: { jobId: string; state: string } | null;
        };
        perception: { frameCount: number };
      };
    };
    expect(ingestBody.registration.acquisition.state).toBe("ACQUIRED");
    expect(ingestBody.registration.acquisition.integrity.sha256).toBe(claim.sha256);
    expect(ingestBody.registration.acquisition.integrity.byteSize).toBe(claim.byteSize);
    expect(ingestBody.registration.sessionId).toBe(ingestBody.session.sessionId);
    sessionId = ingestBody.session.sessionId;
    mediaJobId = ingestBody.session.source.job?.jobId ?? "";
    // The R101 boundary's own records over the transferred bytes.
    expect(ingestBody.session.source.asset.contentHash).toBe(claim.sha256);
    expect(ingestBody.session.source.asset.uploadState).toBe("stored");
    expect(ingestBody.session.source.asset.checksumVerified).toBe(true);
    expect(ingestBody.session.source.asset.container).toBe("mp4");
    // The R207 pipeline ran over the TRANSFERRED frames.
    expect(ingestBody.session.perception.frameCount).toBeGreaterThan(0);

    // The session state's COMBINED truth: the registration + the R101 records.
    const state = await sessionStateRoute(
      withCookie(creatorToken, `/api/create/sessions/${sessionId}`),
      { params: Promise.resolve({ sessionId }) },
    );
    expect(state.status).toBe(200);
    const stateBody = (await bodyOf(state)) as {
      source:
        | ({
            kind: "url";
            registration: {
              url: string;
              acquisition: { state: string; integrity: { sha256: string } | null };
            };
          } & Record<string, unknown>)
        | { kind: string }
        | null;
    };
    expect(stateBody.source).not.toBeNull();
    expect((stateBody.source as { kind: string }).kind).toBe("url");
    const urlSource = stateBody.source as unknown as {
      registration: {
        url: string;
        acquisition: { state: string; integrity: { sha256: string } | null };
      };
      asset: { contentHash: string; assetId: string };
      job: { state: string } | null;
    };
    expect(urlSource.registration.url).toBe(SOURCE_URL);
    expect(urlSource.registration.acquisition.state).toBe("ACQUIRED");
    expect(urlSource.registration.acquisition.integrity?.sha256).toBe(claim.sha256);
    expect(urlSource.asset.contentHash).toBe(claim.sha256);

    // The media job settles succeeded (the real normalization pipeline).
    let jobView = server.media.jobView(mediaJobId);
    for (let attempt = 0; attempt < 240 && jobView !== null && !jobView.terminal; attempt += 1) {
      await new Promise((resolve) => setTimeout(resolve, 25));
      jobView = server.media.jobView(mediaJobId);
    }
    expect(jobView?.state).toBe("succeeded");

    // The catalog's `original` reality is READY (the stored artifact).
    const catalog = await catalogArtifactsRoute(
      withCookie(creatorToken, `/api/catalog/sessions/${sessionId}/artifacts`),
      { params: Promise.resolve({ sessionId }) },
    );
    expect(catalog.status).toBe(200);
    const catalogBody = (await bodyOf(catalog)) as {
      realities: { kind: string; availability: string }[] | null;
    };
    const original = (catalogBody.realities ?? []).find((entry) => entry.kind === "original");
    expect(original?.availability).toBe("ready");
  });

  test("W6-e: the J004 plan parameters ride the registration and replay at ingestion", async () => {
    const { status, body } = await registerSource(creatorToken, SOURCE_URL, OPERATIONS, {
      realities: ["anime-npr"],
      compute: { mode: "sporta-auto" },
      styleId: "url-source-test-style",
    });
    expect(status).toBe(201);
    planRegistrationId = body.registrationId as string;
    planCapability = body.acquisitionCapability as string;

    await transferRoute(
      transferRequest(planRegistrationId, planCapability, {
        phase: "begin",
        kind: "file",
        detail: "plan transfer",
      }),
      { params: Promise.resolve({ registrationId: planRegistrationId }) },
    );
    const ingest = await transferRoute(
      transferRequest(planRegistrationId, planCapability, {
        phase: "ingest",
        bytesPath: clipPath,
        via: { kind: "file", detail: "the operator's transferred file (test stand-in)" },
        claimed: { byteSize: clipBytes.byteLength, sha256: sha256OfBytes(clipBytes) },
      }),
      { params: Promise.resolve({ registrationId: planRegistrationId }) },
    );
    expect(ingest.status).toBe(200);
    const ingestBody = (await bodyOf(ingest)) as {
      registration: { sessionId: string };
      session: { renderPlan?: { realities: { reality: string; disposition: string }[] } };
    };
    const plan = ingestBody.session.renderPlan?.realities ?? [];
    expect(plan.some((entry) => entry.reality === "anime-npr")).toBe(true);
    planSessionId = ingestBody.registration.sessionId;

    // The plan's job rides the EXISTING session-state surface.
    const state = await sessionStateRoute(
      withCookie(creatorToken, `/api/create/sessions/${planSessionId}`),
      { params: Promise.resolve({ sessionId: planSessionId }) },
    );
    const stateBody = (await bodyOf(state)) as { jobs: { jobId: string; state: string }[] };
    expect(stateBody.jobs.length).toBeGreaterThanOrEqual(1);
  });

  test("W6-f: an integrity mismatch refuses typed and records FAILED — nothing ingested; a non-mp4 transfer refuses through the R101 boundary", async () => {
    const { body } = await registerSource(creatorToken, SOURCE_URL);
    const mismatchId = body.registrationId as string;
    const mismatchCapability = body.acquisitionCapability as string;

    await transferRoute(
      transferRequest(mismatchId, mismatchCapability, {
        phase: "begin",
        kind: "file",
        detail: "mismatch test",
      }),
      { params: Promise.resolve({ registrationId: mismatchId }) },
    );
    // A WRONG sha-256 claim → the seam's measured integrity disagrees.
    const mismatch = await transferRoute(
      transferRequest(mismatchId, mismatchCapability, {
        phase: "ingest",
        bytesPath: clipPath,
        via: { kind: "file", detail: "mismatch test" },
        claimed: { byteSize: clipBytes.byteLength, sha256: "0".repeat(64) },
      }),
      { params: Promise.resolve({ registrationId: mismatchId }) },
    );
    expect(mismatch.status).toBe(422);
    expect(((await bodyOf(mismatch)).error as Record<string, unknown>).failureClass).toBe(
      "integrity-mismatch",
    );

    // The registration records the honest FAILED state — no session join.
    const failedShow = await showRoute(
      withCookie(creatorToken, `/api/create/url-sources/${mismatchId}`),
      { params: Promise.resolve({ registrationId: mismatchId }) },
    );
    const failedBody = (await bodyOf(failedShow)) as {
      acquisition: { state: string; failureReason: string | null };
      sessionId: string | null;
    };
    expect(failedBody.acquisition.state).toBe("FAILED");
    expect(failedBody.acquisition.failureReason ?? "").toContain("integrity");
    expect(failedBody.sessionId).toBeNull();

    // Retry: begin again, then a NON-mp4 transfer — the R101 boundary's own
    // typed refusal, recorded as FAILED (never a silent fallback).
    await transferRoute(
      transferRequest(mismatchId, mismatchCapability, {
        phase: "begin",
        kind: "file",
        detail: "non-mp4 retry",
      }),
      { params: Promise.resolve({ registrationId: mismatchId }) },
    );
    const textPath = join(scratch, "not-a-video.txt");
    await writeFile(textPath, "these are not video bytes");
    const nonMp4 = await transferRoute(
      transferRequest(mismatchId, mismatchCapability, {
        phase: "ingest",
        bytesPath: textPath,
        via: { kind: "file", detail: "non-mp4 retry" },
      }),
      { params: Promise.resolve({ registrationId: mismatchId }) },
    );
    expect(nonMp4.status).toBe(400);
    expect(((await bodyOf(nonMp4)).error as Record<string, unknown>).failureClass).toBe(
      "media-invalid",
    );
    const afterNonMp4 = (await bodyOf(
      await showRoute(withCookie(creatorToken, `/api/create/url-sources/${mismatchId}`), {
        params: Promise.resolve({ registrationId: mismatchId }),
      }),
    )) as { acquisition: { state: string; failureReason: string | null } };
    expect(afterNonMp4.acquisition.state).toBe("FAILED");
    expect(afterNonMp4.acquisition.failureReason ?? "").toContain("container");
  });

  test("W6-g: the capability gate answers UNIFORM 404s (no oracle); ingest requires the begin phase", async () => {
    // A missing capability header, a wrong capability, and an unknown
    // registration all answer the same shape.
    const missing = await transferRoute(transferRequest(registrationId, null, { phase: "show" }), {
      params: Promise.resolve({ registrationId: registrationId }),
    });
    expect(missing.status).toBe(404);
    const wrong = await transferRoute(
      transferRequest(registrationId, "a-wrong-capability-token", { phase: "show" }),
      { params: Promise.resolve({ registrationId: registrationId }) },
    );
    expect(wrong.status).toBe(404);
    const unknown = await transferRoute(
      transferRequest("urlreg-doesnotexist", capability, { phase: "show" }),
      { params: Promise.resolve({ registrationId: "urlreg-doesnotexist" }) },
    );
    expect(unknown.status).toBe(404);
    // The UNIFORM shape: status + failureClass + message are identical (the
    // registrationId detail rides only for the caller's own correlation).
    const missingBody = (await bodyOf(missing)) as {
      error: { failureClass: string; message: string };
    };
    const unknownBody = (await bodyOf(unknown)) as {
      error: { failureClass: string; message: string };
    };
    expect(missingBody.error.failureClass).toBe(unknownBody.error.failureClass);
    expect(missingBody.error.message).toBe(unknownBody.error.message);

    // Ingest WITHOUT begin refuses (the in-flight state is the honest trace).
    const { body } = await registerSource(creatorToken, SOURCE_URL);
    const pendingId = body.registrationId as string;
    const pendingCapability = body.acquisitionCapability as string;
    const noBegin = await transferRoute(
      transferRequest(pendingId, pendingCapability, {
        phase: "ingest",
        bytesPath: clipPath,
        via: { kind: "file", detail: "no-begin test" },
      }),
      { params: Promise.resolve({ registrationId: pendingId }) },
    );
    expect(noBegin.status).toBe(409);
    expect(((await bodyOf(noBegin)).error as Record<string, unknown>).failureClass).toBe(
      "state-conflict",
    );
  });

  test("W6-h: an ACQUIRED registration refuses a second ingest (the join exists)", async () => {
    const again = await transferRoute(
      transferRequest(registrationId, capability, {
        phase: "ingest",
        bytesPath: clipPath,
        via: { kind: "file", detail: "re-ingest test" },
      }),
      { params: Promise.resolve({ registrationId: registrationId }) },
    );
    expect(again.status).toBe(409);
    const body = (await bodyOf(again)) as { error: { failureClass: string; message: string } };
    expect(body.error.failureClass).toBe("state-conflict");
    expect(body.error.message).toContain("already ACQUIRED");
  });

  test("W6-i: fail records the honest reason; the retry cycle works (begin → ingest → ACQUIRED)", async () => {
    const { body } = await registerSource(creatorToken, SOURCE_URL);
    const retryId = body.registrationId as string;
    const retryCapability = body.acquisitionCapability as string;

    await transferRoute(
      transferRequest(retryId, retryCapability, {
        phase: "begin",
        kind: "cookies",
        detail: "session attempt",
      }),
      { params: Promise.resolve({ registrationId: retryId }) },
    );
    const fail = await transferRoute(
      transferRequest(retryId, retryCapability, {
        phase: "fail",
        reason: "the cookies session was rejected by the host (test)",
      }),
      { params: Promise.resolve({ registrationId: retryId }) },
    );
    expect(fail.status).toBe(200);
    const failedBody = (await bodyOf(fail)) as {
      registration: { state: string; failureReason: string | null };
    };
    expect(failedBody.registration.state).toBe("FAILED");
    expect(failedBody.registration.failureReason).toContain("cookies session");

    // The retry: begin again → ingest the real bytes → ACQUIRED.
    await transferRoute(
      transferRequest(retryId, retryCapability, {
        phase: "begin",
        kind: "file",
        detail: "retry transfer",
      }),
      { params: Promise.resolve({ registrationId: retryId }) },
    );
    const ingest = await transferRoute(
      transferRequest(retryId, retryCapability, {
        phase: "ingest",
        bytesPath: clipPath,
        via: { kind: "file", detail: "retry transfer" },
        claimed: { byteSize: clipBytes.byteLength, sha256: sha256OfBytes(clipBytes) },
      }),
      { params: Promise.resolve({ registrationId: retryId }) },
    );
    expect(ingest.status).toBe(200);
    const acquired = (await bodyOf(ingest)) as {
      registration: { acquisition: { state: string }; sessionId: string };
    };
    expect(acquired.registration.acquisition.state).toBe("ACQUIRED");
    expect(acquired.registration.sessionId.length).toBeGreaterThan(0);
  });

  test("W6-j: the registration reads are owner-only (uniform 404 for anyone else)", async () => {
    const ownerShow = await showRoute(
      withCookie(creatorToken, `/api/create/url-sources/${registrationId}`),
      { params: Promise.resolve({ registrationId }) },
    );
    expect(ownerShow.status).toBe(200);
    const ownerBody = (await bodyOf(ownerShow)) as { url: string; acquisitionCapability: unknown };
    expect(ownerBody.url).toBe(SOURCE_URL);
    // Later reads carry NO capability (it was shown once, at registration).
    expect(ownerBody.acquisitionCapability ?? null).toBeNull();

    const outsiderShow = await showRoute(
      withCookie(outsiderToken, `/api/create/url-sources/${registrationId}`),
      { params: Promise.resolve({ registrationId }) },
    );
    expect(outsiderShow.status).toBe(404);

    const outsiderList = await listRoute(withCookie(outsiderToken, "/api/create/url-sources"));
    expect(outsiderList.status).toBe(200);
    const outsiderRows = (await bodyOf(outsiderList)) as { registrations: { url: string }[] };
    expect(outsiderRows.registrations.every((row) => row.url !== SOURCE_URL)).toBe(true);

    const ownerList = await listRoute(withCookie(creatorToken, "/api/create/url-sources"));
    const ownerRows = (await bodyOf(ownerList)) as { registrations: { url: string }[] };
    expect(ownerRows.registrations.some((row) => row.url === SOURCE_URL)).toBe(true);
  });

  test("W6-k: THE STRUCTURAL NEGATIVE — fixtures and uploads leave no url-source registrations; only the seam writes ACQUIRED", async () => {
    const ownerList = await listRoute(withCookie(creatorToken, "/api/create/url-sources"));
    const before = ((await bodyOf(ownerList)) as { registrations: unknown[] }).registrations.length;

    // A fixture-path session (the dev surface) — its creation never touches
    // the url-source machine.
    const options = await server.studio.listOptions(creatorToken);
    const fixtureKey = options.sources[0]?.key ?? "";
    expect(fixtureKey.length).toBeGreaterThan(0);
    const fixtureSession = await fixtureSessionRoute(
      withCookie(
        creatorToken,
        "/api/create/sessions",
        jsonPost({ sourceKey: fixtureKey, operations: OPERATIONS, sharingScope: "private" }),
      ),
    );
    expect(fixtureSession.status).toBe(201);
    const fixtureBody = (await bodyOf(fixtureSession)) as { sessionId: string };

    // An upload-path session (the R501 browser flow) — same: no registration.
    const form = new FormData();
    form.append(
      "file",
      new File([clipBytes.slice().buffer as ArrayBuffer], "clip.mp4", { type: "video/mp4" }),
    );
    form.append("operations", JSON.stringify(OPERATIONS));
    const uploadSession = await uploadSessionRoute(
      withCookie(creatorToken, "/api/create/upload-sessions", { method: "POST", body: form }),
    );
    expect(uploadSession.status).toBe(201);
    const uploadBody = (await bodyOf(uploadSession)) as { sessionId: string };

    // Neither session's source is a url source; the registration count is
    // unchanged; no phantom ACQUIRED appeared.
    const fixtureState = (await bodyOf(
      await sessionStateRoute(
        withCookie(creatorToken, `/api/create/sessions/${fixtureBody.sessionId}`),
        { params: Promise.resolve({ sessionId: fixtureBody.sessionId }) },
      ),
    )) as { source: { kind: string } | null };
    expect(fixtureState.source?.kind).toBe("fixture");
    const uploadState = (await bodyOf(
      await sessionStateRoute(
        withCookie(creatorToken, `/api/create/sessions/${uploadBody.sessionId}`),
        { params: Promise.resolve({ sessionId: uploadBody.sessionId }) },
      ),
    )) as { source: { kind: string } | null };
    expect(uploadState.source?.kind).toBe("upload");

    const afterList = await listRoute(withCookie(creatorToken, "/api/create/url-sources"));
    const afterRows = (
      (await bodyOf(afterList)) as {
        registrations: { acquisition: { state: string; integrity?: { sha256: string } } }[];
      }
    ).registrations;
    expect(afterRows.length).toBe(before);
    // Every ACQUIRED row came from THIS test file's seam ingests (each one
    // carries the session + the measured integrity — the validating store's
    // own guard).
    for (const row of afterRows) {
      if (row.acquisition.state === "ACQUIRED") {
        expect(row.acquisition.integrity ?? undefined).toBeDefined();
      }
    }
  });

  test("W6-m: the sqlite store creates its durable home on demand (a fresh checkout has no db/ — the CI L014 regression)", async () => {
    // The CI failure shape: the composition's DEFAULT path (db/url-source.db)
    // on a fresh checkout whose parent directory does not exist. The store
    // must create the parent (the media-platform store's exact precedent),
    // never answer SQLITE_CANTOPEN up to the fail-loud composition.
    const { SqliteUrlSourceStore } =
      await import("../src/server/platform/url-source/sqlite-url-source-store");
    const home = await mkdtemp(join(tmpdir(), "w6m-url-source-home-"));
    try {
      const nested = join(home, "deeply", "nested", "db", "url-source.db");
      const store = new SqliteUrlSourceStore(nested);
      // The store is usable and the file now exists at the exact path.
      const rows = await store.listByOwner("w6-m-owner");
      expect(rows).toEqual([]);
      store.close();
      const { stat } = await import("node:fs/promises");
      const info = await stat(nested);
      expect(info.isFile()).toBe(true);
    } finally {
      await rm(home, { recursive: true, force: true });
    }
  });
});

describe("the url-source durable reconstruction (W6 Worker B: the urlsrc: join across instances)", () => {
  const NOW_MS_A = 1_777_900_000_000;
  const NOW_MS_B = 1_778_000_000_000;

  let scratch = "";
  let serverA: SportaServer;
  let serverB: SportaServer;
  let creatorToken = "";

  beforeAll(async () => {
    scratch = await mkdtemp(join(tmpdir(), "sporta-url-source-durable-"));
    // The SHARED durable planes: identity + records + ONE media db file +
    // one storage dir + the shared url-source store (what a durable
    // deployment shares).
    const accounts = new InMemoryAccountStore();
    const sessions = new SessionService({
      store: new InMemorySessionStore(),
      nowMs: () => NOW_MS_A,
      entropy: createSequentialEntropySource(),
    });
    const ownership = new InMemoryMediaOwnershipStore();
    const records = new InMemoryControlPlaneRecordStore();
    const urlSourceStore = new InMemoryUrlSourceStore();
    const mediaDb = join(scratch, "media-platform.db");
    const mediaStorage = new LocalFilesystemStorage(join(scratch, "media-storage"));
    const base = {
      passwordHasher: createDeterministicTestHasher(),
      accounts,
      sessions,
      ownership,
      controlRecords: records,
      media: { db: mediaDb, storage: mediaStorage },
      urlSources: {
        store: urlSourceStore,
        fetchOEmbed: (async () => ({
          ok: false as const,
          reason: "hermetic durable test — no network",
        })) satisfies UrlOEmbedFetcher,
      },
      transient: { redis: new InMemoryRedis(() => NOW_MS_A), provider: "in-memory" as const },
    };
    serverA = createSportaServer({ ...base, nowMs: () => NOW_MS_A, seed: true });
    serverB = createSportaServer({ ...base, nowMs: () => NOW_MS_B, seed: true });
    await serverA.ready;
    await serverB.ready;

    const creator = await serverA.auth.register({
      username: "url-source-durable-creator",
      password: "a-real-durable-password",
      roles: ["creator", "viewer"],
    });
    creatorToken = (await serverA.auth.issueSession({ userId: creator.userId })).token;
  });

  afterAll(async () => {
    await rm(scratch, { recursive: true, force: true });
  });

  test("W6-l: instance B reconstructs the url-source session through the urlsrc: join (ACQUIRED required, bytes re-verified)", async () => {
    // Instance A: register → begin → ingest (the real machine path).
    installSportaServerForTests(serverA);
    const clipPath = await generateTestMp4(join(scratch, "durable.mp4"), {
      durationSeconds: 2,
      withAudio: true,
    });
    const clipBytes = new Uint8Array(await Bun.file(clipPath).arrayBuffer());
    const claim = { byteSize: clipBytes.byteLength, sha256: sha256OfBytes(clipBytes) };

    const registered = await registerRoute(
      withCookie(
        creatorToken,
        "/api/create/url-sources",
        jsonPost({ url: SOURCE_URL, operations: OPERATIONS, sharingScope: "private" }),
      ),
    );
    expect(registered.status).toBe(201);
    const registration = (await bodyOf(registered)) as {
      registrationId: string;
      acquisitionCapability: string;
    };
    await transferRoute(
      transferRequest(registration.registrationId, registration.acquisitionCapability, {
        phase: "begin",
        kind: "file",
        detail: "durable test transfer",
      }),
      { params: Promise.resolve({ registrationId: registration.registrationId }) },
    );
    const ingest = await transferRoute(
      transferRequest(registration.registrationId, registration.acquisitionCapability, {
        phase: "ingest",
        bytesPath: clipPath,
        via: { kind: "file", detail: "durable test transfer" },
        claimed: claim,
      }),
      { params: Promise.resolve({ registrationId: registration.registrationId }) },
    );
    expect(ingest.status).toBe(200);
    const ingestBody = (await bodyOf(ingest)) as {
      registration: { sessionId: string };
      session: { source: { job: { jobId: string } | null } };
    };
    const sessionId = ingestBody.registration.sessionId;
    expect(sessionId.length).toBeGreaterThan(0);

    // Let A's media job settle (the stored-original artifact) BEFORE the
    // instance switch — B's combined-truth read resolves the asset through
    // the SHARED media records.
    const durableMediaJobId = ingestBody.session.source.job?.jobId ?? "";
    let jobView = serverA.media.jobView(durableMediaJobId);
    for (let attempt = 0; attempt < 240 && jobView !== null && !jobView.terminal; attempt += 1) {
      await new Promise((resolve) => setTimeout(resolve, 25));
      jobView = serverA.media.jobView(durableMediaJobId);
    }
    expect(jobView?.state).toBe("succeeded");

    // Instance B: NEVER saw A's in-process state. The session read
    // reconstructs through the durable record's urlsrc: join — the
    // registration must be ACQUIRED, the stored bytes hash-verified, the
    // R207 pipeline re-run (the same engine determinism).
    installSportaServerForTests(serverB);
    const stateOnB = await sessionStateRoute(
      withCookie(creatorToken, `/api/create/sessions/${sessionId}`),
      { params: Promise.resolve({ sessionId }) },
    );
    expect(stateOnB.status).toBe(200);
    const stateBody = (await bodyOf(stateOnB)) as {
      source:
        | ({
            kind: string;
            registration: {
              url: string;
              acquisition: { state: string; integrity: { sha256: string } | null };
            };
            asset: { contentHash: string; assetId: string };
          } & Record<string, unknown>)
        | { kind: string }
        | null;
    };
    expect(stateBody.source).not.toBeNull();
    expect((stateBody.source as { kind: string }).kind).toBe("url");
    const urlSource = stateBody.source as unknown as {
      registration: {
        url: string;
        acquisition: { state: string; integrity: { sha256: string } | null };
      };
      asset: { contentHash: string; assetId: string };
    };
    expect(urlSource.registration.url).toBe(SOURCE_URL);
    expect(urlSource.registration.acquisition.state).toBe("ACQUIRED");
    expect(urlSource.registration.acquisition.integrity?.sha256).toBe(claim.sha256);
    expect(urlSource.asset.contentHash).toBe(claim.sha256);
  });
});
